// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.
//
// Manual additions to Swift.Nuke bindings - not regenerated by the binding generator.
// Contains factory methods that bypass the Mono JIT bug with SwiftArray<ExistentialContainer>.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Swift;
using Swift.Runtime;
using Swift.Runtime.InteropServices;

namespace Swift.Nuke;

/// <summary>
/// Factory methods for creating ImageRequest objects that bypass the SwiftArray&lt;ExistentialContainer&gt; JIT bug.
/// Use these methods instead of the direct ImageRequest constructors that take processors parameters.
/// </summary>
public static unsafe class ImageRequestFactory
{
    // MARK: - Factory Methods (Bypass ExistentialContainer JIT Bug)
    // These methods use Swift wrappers to create ImageRequest objects with empty
    // processors arrays, avoiding the SwiftArray<ExistentialContainer> crash.

    /// <summary>
    /// Creates an ImageRequest from a URL string with default options and no processors.
    /// This bypasses the SwiftArray&lt;ExistentialContainer&gt; crash by using a Swift wrapper.
    /// </summary>
    /// <param name="urlString">The URL string for the image.</param>
    /// <returns>A new ImageRequest instance.</returns>
    public static ImageRequest FromUrlString(string urlString)
    {
        var utf8Bytes = System.Text.Encoding.UTF8.GetBytes(urlString + "\0");
        fixed (byte* ptr = utf8Bytes)
        {
            var swiftPtr = PInvoke_ImageRequest_initWithURLString_simple((IntPtr)ptr);

            // Allocate C# buffer and copy from Swift-allocated memory
            var metadata = SwiftObjectHelper<ImageRequest>.GetTypeMetadata();
            var csharpBuffer = (IntPtr)NativeMemory.Alloc((nuint)metadata.Size);

            // Use value witness table to initialize with copy (handles ARC correctly)
            metadata.ValueWitnessTable->InitializeWithCopy((void*)csharpBuffer, (void*)swiftPtr, metadata);

            // Create the ImageRequest with our copied buffer
            var result = SwiftMarshal.MarshalFromSwift<ImageRequest>(csharpBuffer);

            // Free the Swift-allocated memory (deinitialize + deallocate)
            PInvoke_ImageRequest_free(swiftPtr);

            return result;
        }
    }

    [DllImport("SwiftBindings", EntryPoint = "ImageRequest_initWithURLString_simple")]
    private static extern IntPtr PInvoke_ImageRequest_initWithURLString_simple(IntPtr urlString);

    /// <summary>
    /// Creates an ImageRequest from a URL with default options and no processors.
    /// This is a convenience overload that extracts the URL's absolute string.
    /// </summary>
    /// <param name="url">The URL for the image.</param>
    /// <returns>A new ImageRequest instance.</returns>
    public static ImageRequest FromUrl(Swift.URL url)
    {
        return FromUrlString(url.AbsoluteString);
    }

    /// <summary>
    /// Creates an ImageRequest from a URLRequest with default options and no processors.
    /// This is a convenience overload that extracts the URLRequest's URL.
    /// </summary>
    /// <param name="urlRequest">The URLRequest for the image.</param>
    /// <returns>A new ImageRequest instance.</returns>
    public static ImageRequest FromUrlRequest(Swift.URLRequest urlRequest)
    {
        var url = urlRequest.URL;
        if (url == null)
            throw new ArgumentException("URLRequest must have a valid URL", nameof(urlRequest));
        return FromUrlString(url.AbsoluteString);
    }

    [DllImport("SwiftBindings", EntryPoint = "ImageRequest_free")]
    private static extern void PInvoke_ImageRequest_free(IntPtr ptr);
}
