// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

namespace BindingsGeneration;

public partial class ProtocolProxyEmitter
{
    private void EmitISwiftObjectImplementation(CSharpWriter writer, ProtocolDecl protocolDecl, WitnessDispatchEmitter dispatchEmitter)
    {
        var proxyClassName = GetProxyClassName(protocolDecl);
        var witnessTableSymbol = GetWitnessTableSymbol(protocolDecl);
        var wrapperLibPath = _typeDatabase.AsyncLibraryName ?? _typeDatabase.GetLibraryPath(_moduleName);

        writer.WriteLines($$"""
            #region ISwiftObject Implementation

            /// <summary>
            /// Gets the protocol witness table handle for EveryProtocol conforming to {{protocolDecl.Name}}.
            /// </summary>
            public static IntPtr ProtocolWitnessTableHandle
            {
                get
                {
                    if (_protocolWitnessTable == IntPtr.Zero)
                    {
                        // The witness table is generated by the Swift compiler
                        // It will be available after the Swift wrapper is loaded
                        // For now, we look it up dynamically
                        _protocolWitnessTable = GetWitnessTableFromSwift();
                    }
                    return _protocolWitnessTable;
                }
            }

            private static IntPtr GetWitnessTableFromSwift()
            {
                // Call the Swift-exported function that returns the witness table pointer
                // This function is generated by EveryProtocolEmitter.EmitWitnessTableGetter()
                return NativeMethods.GetWitnessTable();
            }

            /// <summary>
            /// Gets the existential container that can be passed to Swift code.
            /// </summary>
            public ExistentialContainer1 GetExistentialContainer()
            {
                if (_disposed) throw new ObjectDisposedException(GetType().Name);
                return _swiftContainer;
            }

            public static TypeMetadata GetTypeMetadata()
            {
                // Proxy classes don't have their own Swift metadata
                // They use the EveryProtocol metadata
                return EveryProtocol.GetTypeMetadata();
            }

            public static ISwiftObject NewFromPayload(IntPtr payload)
            {
                // Create from existential container
                var container = *(ExistentialContainer1*)payload;
                return new {{proxyClassName}}(container);
            }

            IntPtr ISwiftObject.SwiftHandle => _swiftContainer.Payload0;

            public int MarshalToSwift(ref Span<byte> swiftDestSpan)
            {
                if (_disposed) throw new ObjectDisposedException(GetType().Name);
                // Marshal the existential container
                var size = _swiftContainer.SizeOf;
                if (swiftDestSpan.Length < size)
                    throw new ArgumentException("Destination span too small", nameof(swiftDestSpan));

                fixed (ExistentialContainer1* containerPtr = &_swiftContainer)
                {
                    new Span<byte>(containerPtr, size).CopyTo(swiftDestSpan);
                }
                return size;
            }

            public static ProtocolConformanceDescriptor GetProtocolConformanceDescriptor<TProtocol>() where TProtocol : class
            {
                throw new NotSupportedException(
                    "Protocol conformance descriptor is not available for proxy types. " +
                    "Proxy classes use EveryProtocol's witness table, not native conformance descriptors.");
            }

            public void Dispose()
            {
                if (_disposed) return;
                _disposed = true;
                if (_everyProtocol != null)
                {
                    SwiftObjectRegistry.Unregister(_everyProtocol.Handle);
                    _everyProtocol.Dispose();
                }
            }

            #endregion

            #region Marshalling Helpers

            [StructLayout(LayoutKind.Sequential)]
            private struct Utf8Slice
            {
                public IntPtr Ptr;
                public nint Len;
            }

            private static IntPtr MarshalToSwiftBuffer<T>(T value)
            {
                // Use direct memory operations for all types
                // This works for blittable types (value types, structs with blittable fields)
                var size = Unsafe.SizeOf<T>();
                var ptr = (IntPtr)NativeMemory.Alloc((nuint)size);
                Unsafe.Write((void*)ptr, value);
                return ptr;
            }

            private static T MarshalFromSwift<T>(IntPtr ptr)
            {
                // Use direct memory operations for all types
                return Unsafe.Read<T>((void*)ptr);
            }

            #endregion

            """);

        // Emit NativeMethods for SetVtable + witness dispatch
        var setVtableName = GetSetVtablePInvokeName(protocolDecl);
        var mangledName = $"Set{protocolDecl.Name}_vtable";

        // Note: vtable and witness table functions are in the SwiftBindings wrapper, not the original module
        writer.WriteLine("private static partial class NativeMethods");
        writer.WriteLine("{");
        writer.Indent++;

        PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
        {
            LibraryPath = wrapperLibPath,
            EntryPoint = mangledName,
            MethodName = setVtableName,
            ReturnType = "void",
            ParametersString = "IntPtr vtable",
            CallingConvention = PInvokeCallingConvention.Cdecl,
            Visibility = PInvokeVisibility.Public
        });
        writer.WriteLine();
        PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
        {
            LibraryPath = wrapperLibPath,
            EntryPoint = $"Get_EveryProtocol_{protocolDecl.Name}_WitnessTable",
            MethodName = "GetWitnessTable",
            ReturnType = "IntPtr",
            ParametersString = "",
            CallingConvention = PInvokeCallingConvention.Cdecl,
            Visibility = PInvokeVisibility.Public
        });

        // Emit P/Invoke declarations for witness dispatch accessors
        EmitWitnessDispatchPInvokes(writer, protocolDecl, dispatchEmitter, wrapperLibPath);

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits P/Invoke declarations for witness dispatch accessor and free functions.
    /// </summary>
    private void EmitWitnessDispatchPInvokes(CSharpWriter writer, ProtocolDecl protocolDecl, WitnessDispatchEmitter dispatchEmitter, string wrapperLibPath)
    {
        var protocolName = protocolDecl.Name;
        var emittedPInvokes = new HashSet<string>();

        // Property getters (skip static properties - not part of witness table)
        foreach (var property in protocolDecl.Properties)
        {
            if (property.IsStatic)
                continue;

            var hasGetter = property.Accessors.OfType<GetAccessorDecl>().Any();
            // Only emit blittable/string getter P/Invokes here — class/struct properties
            // fall through to IsPropertyClassReturn/IsPropertyStructReturn branches below.
            // Note: Swift.String is a frozen+RefFields struct, so IsIndirectStructType matches it.
            // We must check IsStringDispatchType first to keep string on the blittable path.
            var isStringProp = WitnessDispatchEmitter.IsStringDispatchType(property.SwiftTypeSpec);
            if (hasGetter && dispatchEmitter.IsPropertyGetterDispatchable(property)
                && (isStringProp || (!dispatchEmitter.IsSwiftClassType(property.SwiftTypeSpec)
                    && !dispatchEmitter.IsIndirectStructType(property.SwiftTypeSpec))))
            {
                var csharpTypeName = GetInterfaceCompatiblePropertyTypeName(property);
                var isStringProperty = WitnessDispatchEmitter.IsStringDispatchType(property.SwiftTypeSpec);
                // Validate projected type allows dispatch (same gate as EmitPropertyImplementation)
                if (!isStringProperty && !WitnessDispatchEmitter.IsBlittablePrimitive(csharpTypeName))
                    continue;

                var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "get", property.Name, 0);
                if (!emittedPInvokes.Add(accessorSymbol))
                    continue;

                var freeSymbol = WitnessDispatchEmitter.GetFreeSymbol(protocolName, "get", property.Name, 0);

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = "IntPtr",
                    ParametersString = "IntPtr containerPtr",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = freeSymbol,
                    MethodName = freeSymbol,
                    ReturnType = "void",
                    ParametersString = "IntPtr ptr",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
            }
            else if (hasGetter && dispatchEmitter.IsPropertyClassReturn(property))
            {
                // ClassReturn getter: returns IntPtr, no free function
                var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "get", property.Name, 0);
                if (!emittedPInvokes.Add(accessorSymbol))
                    continue;

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = "IntPtr",
                    ParametersString = "IntPtr containerPtr",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
            }
            else if (hasGetter && dispatchEmitter.IsPropertyStructReturn(property))
            {
                // StructReturn getter: returns void, has resultBuf param, no free function
                var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "get", property.Name, 0);
                if (!emittedPInvokes.Add(accessorSymbol))
                    continue;

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = "void",
                    ParametersString = "IntPtr containerPtr, IntPtr resultBuf",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
            }
            else if (hasGetter && dispatchEmitter.IsPropertyCollectionReturn(property))
            {
                // BoundGenericReturn getter: returns IntPtr + free function (same shape as ExistentialReturn)
                var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "get", property.Name, 0);
                if (!emittedPInvokes.Add(accessorSymbol))
                    continue;

                var freeSymbol = WitnessDispatchEmitter.GetFreeSymbol(protocolName, "get", property.Name, 0);

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = "IntPtr",
                    ParametersString = "IntPtr containerPtr",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = freeSymbol,
                    MethodName = freeSymbol,
                    ReturnType = "void",
                    ParametersString = "IntPtr ptr",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
            }
        }

        // Property setters (skip static properties - not part of witness table)
        foreach (var property in protocolDecl.Properties)
        {
            if (property.IsStatic)
                continue;

            var hasSetter = property.Accessors.OfType<SetAccessorDecl>().Any();
            // Only emit blittable/string setter P/Invokes — no setter dispatch for class/struct types yet.
            var isSetterStringProp = WitnessDispatchEmitter.IsStringDispatchType(property.SwiftTypeSpec);
            if (hasSetter && dispatchEmitter.IsPropertySetterDispatchable(property)
                && (isSetterStringProp || (!dispatchEmitter.IsSwiftClassType(property.SwiftTypeSpec)
                    && !dispatchEmitter.IsIndirectStructType(property.SwiftTypeSpec))))
            {
                var csharpTypeName = GetInterfaceCompatiblePropertyTypeName(property);
                var isStringProperty = WitnessDispatchEmitter.IsStringDispatchType(property.SwiftTypeSpec);
                // Validate projected type allows dispatch (same gate as EmitPropertyImplementation)
                if (!isStringProperty && !WitnessDispatchEmitter.IsBlittablePrimitive(csharpTypeName))
                    continue;

                var setterSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "set", property.Name, 0);
                if (!emittedPInvokes.Add(setterSymbol))
                    continue;

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = setterSymbol,
                    MethodName = setterSymbol,
                    ReturnType = "void",
                    ParametersString = "IntPtr containerPtr, IntPtr valuePtr",
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
            }
        }

        // Methods
        int methodIndex = 0;
        var methodIndices = new Dictionary<string, int>();
        var emittedCSharpKeys = new HashSet<string>();
        foreach (var method in protocolDecl.Methods)
        {
            if (method.IsConstructor || method.MethodType == MethodType.Static)
                continue;

            var methodKey = ProtocolSignatureHelper.GetMethodSignatureKey(method, _typeDatabase, protocolDecl);
            if (methodIndices.ContainsKey(methodKey))
                continue;

            var idx = methodIndex++;
            methodIndices[methodKey] = idx;

            var projectedKey = ProtocolSignatureHelper.GetProjectedCSharpMethodKey(method, _typeDatabase, protocolDecl);
            if (!emittedCSharpKeys.Add(projectedKey))
                continue;

            var dispatchKind = dispatchEmitter.ClassifyMethodDispatch(method);
            if (dispatchKind == MethodDispatchKind.NotDispatchable)
                continue;

            var returnType = method.CSSignature.FirstOrDefault()?.SwiftTypeSpec;
            var hasReturn = returnType != null && !returnType.IsEmptyTuple;
            var paramCount = method.CSSignature.Count - 1;

            var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "method", method.Name, idx);
            if (!emittedPInvokes.Add(accessorSymbol))
                continue;

            if (dispatchKind is MethodDispatchKind.ExistentialReturn or MethodDispatchKind.ThrowingBlittableOrString or MethodDispatchKind.ClassReturn or MethodDispatchKind.BoundGenericReturn)
            {
                // ExistentialReturn, ThrowingBlittableOrString, ClassReturn, and BoundGenericReturn share the same P/Invoke shape:
                // params: containerPtr + per-param IntPtrs + errorOut (if throwing)
                // return: IntPtr (or void for ThrowingBlittableOrString void)
                var isThrowingKind = dispatchKind == MethodDispatchKind.ThrowingBlittableOrString ||
                                     (dispatchKind == MethodDispatchKind.ExistentialReturn && method.Throws) ||
                                     (dispatchKind == MethodDispatchKind.ClassReturn && method.Throws) ||
                                     (dispatchKind == MethodDispatchKind.BoundGenericReturn && method.Throws);

                var pInvokeParams = new List<string> { "IntPtr containerPtr" };
                for (int i = 0; i < paramCount; i++)
                {
                    pInvokeParams.Add($"IntPtr arg{i}Ptr");
                }
                if (isThrowingKind)
                {
                    pInvokeParams.Add("IntPtr errorOut");
                }
                var pInvokeParamsString = string.Join(", ", pInvokeParams);

                // ThrowingBlittableOrString: value-returning uses IntPtr (nil=error), void uses void
                // ExistentialReturn / ClassReturn: always IntPtr
                var pInvokeReturnType = (dispatchKind == MethodDispatchKind.ThrowingBlittableOrString && !hasReturn)
                    ? "void"
                    : "IntPtr";

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = pInvokeReturnType,
                    ParametersString = pInvokeParamsString,
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });

                // Free function: always for ExistentialReturn and BoundGenericReturn,
                // for value-returning ThrowingBlittableOrString,
                // never for ClassReturn (SafeHandle handles ARC release)
                var needsFree = dispatchKind == MethodDispatchKind.ExistentialReturn ||
                                dispatchKind == MethodDispatchKind.BoundGenericReturn ||
                                (dispatchKind == MethodDispatchKind.ThrowingBlittableOrString && hasReturn);
                if (needsFree)
                {
                    var freeSymbol = WitnessDispatchEmitter.GetFreeSymbol(protocolName, "method", method.Name, idx);
                    writer.WriteLine();
                    PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                    {
                        LibraryPath = wrapperLibPath,
                        EntryPoint = freeSymbol,
                        MethodName = freeSymbol,
                        ReturnType = "void",
                        ParametersString = "IntPtr ptr",
                        CallingConvention = PInvokeCallingConvention.Cdecl,
                        Visibility = PInvokeVisibility.Public
                    });
                }

                // Emit error helper P/Invokes for throwing methods
                if (isThrowingKind)
                {
                    var proxyClassName = GetProxyClassName(protocolDecl);
                    if (!ErrorDescriptionEmitter.HasErrorPInvokeForType(proxyClassName, _emissionContext))
                    {
                        ErrorDescriptionEmitter.MarkErrorPInvokeEmittedForType(proxyClassName, _emissionContext);

                        var descSymbol = ErrorDescriptionEmitter.GetDescriptionSymbolName(_moduleName);
                        var releaseSymbol = ErrorDescriptionEmitter.GetReleaseSymbolName(_moduleName);

                        writer.WriteLine();
                        PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                        {
                            LibraryPath = wrapperLibPath,
                            EntryPoint = descSymbol,
                            MethodName = "SBW_GetErrorDescription",
                            ReturnType = "IntPtr",
                            ParametersString = "IntPtr error",
                            CallingConvention = PInvokeCallingConvention.Cdecl,
                            Visibility = PInvokeVisibility.Public
                        });

                        writer.WriteLine();
                        PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                        {
                            LibraryPath = wrapperLibPath,
                            EntryPoint = releaseSymbol,
                            MethodName = "SBW_ReleaseError",
                            ReturnType = "void",
                            ParametersString = "IntPtr error",
                            CallingConvention = PInvokeCallingConvention.Cdecl,
                            Visibility = PInvokeVisibility.Public
                        });

                        if (!Utf8SliceEmitter.HasFreePInvokeForType(proxyClassName, _emissionContext))
                        {
                            Utf8SliceEmitter.MarkFreePInvokeEmittedForType(proxyClassName, _emissionContext);
                            var freeSwiftSymbol = Utf8SliceEmitter.GetFreeSymbolName(_moduleName);

                            writer.WriteLine();
                            PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                            {
                                LibraryPath = wrapperLibPath,
                                EntryPoint = freeSwiftSymbol,
                                MethodName = "SBW_Free",
                                ReturnType = "void",
                                ParametersString = "IntPtr ptr",
                                CallingConvention = PInvokeCallingConvention.Cdecl,
                                Visibility = PInvokeVisibility.Public
                            });
                        }
                    }
                }
            }
            else if (dispatchKind == MethodDispatchKind.StructReturn)
            {
                // StructReturn: different P/Invoke shape — returns void, has resultBuf param
                var isThrowingStruct = method.Throws;

                var pInvokeParams = new List<string> { "IntPtr containerPtr", "IntPtr resultBuf" };
                for (int i = 0; i < paramCount; i++)
                {
                    pInvokeParams.Add($"IntPtr arg{i}Ptr");
                }
                if (isThrowingStruct)
                {
                    pInvokeParams.Add("IntPtr errorOut");
                }
                var pInvokeParamsString = string.Join(", ", pInvokeParams);

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = "void",
                    ParametersString = pInvokeParamsString,
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });
                // No free function — SafeHandle owns the buffer

                // Emit error helper P/Invokes for throwing struct return methods
                if (isThrowingStruct)
                {
                    var proxyClassName = GetProxyClassName(protocolDecl);
                    if (!ErrorDescriptionEmitter.HasErrorPInvokeForType(proxyClassName, _emissionContext))
                    {
                        ErrorDescriptionEmitter.MarkErrorPInvokeEmittedForType(proxyClassName, _emissionContext);

                        var descSymbol = ErrorDescriptionEmitter.GetDescriptionSymbolName(_moduleName);
                        var releaseSymbol = ErrorDescriptionEmitter.GetReleaseSymbolName(_moduleName);

                        writer.WriteLine();
                        PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                        {
                            LibraryPath = wrapperLibPath,
                            EntryPoint = descSymbol,
                            MethodName = "SBW_GetErrorDescription",
                            ReturnType = "IntPtr",
                            ParametersString = "IntPtr error",
                            CallingConvention = PInvokeCallingConvention.Cdecl,
                            Visibility = PInvokeVisibility.Public
                        });

                        writer.WriteLine();
                        PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                        {
                            LibraryPath = wrapperLibPath,
                            EntryPoint = releaseSymbol,
                            MethodName = "SBW_ReleaseError",
                            ReturnType = "void",
                            ParametersString = "IntPtr error",
                            CallingConvention = PInvokeCallingConvention.Cdecl,
                            Visibility = PInvokeVisibility.Public
                        });

                        if (!Utf8SliceEmitter.HasFreePInvokeForType(proxyClassName, _emissionContext))
                        {
                            Utf8SliceEmitter.MarkFreePInvokeEmittedForType(proxyClassName, _emissionContext);
                            var freeSwiftSymbol = Utf8SliceEmitter.GetFreeSymbolName(_moduleName);

                            writer.WriteLine();
                            PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                            {
                                LibraryPath = wrapperLibPath,
                                EntryPoint = freeSwiftSymbol,
                                MethodName = "SBW_Free",
                                ReturnType = "void",
                                ParametersString = "IntPtr ptr",
                                CallingConvention = PInvokeCallingConvention.Cdecl,
                                Visibility = PInvokeVisibility.Public
                            });
                        }
                    }
                }
            }
            else
            {
                // BlittableOrString: existing pattern
                // Build parameter list: containerPtr + one IntPtr per param
                var pInvokeParams = new List<string> { "IntPtr containerPtr" };
                for (int i = 0; i < paramCount; i++)
                {
                    pInvokeParams.Add($"IntPtr arg{i}Ptr");
                }
                var pInvokeParamsString = string.Join(", ", pInvokeParams);
                var returnTypeStr = hasReturn ? "IntPtr" : "void";

                writer.WriteLine();
                PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                {
                    LibraryPath = wrapperLibPath,
                    EntryPoint = accessorSymbol,
                    MethodName = accessorSymbol,
                    ReturnType = returnTypeStr,
                    ParametersString = pInvokeParamsString,
                    CallingConvention = PInvokeCallingConvention.Cdecl,
                    Visibility = PInvokeVisibility.Public
                });

                if (hasReturn)
                {
                    var freeSymbol = WitnessDispatchEmitter.GetFreeSymbol(protocolName, "method", method.Name, idx);
                    writer.WriteLine();
                    PInvokeEmitHelper.EmitDeclaration(writer, new PInvokeEmissionInfo
                    {
                        LibraryPath = wrapperLibPath,
                        EntryPoint = freeSymbol,
                        MethodName = freeSymbol,
                        ReturnType = "void",
                        ParametersString = "IntPtr ptr",
                        CallingConvention = PInvokeCallingConvention.Cdecl,
                        Visibility = PInvokeVisibility.Public
                    });
                }
            }
        }
    }
}
