// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

namespace BindingsGeneration;

public partial class ProtocolProxyEmitter
{
    private void EmitISwiftObjectImplementation(CSharpWriter writer, ProtocolDecl protocolDecl, WitnessDispatchEmitter dispatchEmitter)
    {
        var proxyClassName = GetProxyClassName(protocolDecl);
        var witnessTableSymbol = GetWitnessTableSymbol(protocolDecl);
        var wrapperLibPath = _typeDatabase.AsyncLibraryName ?? _typeDatabase.GetLibraryPath(_moduleName);

        writer.WriteLines($$"""
            #region ISwiftObject Implementation

            /// <summary>
            /// Gets the protocol witness table handle for EveryProtocol conforming to {{protocolDecl.Name}}.
            /// </summary>
            public static IntPtr ProtocolWitnessTableHandle
            {
                get
                {
                    if (_protocolWitnessTable == IntPtr.Zero)
                    {
                        // The witness table is generated by the Swift compiler
                        // It will be available after the Swift wrapper is loaded
                        // For now, we look it up dynamically
                        _protocolWitnessTable = GetWitnessTableFromSwift();
                    }
                    return _protocolWitnessTable;
                }
            }

            private static IntPtr GetWitnessTableFromSwift()
            {
                // Call the Swift-exported function that returns the witness table pointer
                // This function is generated by EveryProtocolEmitter.EmitWitnessTableGetter()
                return NativeMethods.GetWitnessTable();
            }

            /// <summary>
            /// Gets the existential container that can be passed to Swift code.
            /// </summary>
            public ExistentialContainer1 GetExistentialContainer() => _swiftContainer;

            public static TypeMetadata GetTypeMetadata()
            {
                // Proxy classes don't have their own Swift metadata
                // They use the EveryProtocol metadata
                return EveryProtocol.GetTypeMetadata();
            }

            public static ISwiftObject NewFromPayload(IntPtr payload)
            {
                // Create from existential container
                var container = *(ExistentialContainer1*)payload;
                return new {{proxyClassName}}(container);
            }

            public int MarshalToSwift(ref Span<byte> swiftDestSpan)
            {
                // Marshal the existential container
                var size = _swiftContainer.SizeOf;
                if (swiftDestSpan.Length < size)
                    throw new ArgumentException("Destination span too small", nameof(swiftDestSpan));

                fixed (ExistentialContainer1* containerPtr = &_swiftContainer)
                {
                    new Span<byte>(containerPtr, size).CopyTo(swiftDestSpan);
                }
                return size;
            }

            public static ProtocolConformanceDescriptor GetProtocolConformanceDescriptor<TProtocol>() where TProtocol : class
            {
                throw new NotSupportedException(
                    "Protocol conformance descriptor is not available for proxy types. " +
                    "Proxy classes use EveryProtocol's witness table, not native conformance descriptors.");
            }

            public void Dispose() { }

            #endregion

            #region Marshalling Helpers

            [StructLayout(LayoutKind.Sequential)]
            private struct Utf8Slice
            {
                public IntPtr Ptr;
                public nint Len;
            }

            private static IntPtr MarshalToSwiftBuffer<T>(T value)
            {
                // Use direct memory operations for all types
                // This works for blittable types (value types, structs with blittable fields)
                var size = Unsafe.SizeOf<T>();
                var ptr = (IntPtr)NativeMemory.Alloc((nuint)size);
                Unsafe.Write((void*)ptr, value);
                return ptr;
            }

            private static T MarshalFromSwift<T>(IntPtr ptr)
            {
                // Use direct memory operations for all types
                return Unsafe.Read<T>((void*)ptr);
            }

            #endregion

            """);

        // Emit NativeMethods for SetVtable + witness dispatch
        var setVtableName = GetSetVtablePInvokeName(protocolDecl);
        var mangledName = $"Set{protocolDecl.Name}_vtable";

        // Note: vtable and witness table functions are in the SwiftBindings wrapper, not the original module
        writer.WriteLine("private static partial class NativeMethods");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLines($$"""
            [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
            [LibraryImport("{{wrapperLibPath}}", EntryPoint = "{{mangledName}}")]
            public static partial void {{setVtableName}}(IntPtr vtable);

            [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
            [LibraryImport("{{wrapperLibPath}}", EntryPoint = "Get_EveryProtocol_{{protocolDecl.Name}}_WitnessTable")]
            public static partial IntPtr GetWitnessTable();
            """);

        // Emit P/Invoke declarations for witness dispatch accessors
        EmitWitnessDispatchPInvokes(writer, protocolDecl, dispatchEmitter, wrapperLibPath);

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits P/Invoke declarations for witness dispatch accessor and free functions.
    /// </summary>
    private void EmitWitnessDispatchPInvokes(CSharpWriter writer, ProtocolDecl protocolDecl, WitnessDispatchEmitter dispatchEmitter, string wrapperLibPath)
    {
        var protocolName = protocolDecl.Name;
        var emittedPInvokes = new HashSet<string>();

        // Property getters (skip static properties - not part of witness table)
        foreach (var property in protocolDecl.Properties)
        {
            if (property.IsStatic)
                continue;

            var hasGetter = property.Accessors.OfType<GetAccessorDecl>().Any();
            if (hasGetter && dispatchEmitter.IsPropertyGetterDispatchable(property))
            {
                var csharpTypeName = GetInterfaceCompatiblePropertyTypeName(property);
                var isStringProperty = WitnessDispatchEmitter.IsStringDispatchType(property.SwiftTypeSpec);
                // Validate projected type allows dispatch (same gate as EmitPropertyImplementation)
                if (!isStringProperty && !WitnessDispatchEmitter.IsBlittablePrimitive(csharpTypeName))
                    continue;

                var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "get", property.Name, 0);
                if (!emittedPInvokes.Add(accessorSymbol))
                    continue;

                var freeSymbol = WitnessDispatchEmitter.GetFreeSymbol(protocolName, "get", property.Name, 0);

                writer.WriteLine();
                writer.WriteLines($$"""
                    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
                    [LibraryImport("{{wrapperLibPath}}", EntryPoint = "{{accessorSymbol}}")]
                    public static partial IntPtr {{accessorSymbol}}(IntPtr containerPtr);

                    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
                    [LibraryImport("{{wrapperLibPath}}", EntryPoint = "{{freeSymbol}}")]
                    public static partial void {{freeSymbol}}(IntPtr ptr);
                    """);
            }
        }

        // Property setters (skip static properties - not part of witness table)
        foreach (var property in protocolDecl.Properties)
        {
            if (property.IsStatic)
                continue;

            var hasSetter = property.Accessors.OfType<SetAccessorDecl>().Any();
            if (hasSetter && dispatchEmitter.IsPropertySetterDispatchable(property))
            {
                var csharpTypeName = GetInterfaceCompatiblePropertyTypeName(property);
                var isStringProperty = WitnessDispatchEmitter.IsStringDispatchType(property.SwiftTypeSpec);
                // Validate projected type allows dispatch (same gate as EmitPropertyImplementation)
                if (!isStringProperty && !WitnessDispatchEmitter.IsBlittablePrimitive(csharpTypeName))
                    continue;

                var setterSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "set", property.Name, 0);
                if (!emittedPInvokes.Add(setterSymbol))
                    continue;

                writer.WriteLine();
                writer.WriteLines($$"""
                    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
                    [LibraryImport("{{wrapperLibPath}}", EntryPoint = "{{setterSymbol}}")]
                    public static partial void {{setterSymbol}}(IntPtr containerPtr, IntPtr valuePtr);
                    """);
            }
        }

        // Methods
        int methodIndex = 0;
        var methodIndices = new Dictionary<string, int>();
        var emittedCSharpKeys = new HashSet<string>();
        foreach (var method in protocolDecl.Methods)
        {
            if (method.IsConstructor || method.MethodType == MethodType.Static)
                continue;

            var methodKey = ProtocolSignatureHelper.GetMethodSignatureKey(method, _typeDatabase, protocolDecl);
            if (methodIndices.ContainsKey(methodKey))
                continue;

            var idx = methodIndex++;
            methodIndices[methodKey] = idx;

            var projectedKey = ProtocolSignatureHelper.GetProjectedCSharpMethodKey(method, _typeDatabase, protocolDecl);
            if (!emittedCSharpKeys.Add(projectedKey))
                continue;

            if (dispatchEmitter.IsMethodDispatchable(method))
            {
                var returnType = method.CSSignature.FirstOrDefault()?.SwiftTypeSpec;
                var hasReturn = returnType != null && !returnType.IsEmptyTuple;
                var paramCount = method.CSSignature.Count - 1;

                var accessorSymbol = WitnessDispatchEmitter.GetAccessorSymbol(protocolName, "method", method.Name, idx);
                if (!emittedPInvokes.Add(accessorSymbol))
                    continue;

                // Build parameter list: containerPtr + one IntPtr per param
                var pInvokeParams = new List<string> { "IntPtr containerPtr" };
                for (int i = 0; i < paramCount; i++)
                {
                    pInvokeParams.Add($"IntPtr arg{i}Ptr");
                }
                var pInvokeParamsString = string.Join(", ", pInvokeParams);
                var returnTypeStr = hasReturn ? "IntPtr" : "void";

                writer.WriteLine();
                writer.WriteLines($$"""
                    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
                    [LibraryImport("{{wrapperLibPath}}", EntryPoint = "{{accessorSymbol}}")]
                    public static partial {{returnTypeStr}} {{accessorSymbol}}({{pInvokeParamsString}});
                    """);

                if (hasReturn)
                {
                    var freeSymbol = WitnessDispatchEmitter.GetFreeSymbol(protocolName, "method", method.Name, idx);
                    writer.WriteLines($$"""

                        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
                        [LibraryImport("{{wrapperLibPath}}", EntryPoint = "{{freeSymbol}}")]
                        public static partial void {{freeSymbol}}(IntPtr ptr);
                        """);
                }
            }
        }
    }
}
