// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;
using Microsoft.Extensions.Logging;

namespace BindingsGeneration;

/// <summary>
/// Emits SwiftUI bridge files (Swift wrappers + C# interop) for detected View types.
/// </summary>
public static partial class SwiftUIBridgeEmitter
{
    /// <summary>
    /// Emits bridge files for collected SwiftUI View types.
    /// Generates {namespace}.SwiftUIBridge.swift and {namespace}.SwiftUIBridge.cs
    /// in the specified output directory.
    /// </summary>
    public static void EmitBridgeFiles(
        string outputDirectory,
        string @namespace,
        string moduleName,
        IReadOnlyList<TypeDecl> collectedViews,
        ILogger logger,
        ITypeDatabase? typeDatabase = null,
        ModuleDecl? moduleDecl = null,
        string? bridgeHintsPath = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(@namespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(moduleName);
        ArgumentNullException.ThrowIfNull(collectedViews);
        ArgumentNullException.ThrowIfNull(logger);

        if (collectedViews.Count == 0)
            return;

        var hints = BridgeHintsLoader.Load(bridgeHintsPath, outputDirectory, moduleName, logger);
        var context = new BridgeContext(typeDatabase, moduleDecl, hints);
        var viewInfos = collectedViews.Select(v => AnalyzeView(v, moduleName, context)).ToList();

        // Record skipped views in report, then remove them
        var skippedViews = viewInfos.Where(v => v.Classification == ViewInitClassification.Skipped).ToList();
        foreach (var skipped in skippedViews)
            ReportCollector.RecordBridgedView(skipped.ViewName, moduleName, "Skipped", "HintSkipped");
        viewInfos = viewInfos.Where(v => v.Classification != ViewInitClassification.Skipped).ToList();

        // If all views were skipped, clean up auto-generated bridge files and return
        if (viewInfos.Count == 0)
        {
            CleanupAutoGeneratedBridgeFiles(outputDirectory, @namespace, logger);
            return;
        }

        // Determine which views can be functionally bridged
        var bridgeResults = new List<(ViewBridgeInfo Info, List<BridgeParameter>? Params, AsyncViewPattern? AsyncPattern, bool IsFunctional)>();
        foreach (var info in viewInfos)
        {
            List<BridgeParameter>? bridgeParams = null;
            AsyncViewPattern? asyncPattern = null;
            bool isFunctional = false;
            var viewHint = hints?.Views?.GetValueOrDefault(info.ViewName);

            if (info.Classification == ViewInitClassification.AsyncDependency)
            {
                // For hint-forced async: try inference first, then dictionary
                asyncPattern = info.InferredPattern;
                if (asyncPattern == null && viewHint?.AsyncPattern != null)
                {
                    // Hints forced async classification — try ABI inference
                    asyncPattern = InferAsyncPattern(info, context);
                }
                asyncPattern ??= GetAsyncPattern(info.ViewName, info.ModuleName);
                isFunctional = asyncPattern != null;
            }
            else if (info.Classification == ViewInitClassification.Simple && info.Constructors.Count > 0)
            {
                var ctorIndex = 0;
                if (viewHint?.PreferredInit != null)
                {
                    if (viewHint.PreferredInit.Value >= 0 && viewHint.PreferredInit.Value < info.Constructors.Count)
                        ctorIndex = viewHint.PreferredInit.Value;
                    else
                        logger.LogWarning("preferredInit {Index} out of range for {View} (has {Count} constructors), using 0",
                            viewHint.PreferredInit.Value, info.ViewName, info.Constructors.Count);
                }
                bridgeParams = AnalyzeInitParameters(info.Constructors[ctorIndex], context);
                isFunctional = bridgeParams != null;
            }
            else if (info.Classification == ViewInitClassification.Simple && info.Constructors.Count == 0)
            {
                bridgeParams = new List<BridgeParameter>();
                isFunctional = true;
            }

            bridgeResults.Add((info, bridgeParams, asyncPattern, isFunctional));
        }

        // Record bridged views in report
        foreach (var (info, _, asyncPat, isFunctional) in bridgeResults)
        {
            var status = isFunctional ? "Generated" : "TemplatePending";
            var classification = info.InferredPattern != null
                ? "InferredAsync"
                : info.Classification.ToString();
            ReportCollector.RecordBridgedView(
                info.ViewName, moduleName, classification, status);
        }

        // Collect extra Swift imports from hints (global + per-view)
        var hintImports = CollectHintExtraImports(hints, viewInfos, moduleName);

        var swiftContent = GenerateSwiftBridge(moduleName, bridgeResults, hintImports);
        var csContent = GenerateCSharpBridge(@namespace, moduleName, bridgeResults);

        var swiftPath = Path.Combine(outputDirectory, $"{@namespace}.SwiftUIBridge.swift");
        File.WriteAllText(swiftPath, swiftContent);

        var csPath = Path.Combine(outputDirectory, $"{@namespace}.SwiftUIBridge.cs");
        File.WriteAllText(csPath, csContent);

        var functionalCount = bridgeResults.Count(r => r.IsFunctional);
        var templateCount = bridgeResults.Count - functionalCount;
        logger.LogInformation(
            "SwiftUI bridge files written: {Functional} functional, {Template} templates",
            functionalCount, templateCount);
    }

    /// <summary>
    /// Collects extra Swift imports from bridge hints (global + per-view),
    /// deduplicating and filtering out standard imports.
    /// </summary>
    private static HashSet<string> CollectHintExtraImports(
        BridgeHintsFile? hints, List<ViewBridgeInfo> viewInfos, string moduleName)
    {
        var imports = new HashSet<string>(StringComparer.Ordinal);

        if (hints?.GlobalSettings?.ExtraSwiftImports != null)
        {
            foreach (var imp in hints.GlobalSettings.ExtraSwiftImports)
            {
                if (!string.IsNullOrWhiteSpace(imp))
                    imports.Add(imp);
            }
        }

        if (hints?.Views != null)
        {
            foreach (var info in viewInfos)
            {
                if (hints.Views.TryGetValue(info.ViewName, out var viewHint) && viewHint.ExtraSwiftImports != null)
                {
                    foreach (var imp in viewHint.ExtraSwiftImports)
                    {
                        if (!string.IsNullOrWhiteSpace(imp))
                            imports.Add(imp);
                    }
                }
            }
        }

        // Filter out standard imports that are already emitted
        imports.Remove("UIKit");
        imports.Remove("SwiftUI");
        imports.Remove(moduleName);

        return imports;
    }

    private const string AutoGeneratedMarker = "// Auto-generated by SwiftBindings";

    /// <summary>
    /// Deletes bridge files only if they were auto-generated (contain the marker comment).
    /// User-maintained files are left intact with a warning.
    /// </summary>
    internal static void CleanupAutoGeneratedBridgeFiles(string outputDirectory, string @namespace, ILogger logger)
    {
        var swiftPath = Path.Combine(outputDirectory, $"{@namespace}.SwiftUIBridge.swift");
        var csPath = Path.Combine(outputDirectory, $"{@namespace}.SwiftUIBridge.cs");
        TryDeleteAutoGeneratedFile(swiftPath, logger);
        TryDeleteAutoGeneratedFile(csPath, logger);
    }

    private static void TryDeleteAutoGeneratedFile(string path, ILogger logger)
    {
        if (!File.Exists(path))
            return;

        try
        {
            // Read just the first line to check for the auto-generated marker
            using var reader = new StreamReader(path);
            var firstLine = reader.ReadLine();
            if (firstLine != null && firstLine.StartsWith(AutoGeneratedMarker, StringComparison.Ordinal))
            {
                reader.Close();
                File.Delete(path);
            }
            else
            {
                logger.LogWarning("Bridge file {Path} exists but was not auto-generated; leaving it intact", path);
            }
        }
        catch (IOException ex)
        {
            logger.LogWarning(ex, "Failed to clean up bridge file {Path}", path);
        }
    }

    /// <summary>
    /// Analyzes a View type and classifies its init for bridge generation.
    /// Overload without context — calls through to the context-aware version.
    /// </summary>
    public static ViewBridgeInfo AnalyzeView(TypeDecl viewType, string moduleName)
    {
        return AnalyzeView(viewType, moduleName, context: null);
    }

    /// <summary>
    /// Analyzes a View type and classifies its init for bridge generation.
    /// When a BridgeContext with ModuleDecl is provided, attempts ABI-driven async inference.
    /// </summary>
    public static ViewBridgeInfo AnalyzeView(TypeDecl viewType, string moduleName, BridgeContext? context)
    {
        var constructors = viewType.Methods.Where(m => m.IsConstructor).ToList();
        var viewHint = context?.Hints?.Views?.GetValueOrDefault(viewType.Name);

        // 1. Hints skip (highest priority — overrides everything including generics)
        if (viewHint?.Skip == true)
        {
            return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Skipped,
                viewHint.Reason ?? "Skipped by bridge hints", constructors);
        }

        // 2. Hints forceTemplate
        if (viewHint?.ForceTemplate == true)
        {
            return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Unsupported,
                viewHint.Reason ?? "Forced to template by bridge hints", constructors);
        }

        // 3. Generic type check
        if (viewType.IsGeneric)
        {
            return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Unsupported,
                "Generic type parameter", constructors);
        }

        // 4. Hints asyncPattern (forces async classification; pattern resolved in EmitBridgeFiles)
        if (viewHint?.AsyncPattern != null)
        {
            return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.AsyncDependency,
                null, constructors);
        }

        // 5. Check for known async dependency patterns (takes precedence over inference).
        if (KnownAsyncPatterns.ContainsKey($"{moduleName}.{viewType.Name}"))
        {
            return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.AsyncDependency,
                null, constructors);
        }

        // 6. ABI-driven async inference (Phase 2).
        if (context?.ModuleDecl != null)
        {
            var tempInfo = new ViewBridgeInfo(viewType.Name, moduleName,
                ViewInitClassification.Simple, null, constructors);
            var inferred = InferAsyncPattern(tempInfo, context);
            if (inferred != null)
                return new ViewBridgeInfo(viewType.Name, moduleName,
                    ViewInitClassification.AsyncDependency, null, constructors, inferred);
        }

        if (constructors.Count == 0)
        {
            return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Simple,
                null, constructors);
        }

        // Check each constructor's parameters
        foreach (var ctor in constructors)
        {
            // CSSignature[0] is the return type, skip it
            for (int i = 1; i < ctor.CSSignature.Count; i++)
            {
                var param = ctor.CSSignature[i];

                if (param.IsGeneric)
                {
                    return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Unsupported,
                        "Generic parameter in init", constructors);
                }

                if (param.SwiftTypeSpec is ProtocolListTypeSpec)
                {
                    return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Unsupported,
                        "Existential parameter in init", constructors);
                }
            }
        }

        return new ViewBridgeInfo(viewType.Name, moduleName, ViewInitClassification.Simple,
            null, constructors);
    }

    #region Swift Generation

    private static string GenerateSwiftBridge(
        string moduleName,
        List<(ViewBridgeInfo Info, List<BridgeParameter>? Params, AsyncViewPattern? AsyncPattern, bool IsFunctional)> bridgeResults,
        HashSet<string>? hintImports = null)
    {
        var sb = new StringBuilder();
        bool hasFunctionalBridge = bridgeResults.Any(r => r.IsFunctional);

        if (hasFunctionalBridge)
        {
            sb.AppendLine("// Auto-generated by SwiftBindings — SwiftUI Bridge");
            sb.AppendLine("import UIKit");
            sb.AppendLine("import SwiftUI");
            sb.AppendLine($"import {moduleName}");

            // Extra imports from async patterns
            var extraImports = bridgeResults
                .Where(r => r.AsyncPattern?.ExtraSwiftImports != null)
                .SelectMany(r => r.AsyncPattern!.ExtraSwiftImports)
                .Distinct()
                .Where(m => m != moduleName);
            foreach (var import in extraImports)
            {
                sb.AppendLine($"import {import}");
            }

            // Extra imports from bridge hints
            if (hintImports != null)
            {
                foreach (var import in hintImports.OrderBy(i => i, StringComparer.Ordinal))
                {
                    // Avoid duplicating imports already emitted from async patterns
                    if (!extraImports.Contains(import))
                        sb.AppendLine($"import {import}");
                }
            }

            sb.AppendLine();

            // Shared helpers
            sb.AppendLine("// --- Shared helpers ---");
            sb.AppendLine();
            sb.AppendLine("@discardableResult");
            sb.AppendLine("func SBW_onMainThread<T>(_ block: () -> T) -> T {");
            sb.AppendLine("    if Thread.isMainThread { return block() }");
            sb.AppendLine("    return DispatchQueue.main.sync { block() }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("// Auto-generated by SwiftBindings — SwiftUI Bridge Templates");
            sb.AppendLine("// These templates require manual completion before use.");
            sb.AppendLine("import UIKit");
            sb.AppendLine("import SwiftUI");
            sb.AppendLine($"import {moduleName}");
            sb.AppendLine();
        }

        foreach (var (info, bridgeParams, asyncPattern, isFunctional) in bridgeResults)
        {
            if (isFunctional && asyncPattern != null)
            {
                EmitAsyncSwiftBridge(sb, moduleName, info, asyncPattern);
            }
            else if (isFunctional)
            {
                EmitFunctionalSwiftBridge(sb, moduleName, info, bridgeParams!);
            }
            else
            {
                EmitSwiftTemplate(sb, moduleName, info);
            }
        }

        return sb.ToString();
    }

    private static void EmitFunctionalSwiftBridge(
        StringBuilder sb, string moduleName, ViewBridgeInfo info, List<BridgeParameter> bridgeParams)
    {
        var prefix = $"SBW_{moduleName}_{info.ViewName}";
        var sessionClass = $"{prefix}_Session";
        var handlesVar = $"{prefix}_liveHandles";

        sb.AppendLine($"// --- {info.ViewName} ---");
        sb.AppendLine();

        // Session class
        sb.AppendLine($"final class {sessionClass} {{");
        sb.AppendLine($"    let hostingController: UIHostingController<{info.ViewName}>");

        // Store callback fields
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                sb.AppendLine($"    let {param.Name}Callback: ({param.SwiftAbiType.TrimEnd('?')})?");
                sb.AppendLine($"    let {param.Name}UserData: UnsafeMutableRawPointer?");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                sb.AppendLine($"    let {param.Name}: {param.BridgeTypeName}");
            }
        }

        sb.AppendLine();

        // Init
        sb.Append($"    init(");
        var initParams = new List<string>();
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                initParams.Add($"{param.Name}Callback: {param.SwiftAbiType}");
                initParams.Add($"{param.Name}UserData: UnsafeMutableRawPointer?");
            }
            else if (param.Kind == BridgeParameterKind.String)
            {
                initParams.Add($"{param.Name}Ptr: UnsafePointer<UInt8>?");
                initParams.Add($"{param.Name}Len: Int");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String)
            {
                initParams.Add($"{param.Name}Ptr: UnsafePointer<UInt8>?");
                initParams.Add($"{param.Name}Len: Int");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.BoundType)
            {
                initParams.Add($"{param.Name}Ptr: {param.SwiftAbiType}");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped)
            {
                initParams.Add($"{param.Name}HasValue: Int32");
                initParams.Add($"{param.Name}Value: {param.InnerParameter!.SwiftAbiType}");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                initParams.Add($"{param.Name}Ptr: {param.SwiftAbiType}");
            }
            else
            {
                initParams.Add($"{param.Name}: {param.SwiftAbiType}");
            }
        }
        sb.Append(string.Join(",\n         ", initParams));
        sb.AppendLine(") {");

        // Store callbacks and retain class references
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                sb.AppendLine($"        self.{param.Name}Callback = {param.Name}Callback");
                sb.AppendLine($"        self.{param.Name}UserData = {param.Name}UserData");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                sb.AppendLine($"        self.{param.Name} = Unmanaged<{param.BridgeTypeName}>.fromOpaque({param.Name}Ptr).takeUnretainedValue()");
            }
        }

        // Capture locals for closure safety
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                sb.AppendLine($"        let cb_{param.Name} = {param.Name}Callback; let ud_{param.Name} = {param.Name}UserData");
            }
        }

        // Build view init call
        var viewInitArgs = new List<string>();
        foreach (var param in bridgeParams)
        {
            if (param.Kind == BridgeParameterKind.VoidClosure)
            {
                viewInitArgs.Add($"{param.Name}: {{\n            DispatchQueue.main.async {{ cb_{param.Name}?(ud_{param.Name}) }}\n        }}");
            }
            else if (param.Kind == BridgeParameterKind.TypedClosure)
            {
                viewInitArgs.Add(BuildTypedClosureViewInitArg(param));
            }
            else if (param.Kind == BridgeParameterKind.String)
            {
                sb.AppendLine($"        let {param.Name}String: String");
                sb.AppendLine($"        if let ptr = {param.Name}Ptr, {param.Name}Len > 0 {{");
                sb.AppendLine($"            {param.Name}String = String(bytes: UnsafeBufferPointer(start: ptr, count: {param.Name}Len), encoding: .utf8) ?? \"\"");
                sb.AppendLine($"        }} else {{");
                sb.AppendLine($"            {param.Name}String = \"\"");
                sb.AppendLine($"        }}");
                viewInitArgs.Add($"{param.Name}: {param.Name}String");
            }
            else if (param.Kind == BridgeParameterKind.BoundEnum)
            {
                // Construct enum from rawValue
                viewInitArgs.Add($"{param.Name}: {param.BridgeTypeName}(rawValue: {param.Name})!");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                // Pass the reconstructed Swift object
                viewInitArgs.Add($"{param.Name}: self.{param.Name}");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String)
            {
                // Optional<String>: nil check branching
                sb.AppendLine($"        let {param.Name}String: String?");
                sb.AppendLine($"        if {param.Name}Ptr == nil {{ {param.Name}String = nil }}");
                sb.AppendLine($"        else if {param.Name}Len > 0 {{ {param.Name}String = String(bytes: UnsafeBufferPointer(start: {param.Name}Ptr!, count: {param.Name}Len), encoding: .utf8) ?? \"\" }}");
                sb.AppendLine($"        else {{ {param.Name}String = \"\" }}");
                viewInitArgs.Add($"{param.Name}: {param.Name}String");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.BoundType)
            {
                // Optional<BoundType>: nullable pointer — reconstruct if non-nil
                var inner = param.InnerParameter!;
                sb.AppendLine($"        let {param.Name}Val: {inner.BridgeTypeName}? = {param.Name}Ptr.map {{ Unmanaged<{inner.BridgeTypeName}>.fromOpaque($0).takeUnretainedValue() }}");
                viewInitArgs.Add($"{param.Name}: {param.Name}Val");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped)
            {
                var inner = param.InnerParameter!;
                string valueExpr;
                if (inner.Kind == BridgeParameterKind.BoundEnum)
                    valueExpr = $"{inner.BridgeTypeName}(rawValue: {param.Name}Value)!";
                else if (inner.SwiftConversion != null)
                    valueExpr = $"{param.Name}Value {inner.SwiftConversion}";
                else
                    valueExpr = $"{param.Name}Value";
                viewInitArgs.Add($"{param.Name}: {param.Name}HasValue != 0 ? {valueExpr} : nil");
            }
            else if (param.Kind == BridgeParameterKind.Primitive && param.SwiftConversion != null)
            {
                // Bool: Int32 != 0
                viewInitArgs.Add($"{param.Name}: {param.Name} {param.SwiftConversion}");
            }
            else
            {
                viewInitArgs.Add($"{param.Name}: {param.Name}");
            }
        }

        if (viewInitArgs.Count == 0)
        {
            sb.AppendLine($"        let view = {info.ViewName}()");
        }
        else
        {
            sb.AppendLine($"        let view = {info.ViewName}({string.Join(", ", viewInitArgs)})");
        }
        sb.AppendLine($"        self.hostingController = UIHostingController(rootView: view)");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Handle tracking
        sb.AppendLine($"var {handlesVar} = Set<UnsafeMutableRawPointer>()");
        sb.AppendLine();

        // Create function
        sb.AppendLine($"@_cdecl(\"{prefix}_Create\")");
        sb.Append($"public func {prefix}_Create(");
        var createParams = new List<string>();
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                createParams.Add($"_ {param.Name}Callback: {param.SwiftAbiType}");
                createParams.Add($"_ {param.Name}UserData: UnsafeMutableRawPointer?");
            }
            else if (param.Kind == BridgeParameterKind.String)
            {
                createParams.Add($"_ {param.Name}Ptr: UnsafePointer<UInt8>?");
                createParams.Add($"_ {param.Name}Len: Int");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String)
            {
                createParams.Add($"_ {param.Name}Ptr: UnsafePointer<UInt8>?");
                createParams.Add($"_ {param.Name}Len: Int");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.BoundType)
            {
                createParams.Add($"_ {param.Name}Ptr: {param.SwiftAbiType}");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped)
            {
                createParams.Add($"_ {param.Name}HasValue: Int32");
                createParams.Add($"_ {param.Name}Value: {param.InnerParameter!.SwiftAbiType}");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                createParams.Add($"_ {param.Name}Ptr: {param.SwiftAbiType}");
            }
            else
            {
                createParams.Add($"_ {param.Name}: {param.SwiftAbiType}");
            }
        }
        sb.AppendLine(string.Join(",\n    ", createParams));
        sb.AppendLine(") -> UnsafeMutableRawPointer? {");
        sb.AppendLine("    return SBW_onMainThread {");

        // Build session init call
        var sessionArgs = new List<string>();
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                sessionArgs.Add($"{param.Name}Callback: {param.Name}Callback");
                sessionArgs.Add($"{param.Name}UserData: {param.Name}UserData");
            }
            else if (param.Kind == BridgeParameterKind.String)
            {
                sessionArgs.Add($"{param.Name}Ptr: {param.Name}Ptr");
                sessionArgs.Add($"{param.Name}Len: {param.Name}Len");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String)
            {
                sessionArgs.Add($"{param.Name}Ptr: {param.Name}Ptr");
                sessionArgs.Add($"{param.Name}Len: {param.Name}Len");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.BoundType)
            {
                sessionArgs.Add($"{param.Name}Ptr: {param.Name}Ptr");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped)
            {
                sessionArgs.Add($"{param.Name}HasValue: {param.Name}HasValue");
                sessionArgs.Add($"{param.Name}Value: {param.Name}Value");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                sessionArgs.Add($"{param.Name}Ptr: {param.Name}Ptr");
            }
            else
            {
                sessionArgs.Add($"{param.Name}: {param.Name}");
            }
        }

        sb.AppendLine($"        let session = {sessionClass}(");
        sb.AppendLine($"            {string.Join(",\n            ", sessionArgs)})");
        sb.AppendLine($"        let handle = Unmanaged.passRetained(session).toOpaque()");
        sb.AppendLine($"        {handlesVar}.insert(handle)");
        sb.AppendLine($"        return handle");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // GetViewController function
        sb.AppendLine($"@_cdecl(\"{prefix}_GetViewController\")");
        sb.AppendLine($"public func {prefix}_GetViewController(");
        sb.AppendLine($"    _ handle: UnsafeMutableRawPointer?");
        sb.AppendLine(") -> UnsafeMutableRawPointer? {");
        sb.AppendLine("    return SBW_onMainThread {");
        sb.AppendLine($"        guard let handle = handle,");
        sb.AppendLine($"              {handlesVar}.contains(handle) else {{ return nil }}");
        sb.AppendLine($"        let session = Unmanaged<{sessionClass}>");
        sb.AppendLine($"            .fromOpaque(handle).takeUnretainedValue()");
        sb.AppendLine($"        return Unmanaged.passUnretained(session.hostingController).toOpaque()");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Free function
        sb.AppendLine($"@_cdecl(\"{prefix}_Free\")");
        sb.AppendLine($"public func {prefix}_Free(_ handle: UnsafeMutableRawPointer?) {{");
        sb.AppendLine("    SBW_onMainThread {");
        sb.AppendLine($"        guard let handle = handle,");
        sb.AppendLine($"              {handlesVar}.remove(handle) != nil else {{ return }}");
        sb.AppendLine($"        Unmanaged<{sessionClass}>.fromOpaque(handle).release()");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitSwiftTemplate(StringBuilder sb, string moduleName, ViewBridgeInfo info)
    {
        sb.AppendLine($"// ========================================");
        sb.AppendLine($"// BRIDGE TEMPLATE: {info.ViewName}");
        sb.AppendLine($"// ========================================");

        var initDesc = GetInitDescription(info);
        sb.AppendLine($"// Init: {initDesc}");
        sb.AppendLine($"// Classification: {info.Classification}");
        if (info.UnsupportedReason != null)
            sb.AppendLine($"// Unsupported reason: {info.UnsupportedReason}");
        sb.AppendLine($"// Status: Template — complete the TODO sections");
        sb.AppendLine($"//");
        sb.AppendLine($"// @_cdecl(\"SBW_{moduleName}_{info.ViewName}_Create\")");
        sb.AppendLine($"// @_cdecl(\"SBW_{moduleName}_{info.ViewName}_GetViewController\")");
        sb.AppendLine($"// @_cdecl(\"SBW_{moduleName}_{info.ViewName}_Free\")");
        sb.AppendLine($"//");
        sb.AppendLine($"// See: src/docs/swiftui-bridge-design.md");
        sb.AppendLine();
    }

    #endregion

    #region C# Generation

    private static string GenerateCSharpBridge(
        string @namespace,
        string moduleName,
        List<(ViewBridgeInfo Info, List<BridgeParameter>? Params, AsyncViewPattern? AsyncPattern, bool IsFunctional)> bridgeResults)
    {
        var sb = new StringBuilder();
        bool hasFunctionalBridge = bridgeResults.Any(r => r.IsFunctional);

        if (hasFunctionalBridge)
        {
            sb.AppendLine("// Auto-generated by SwiftBindings — SwiftUI Bridge");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Threading.Tasks;");

            // Add Swift.Runtime.InteropServices when class closure args need SwiftMarshal
            bool hasClassClosureArgs = bridgeResults.Any(r => r.IsFunctional && r.Params != null &&
                r.Params.Any(p => p.Kind == BridgeParameterKind.TypedClosure &&
                    p.ClosureArguments != null &&
                    p.ClosureArguments.Any(a => a.Kind == BridgeParameterKind.BoundType)));
            if (hasClassClosureArgs)
                sb.AppendLine("using Swift.Runtime.InteropServices;");
            sb.AppendLine();
            sb.AppendLine($"namespace {@namespace}");
            sb.AppendLine("{");

            foreach (var (info, bridgeParams, asyncPattern, isFunctional) in bridgeResults)
            {
                if (isFunctional && asyncPattern != null)
                {
                    EmitAsyncCSharpBridge(sb, moduleName, info, asyncPattern);
                }
                else if (isFunctional)
                {
                    EmitFunctionalCSharpBridge(sb, moduleName, info, bridgeParams!);
                }
                else
                {
                    EmitCSharpTemplate(sb, info);
                }
            }

            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("// Auto-generated by SwiftBindings — SwiftUI Bridge Templates");
            sb.AppendLine("// These templates require manual completion before use.");
            sb.AppendLine("//");
            sb.AppendLine("// Views detected:");
            foreach (var (info, _, _, _) in bridgeResults)
            {
                var paramSummary = GetInitParamSummary(info);
                sb.AppendLine($"//   - {info.ViewName} ({info.Classification}: {paramSummary})");
            }
            sb.AppendLine("//");
            sb.AppendLine("// See: src/docs/swiftui-bridge-design.md");
        }

        sb.AppendLine();

        return sb.ToString();
    }

    private static void EmitFunctionalCSharpBridge(
        StringBuilder sb, string moduleName, ViewBridgeInfo info, List<BridgeParameter> bridgeParams)
    {
        var prefix = $"SBW_{moduleName}_{info.ViewName}";
        var bridgeLib = $"{moduleName}Bridge";
        var hasClosures = bridgeParams.Any(p => p.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure);
        var hasStrings = bridgeParams.Any(p => p.Kind == BridgeParameterKind.String ||
            (p.Kind == BridgeParameterKind.OptionalWrapped && p.InnerParameter?.Kind == BridgeParameterKind.String));
        var needsUnsafe = hasClosures || hasStrings;

        // NativeMethods class
        sb.AppendLine($"    internal static partial class {info.ViewName}BridgeNativeMethods");
        sb.AppendLine("    {");
        sb.AppendLine($"        private const string BridgeLib = \"{bridgeLib}\";");
        sb.AppendLine();

        // Create P/Invoke — build params first
        var createPInvokeParams = new List<string>();
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                createPInvokeParams.Add($"IntPtr {param.Name}Callback");
                createPInvokeParams.Add($"IntPtr {param.Name}UserData");
            }
            else if (param.Kind == BridgeParameterKind.String)
            {
                createPInvokeParams.Add($"IntPtr {param.Name}Ptr");
                createPInvokeParams.Add($"nint {param.Name}Len");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String)
            {
                createPInvokeParams.Add($"IntPtr {param.Name}Ptr");
                createPInvokeParams.Add($"nint {param.Name}Len");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.BoundType)
            {
                createPInvokeParams.Add($"IntPtr {param.Name}");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped)
            {
                createPInvokeParams.Add($"int {param.Name}HasValue");
                createPInvokeParams.Add($"{param.InnerParameter!.CSharpPInvokeType} {param.Name}Value");
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                createPInvokeParams.Add($"IntPtr {param.Name}");
            }
            else
            {
                createPInvokeParams.Add($"{param.CSharpPInvokeType} {param.Name}");
            }
        }
        foreach (var line in PInvokeEmitHelper.FormatDeclarationLines(new PInvokeEmissionInfo
        {
            LibraryPath = bridgeLib,
            EntryPoint = $"{prefix}_Create",
            MethodName = "Create",
            ReturnType = "IntPtr",
            ParametersString = string.Join(", ", createPInvokeParams),
            CallingConvention = PInvokeCallingConvention.Cdecl,
            Visibility = PInvokeVisibility.Internal
        }))
            sb.AppendLine($"        {line}");
        sb.AppendLine();

        // GetViewController P/Invoke
        foreach (var line in PInvokeEmitHelper.FormatDeclarationLines(new PInvokeEmissionInfo
        {
            LibraryPath = bridgeLib,
            EntryPoint = $"{prefix}_GetViewController",
            MethodName = "GetViewController",
            ReturnType = "IntPtr",
            ParametersString = "IntPtr handle",
            CallingConvention = PInvokeCallingConvention.Cdecl,
            Visibility = PInvokeVisibility.Internal
        }))
            sb.AppendLine($"        {line}");
        sb.AppendLine();

        // Free P/Invoke
        foreach (var line in PInvokeEmitHelper.FormatDeclarationLines(new PInvokeEmissionInfo
        {
            LibraryPath = bridgeLib,
            EntryPoint = $"{prefix}_Free",
            MethodName = "Free",
            ReturnType = "void",
            ParametersString = "IntPtr handle",
            CallingConvention = PInvokeCallingConvention.Cdecl,
            Visibility = PInvokeVisibility.Internal
        }))
            sb.AppendLine($"        {line}");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Session class
        sb.AppendLine($"    public sealed class {info.ViewName}Session : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private IntPtr _handle;");
        sb.AppendLine("        private bool _disposed;");
        if (hasClosures)
        {
            sb.AppendLine("        private GCHandle[] _closureHandles = Array.Empty<GCHandle>();");
        }
        sb.AppendLine();
        sb.AppendLine($"        internal {info.ViewName}Session(IntPtr handle) => _handle = handle;");
        sb.AppendLine();
        sb.AppendLine("        public IntPtr Handle => !_disposed");
        sb.AppendLine($"            ? _handle");
        sb.AppendLine($"            : throw new ObjectDisposedException(nameof({info.ViewName}Session));");
        sb.AppendLine();
        sb.AppendLine("        public IntPtr GetViewController() =>");
        sb.AppendLine($"            {info.ViewName}BridgeNativeMethods.GetViewController(Handle);");
        sb.AppendLine();

        // Trampolines for closure parameters
        foreach (var param in bridgeParams.Where(p => p.Kind == BridgeParameterKind.VoidClosure))
        {
            var trampolineName = char.ToUpperInvariant(param.Name[0]) + param.Name[1..] + "Trampoline";
            sb.AppendLine($"        [UnmanagedCallersOnly(CallConvs = new[] {{ typeof(CallConvCdecl) }})]");
            sb.AppendLine($"        private static void {trampolineName}(IntPtr userData)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (userData != IntPtr.Zero)");
            sb.AppendLine("            {");
            sb.AppendLine("                var h = GCHandle.FromIntPtr(userData);");
            sb.AppendLine("                if (h.Target is Action action)");
            sb.AppendLine("                    action();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Typed closure trampolines
        foreach (var param in bridgeParams.Where(p => p.Kind == BridgeParameterKind.TypedClosure))
        {
            EmitTypedClosureTrampoline(sb, param);
        }

        // Create factory method
        EmitSimpleCreateFactory(sb, info, bridgeParams, needsUnsafe, hasClosures, hasStrings);

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_disposed)");
        sb.AppendLine("            {");
        sb.AppendLine("                _disposed = true;");
        sb.AppendLine($"                {info.ViewName}BridgeNativeMethods.Free(_handle);");
        if (hasClosures)
        {
            sb.AppendLine("                foreach (var h in _closureHandles)");
            sb.AppendLine("                    if (h.IsAllocated) h.Free();");
            sb.AppendLine("                _closureHandles = Array.Empty<GCHandle>();");
        }
        sb.AppendLine("                _handle = IntPtr.Zero;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSimpleCreateFactory(
        StringBuilder sb, ViewBridgeInfo info, List<BridgeParameter> bridgeParams,
        bool needsUnsafe, bool hasClosures, bool hasStrings)
    {
        // Factory parameter list (idiomatic C# types)
        // C# requires optional parameters after all required parameters.
        var requiredParams = new List<string>();
        var optionalParams = new List<string>();
        foreach (var param in bridgeParams)
        {
            var type = GetFactoryParamType(param);
            var isOptionalString = param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String;
            var defaultVal = param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure ? " = null"
                : param.Kind == BridgeParameterKind.String ? " = null"
                : isOptionalString ? " = null" : "";
            if (defaultVal.Length > 0)
                optionalParams.Add($"{type} {param.Name}{defaultVal}");
            else
                requiredParams.Add($"{type} {param.Name}");
        }
        requiredParams.AddRange(optionalParams);

        var unsafeKeyword = needsUnsafe ? "unsafe " : "";
        sb.AppendLine($"        public static {unsafeKeyword}{info.ViewName}Session Create({string.Join(", ", requiredParams)})");
        sb.AppendLine("        {");

        if (hasClosures)
        {
            sb.AppendLine("            var closureHandles = new System.Collections.Generic.List<GCHandle>();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            var indent = "                ";

            // Setup closure parameters
            foreach (var param in bridgeParams.Where(p => p.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure))
            {
                var trampolineName = char.ToUpperInvariant(param.Name[0]) + param.Name[1..] + "Trampoline";
                sb.AppendLine($"{indent}IntPtr {param.Name}Callback = IntPtr.Zero;");
                sb.AppendLine($"{indent}IntPtr {param.Name}UserData = IntPtr.Zero;");
                sb.AppendLine($"{indent}if ({param.Name} != null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var h = GCHandle.Alloc({param.Name});");
                sb.AppendLine($"{indent}    closureHandles.Add(h);");
                sb.AppendLine($"{indent}    {param.Name}UserData = GCHandle.ToIntPtr(h);");

                // Build delegate* type matching trampoline signature
                var fnPtrType = GetClosureFunctionPointerType(param);
                sb.AppendLine($"{indent}    {fnPtrType} fn = &{trampolineName};");
                sb.AppendLine($"{indent}    {param.Name}Callback = (IntPtr)fn;");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }

            // String encoding (includes Optional<String> params)
            foreach (var param in bridgeParams.Where(p => p.Kind == BridgeParameterKind.String))
            {
                sb.AppendLine($"{indent}var {param.Name}Bytes = Encoding.UTF8.GetBytes({param.Name} ?? \"\");");
            }
            foreach (var param in bridgeParams.Where(p => p.Kind == BridgeParameterKind.OptionalWrapped && p.InnerParameter?.Kind == BridgeParameterKind.String))
            {
                sb.AppendLine($"{indent}byte[]? {param.Name}Bytes = {param.Name} != null ? Encoding.UTF8.GetBytes({param.Name}) : null;");
            }

            // Call with fixed block if strings
            EmitSimpleCreateCall(sb, info, bridgeParams, hasStrings, hasClosures, indent);

            sb.AppendLine("            }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (var h in closureHandles)");
            sb.AppendLine("                    if (h.IsAllocated) h.Free();");
            sb.AppendLine("            }");
        }
        else if (hasStrings)
        {
            var indent = "            ";
            // String encoding (includes Optional<String> params)
            foreach (var param in bridgeParams.Where(p => p.Kind == BridgeParameterKind.String))
            {
                sb.AppendLine($"{indent}var {param.Name}Bytes = Encoding.UTF8.GetBytes({param.Name} ?? \"\");");
            }
            foreach (var param in bridgeParams.Where(p => p.Kind == BridgeParameterKind.OptionalWrapped && p.InnerParameter?.Kind == BridgeParameterKind.String))
            {
                sb.AppendLine($"{indent}byte[]? {param.Name}Bytes = {param.Name} != null ? Encoding.UTF8.GetBytes({param.Name}) : null;");
            }
            EmitSimpleCreateCall(sb, info, bridgeParams, hasStrings, hasClosures, indent);
        }
        else
        {
            // Simple case: no closures, no strings
            var nativeArgs = BuildSimpleNativeCallArgs(bridgeParams);
            sb.AppendLine($"            var handle = {info.ViewName}BridgeNativeMethods.Create({string.Join(", ", nativeArgs)});");
            sb.AppendLine("            if (handle == IntPtr.Zero)");
            sb.AppendLine($"                throw new InvalidOperationException(\"Failed to create {info.ViewName} session.\");");
            sb.AppendLine($"            return new {info.ViewName}Session(handle);");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitSimpleCreateCall(
        StringBuilder sb, ViewBridgeInfo info, List<BridgeParameter> bridgeParams,
        bool hasStrings, bool hasClosures, string indent)
    {
        var stringParams = bridgeParams.Where(p => p.Kind == BridgeParameterKind.String ||
            (p.Kind == BridgeParameterKind.OptionalWrapped && p.InnerParameter?.Kind == BridgeParameterKind.String)).ToList();
        var nativeArgs = BuildSimpleNativeCallArgs(bridgeParams);

        if (hasStrings)
        {
            var fixedDecls = string.Join(", ", stringParams.Select(p => $"byte* {p.Name}Ptr = {p.Name}Bytes"));
            sb.AppendLine($"{indent}fixed ({fixedDecls})");
            sb.AppendLine($"{indent}{{");
            var innerIndent = indent + "    ";
            sb.AppendLine($"{innerIndent}var handle = {info.ViewName}BridgeNativeMethods.Create({string.Join(", ", nativeArgs)});");
            sb.AppendLine($"{innerIndent}if (handle == IntPtr.Zero)");
            sb.AppendLine($"{innerIndent}    throw new InvalidOperationException(\"Failed to create {info.ViewName} session.\");");
            if (hasClosures)
            {
                sb.AppendLine($"{innerIndent}var session = new {info.ViewName}Session(handle);");
                sb.AppendLine($"{innerIndent}session._closureHandles = closureHandles.ToArray();");
                sb.AppendLine($"{innerIndent}closureHandles.Clear();");
                sb.AppendLine($"{innerIndent}return session;");
            }
            else
            {
                sb.AppendLine($"{innerIndent}return new {info.ViewName}Session(handle);");
            }
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            sb.AppendLine($"{indent}var handle = {info.ViewName}BridgeNativeMethods.Create({string.Join(", ", nativeArgs)});");
            sb.AppendLine($"{indent}if (handle == IntPtr.Zero)");
            sb.AppendLine($"{indent}    throw new InvalidOperationException(\"Failed to create {info.ViewName} session.\");");
            if (hasClosures)
            {
                sb.AppendLine($"{indent}var session = new {info.ViewName}Session(handle);");
                sb.AppendLine($"{indent}session._closureHandles = closureHandles.ToArray();");
                sb.AppendLine($"{indent}closureHandles.Clear();");
                sb.AppendLine($"{indent}return session;");
            }
            else
            {
                sb.AppendLine($"{indent}return new {info.ViewName}Session(handle);");
            }
        }
    }

    private static List<string> BuildSimpleNativeCallArgs(List<BridgeParameter> bridgeParams)
    {
        var args = new List<string>();
        foreach (var param in bridgeParams)
        {
            if (param.Kind is BridgeParameterKind.VoidClosure or BridgeParameterKind.TypedClosure)
            {
                args.Add($"{param.Name}Callback");
                args.Add($"{param.Name}UserData");
            }
            else if (param.Kind == BridgeParameterKind.String)
            {
                args.Add($"(IntPtr){param.Name}Ptr");
                args.Add($"{param.Name}Bytes.Length");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.String)
            {
                args.Add($"{param.Name} == null ? IntPtr.Zero : (IntPtr){param.Name}Ptr");
                args.Add($"{param.Name}Bytes?.Length ?? 0");
            }
            else if (param.Kind == BridgeParameterKind.BoundEnum)
            {
                if (param.IsSimpleEnum)
                {
                    // Simple enums are C# enum value types — cast to underlying int
                    args.Add($"({param.CSharpPInvokeType}){param.Name}");
                }
                else
                {
                    // Complex enums are C# classes with .RawValue property
                    args.Add($"{param.Name}.RawValue");
                }
            }
            else if (param.Kind == BridgeParameterKind.BoundType)
            {
                args.Add($"{param.Name}.Payload.DangerousGetHandle()");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped && param.InnerParameter?.Kind == BridgeParameterKind.BoundType)
            {
                args.Add($"{param.Name}?.Payload.DangerousGetHandle() ?? IntPtr.Zero");
            }
            else if (param.Kind == BridgeParameterKind.OptionalWrapped)
            {
                var inner = param.InnerParameter!;
                if (inner.Kind == BridgeParameterKind.BoundEnum)
                {
                    if (inner.IsSimpleEnum)
                    {
                        // Simple enum is a C# value type — use .HasValue, cast to int
                        args.Add($"{param.Name}.HasValue ? 1 : 0");
                        args.Add($"{param.Name}.HasValue ? ({inner.CSharpPInvokeType}){param.Name}.Value : 0");
                    }
                    else
                    {
                        // Complex enum is a reference type (class) — use != null, .RawValue
                        args.Add($"{param.Name} != null ? 1 : 0");
                        args.Add($"{param.Name}?.RawValue ?? 0");
                    }
                }
                else if (inner.CSharpConversion != null) // Bool
                {
                    args.Add($"{param.Name}.HasValue ? 1 : 0");
                    args.Add($"{param.Name}.HasValue ? ({param.Name}.Value {inner.CSharpConversion}) : 0");
                }
                else
                {
                    args.Add($"{param.Name}.HasValue ? 1 : 0");
                    args.Add($"{param.Name} ?? 0");
                }
            }
            else if (param.CSharpConversion != null)
            {
                // Bool: value ? 1 : 0
                args.Add($"{param.Name} {param.CSharpConversion}");
            }
            else
            {
                args.Add(param.Name);
            }
        }
        return args;
    }

    private static string GetFactoryParamType(BridgeParameter param) => param.Kind switch
    {
        BridgeParameterKind.VoidClosure => "Action?",
        BridgeParameterKind.TypedClosure => GetTypedClosureFactoryType(param),
        BridgeParameterKind.String => "string?",
        BridgeParameterKind.Primitive when param.CSharpConversion != null => "bool",
        BridgeParameterKind.BoundEnum => param.CSharpTypeName!,
        BridgeParameterKind.BoundType => param.CSharpTypeName!,
        BridgeParameterKind.OptionalWrapped => GetOptionalFactoryType(param),
        _ => param.CSharpPInvokeType,
    };

    private static string GetOptionalFactoryType(BridgeParameter param)
    {
        var inner = param.InnerParameter!;
        if (inner.Kind == BridgeParameterKind.String)
            return "string?";
        if (inner.Kind == BridgeParameterKind.BoundEnum)
            return $"{inner.CSharpTypeName}?";
        if (inner.Kind == BridgeParameterKind.BoundType)
            return $"{inner.CSharpTypeName}?";
        if (inner.CSharpConversion != null) // Bool
            return "bool?";
        return $"{inner.CSharpPInvokeType}?";
    }

    private static void EmitCSharpTemplate(StringBuilder sb, ViewBridgeInfo info)
    {
        var paramSummary = GetInitParamSummary(info);
        sb.AppendLine($"    // BRIDGE TEMPLATE: {info.ViewName} ({info.Classification}: {paramSummary})");
        sb.AppendLine($"    // See: src/docs/swiftui-bridge-design.md");
        sb.AppendLine();
    }

    #endregion

    #region Helpers

    /// <summary>
    /// Builds the Swift closure expression for a typed closure view init argument.
    /// Generates: paramName: { (arg0: SwiftType, ...) [-> ReturnType] in callbackExpr }
    /// </summary>
    private static string BuildTypedClosureViewInitArg(BridgeParameter param)
    {
        var closureArgs = param.ClosureArguments!;
        var closureReturn = param.ClosureReturn;

        // Build closure parameter declarations: (arg0: Int, arg1: Bool, arg2: String)
        var swiftArgDecls = closureArgs.Select((a, i) =>
            $"arg{i}: {GetSwiftTypeFromAbi(a)}").ToList();
        var argDeclStr = string.Join(", ", swiftArgDecls);

        // Check if we have String or class args that need special encoding
        var hasStringArgs = closureArgs.Any(a => a.Kind == BridgeParameterKind.String);
        var hasClassArgs = closureArgs.Any(a => a.Kind == BridgeParameterKind.BoundType);

        if (hasStringArgs || hasClassArgs)
        {
            return BuildComplexClosureViewInitArg(param, closureArgs, closureReturn, argDeclStr);
        }

        // Build callback invocation args: convert Swift types to ABI types
        var callbackArgs = closureArgs.Select((a, i) =>
            a.CSharpConversion != null ? $"arg{i} {a.CSharpConversion}" : $"arg{i}").ToList();
        callbackArgs.Add($"ud_{param.Name}");
        var callbackArgStr = string.Join(", ", callbackArgs);

        if (closureReturn == null)
        {
            // (args...) -> Void
            return $"{param.Name}: {{ ({argDeclStr}) in\n" +
                   $"            cb_{param.Name}?({callbackArgStr})\n" +
                   $"        }}";
        }
        else
        {
            // (args...) -> ReturnType
            var swiftReturnType = GetSwiftTypeFromAbi(closureReturn);
            var defaultVal = closureReturn.SwiftAbiType is "Double" or "Float" ? "0.0" : "0";
            var callExpr = $"cb_{param.Name}?({callbackArgStr}) ?? {defaultVal}";

            if (closureReturn.SwiftConversion != null)
                callExpr = $"({callExpr}) {closureReturn.SwiftConversion}";

            return $"{param.Name}: {{ ({argDeclStr}) -> {swiftReturnType} in\n" +
                   $"            {callExpr}\n" +
                   $"        }}";
        }
    }

    /// <summary>
    /// Builds Swift closure body for closures with String or class arguments.
    /// String args are UTF-8 encoded via withUnsafeBufferPointer.
    /// Class args are passed as opaque pointers via Unmanaged.passRetained.
    /// </summary>
    private static string BuildComplexClosureViewInitArg(
        BridgeParameter param, List<BridgeParameter> closureArgs,
        BridgeParameter? closureReturn, string argDeclStr)
    {
        var sb = new StringBuilder();
        var hasReturn = closureReturn != null;

        // Closure signature: with or without return type annotation
        if (hasReturn)
        {
            var swiftReturnType = GetSwiftTypeFromAbi(closureReturn!);
            sb.Append($"{param.Name}: {{ ({argDeclStr}) -> {swiftReturnType} in\n");
        }
        else
        {
            sb.Append($"{param.Name}: {{ ({argDeclStr}) in\n");
        }

        // Collect String args that need withUnsafeBufferPointer nesting
        var stringArgIndices = new List<int>();
        for (int i = 0; i < closureArgs.Count; i++)
        {
            if (closureArgs[i].Kind == BridgeParameterKind.String)
            {
                sb.Append($"            let arg{i}Bytes = Array(arg{i}.utf8)\n");
                stringArgIndices.Add(i);
            }
        }

        // Open nested withUnsafeBufferPointer blocks for each String arg
        // When the closure has a non-void return, each withUnsafeBufferPointer call must
        // be preceded by `return` so the typed result propagates through all nesting levels.
        var baseIndent = "            ";
        var currentIndent = baseIndent;
        for (int s = 0; s < stringArgIndices.Count; s++)
        {
            var si = stringArgIndices[s];
            var returnPrefix = hasReturn ? "return " : "";
            sb.Append($"{currentIndent}{returnPrefix}arg{si}Bytes.withUnsafeBufferPointer {{ buf{si} in\n");
            currentIndent += "    ";
        }

        // Build callback args: String→(baseAddress, count), Class→Unmanaged, Primitive→direct
        var callbackArgs = new List<string>();
        for (int i = 0; i < closureArgs.Count; i++)
        {
            var a = closureArgs[i];
            if (a.Kind == BridgeParameterKind.String)
            {
                callbackArgs.Add($"buf{i}.baseAddress");
                callbackArgs.Add($"Int(buf{i}.count)");
            }
            else if (a.Kind == BridgeParameterKind.BoundType)
            {
                callbackArgs.Add($"Unmanaged.passRetained(arg{i}).toOpaque()");
            }
            else if (a.CSharpConversion != null)
            {
                callbackArgs.Add($"arg{i} {a.CSharpConversion}");
            }
            else
            {
                callbackArgs.Add($"arg{i}");
            }
        }
        callbackArgs.Add($"ud_{param.Name}");
        var callbackArgStr = string.Join(", ", callbackArgs);

        if (hasReturn)
        {
            // Non-void return: default value + optional chaining + conversion
            var defaultVal = closureReturn!.SwiftAbiType is "Double" or "Float" ? "0.0" : "0";
            var callExpr = $"cb_{param.Name}?({callbackArgStr}) ?? {defaultVal}";
            if (closureReturn.SwiftConversion != null)
                callExpr = $"({callExpr}) {closureReturn.SwiftConversion}";

            // String args require `return` keyword inside withUnsafeBufferPointer blocks
            if (stringArgIndices.Count > 0)
                sb.Append($"{currentIndent}return {callExpr}\n");
            else
                sb.Append($"{currentIndent}{callExpr}\n");
        }
        else
        {
            sb.Append($"{currentIndent}cb_{param.Name}?({callbackArgStr})\n");
        }

        // Close nested withUnsafeBufferPointer blocks — inner blocks need `return` propagation
        for (int s = stringArgIndices.Count - 1; s >= 0; s--)
        {
            currentIndent = baseIndent + new string(' ', 4 * s);
            sb.Append($"{currentIndent}}}\n");
        }

        sb.Append($"        }}");
        return sb.ToString();
    }

    /// <summary>
    /// Maps an ABI BridgeParameter back to its Swift type name for closure signatures.
    /// e.g., Int32 with SwiftConversion "!= 0" → Bool; Int → Int; Double → Double
    /// </summary>
    private static string GetSwiftTypeFromAbi(BridgeParameter param)
    {
        if (param.SwiftConversion == "!= 0") return "Bool";
        if (param.Kind == BridgeParameterKind.String) return "String";
        if (param.Kind == BridgeParameterKind.BoundType) return param.BridgeTypeName!;
        return param.SwiftAbiType;
    }

    /// <summary>
    /// Emits a typed closure [UnmanagedCallersOnly] trampoline that unpacks GCHandle → delegate,
    /// converts ABI args to C# types, calls the delegate, and converts the return value back.
    /// </summary>
    private static void EmitTypedClosureTrampoline(StringBuilder sb, BridgeParameter param)
    {
        var trampolineName = char.ToUpperInvariant(param.Name[0]) + param.Name[1..] + "Trampoline";
        var closureArgs = param.ClosureArguments!;
        var closureReturn = param.ClosureReturn;

        // Build trampoline parameters: String args expand to (IntPtr ptr, nint len)
        var trampolineParams = new List<string>();
        foreach (var (a, i) in closureArgs.Select((a, i) => (a, i)))
        {
            if (a.Kind == BridgeParameterKind.String)
            {
                trampolineParams.Add($"IntPtr arg{i}Ptr");
                trampolineParams.Add($"nint arg{i}Len");
            }
            else
            {
                trampolineParams.Add($"{a.CSharpPInvokeType} arg{i}");
            }
        }
        trampolineParams.Add("IntPtr userData");
        var returnType = closureReturn?.CSharpPInvokeType ?? "void";

        sb.AppendLine($"        [UnmanagedCallersOnly(CallConvs = new[] {{ typeof(CallConvCdecl) }})]");
        sb.AppendLine($"        private static {returnType} {trampolineName}({string.Join(", ", trampolineParams)})");
        sb.AppendLine("        {");
        sb.AppendLine("            if (userData != IntPtr.Zero)");
        sb.AppendLine("            {");
        sb.AppendLine("                var h = GCHandle.FromIntPtr(userData);");

        // Build C# delegate type for the cast
        var delegateType = GetCSharpDelegateType(closureArgs, closureReturn);

        var hasStringOrClassArgs = closureArgs.Any(a => a.Kind is BridgeParameterKind.String or BridgeParameterKind.BoundType);

        if (hasStringOrClassArgs)
        {
            // String/class args need decoding before delegate invocation
            foreach (var (a, i) in closureArgs.Select((a, i) => (a, i)))
            {
                if (a.Kind == BridgeParameterKind.String)
                {
                    sb.AppendLine($"                var str{i} = \"\";");
                    sb.AppendLine($"                if (arg{i}Ptr != IntPtr.Zero && arg{i}Len > 0)");
                    sb.AppendLine($"                    unsafe {{ str{i} = Encoding.UTF8.GetString((byte*)arg{i}Ptr, (int)arg{i}Len); }}");
                }
                else if (a.Kind == BridgeParameterKind.BoundType)
                {
                    sb.AppendLine($"                {a.CSharpTypeName} arg{i}Obj;");
                    sb.AppendLine($"                unsafe");
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    var classPayload{i} = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)sizeof(IntPtr));");
                    sb.AppendLine($"                    *(IntPtr*)classPayload{i} = arg{i};");
                    sb.AppendLine($"                    try");
                    sb.AppendLine($"                    {{");
                    sb.AppendLine($"                        arg{i}Obj = ({a.CSharpTypeName})Swift.Runtime.InteropServices.SwiftMarshal.MarshalFromSwift<{a.CSharpTypeName}>(new IntPtr(classPayload{i}));");
                    sb.AppendLine($"                    }}");
                    sb.AppendLine($"                    catch");
                    sb.AppendLine($"                    {{");
                    sb.AppendLine($"                        global::System.Runtime.InteropServices.NativeMemory.Free(classPayload{i});");
                    sb.AppendLine($"                        throw;");
                    sb.AppendLine($"                    }}");
                    sb.AppendLine($"                }}");
                }
            }

            // Build delegate args using decoded values
            var delegateArgs = new List<string>();
            for (int i = 0; i < closureArgs.Count; i++)
            {
                var a = closureArgs[i];
                if (a.Kind == BridgeParameterKind.String)
                    delegateArgs.Add($"str{i}");
                else if (a.Kind == BridgeParameterKind.BoundType)
                    delegateArgs.Add($"arg{i}Obj");
                else if (a.SwiftConversion != null)
                    delegateArgs.Add($"arg{i} {a.SwiftConversion}");
                else
                    delegateArgs.Add($"arg{i}");
            }
            var delegateArgStr = string.Join(", ", delegateArgs);

            if (closureReturn == null)
            {
                sb.AppendLine($"                if (h.Target is {delegateType} action)");
                sb.AppendLine($"                    action({delegateArgStr});");
            }
            else
            {
                sb.AppendLine($"                if (h.Target is {delegateType} func)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var result = func({delegateArgStr});");
                if (closureReturn.CSharpConversion != null)
                    sb.AppendLine($"                    return result {closureReturn.CSharpConversion};");
                else
                    sb.AppendLine($"                    return result;");
                sb.AppendLine("                }");
            }
        }
        else
        {
            // Simple primitive args — direct pass
            var delegateArgs = closureArgs.Select((a, i) =>
                a.SwiftConversion != null ? $"arg{i} {a.SwiftConversion}" : $"arg{i}").ToList();
            var delegateArgStr = string.Join(", ", delegateArgs);

            if (closureReturn == null)
            {
                sb.AppendLine($"                if (h.Target is {delegateType} action)");
                sb.AppendLine($"                    action({delegateArgStr});");
            }
            else
            {
                sb.AppendLine($"                if (h.Target is {delegateType} func)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var result = func({delegateArgStr});");
                if (closureReturn.CSharpConversion != null)
                    sb.AppendLine($"                    return result {closureReturn.CSharpConversion};");
                else
                    sb.AppendLine($"                    return result;");
                sb.AppendLine("                }");
            }
        }

        sb.AppendLine("            }");
        if (closureReturn != null)
            sb.AppendLine("            return 0;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Gets the C# delegate type for a typed closure (e.g., Action&lt;nint, bool&gt; or Func&lt;nint, bool&gt;).
    /// </summary>
    private static string GetCSharpDelegateType(List<BridgeParameter> closureArgs, BridgeParameter? closureReturn)
    {
        var argTypes = closureArgs.Select(GetClosureArgCSharpType).ToList();

        if (closureReturn == null)
        {
            return argTypes.Count == 0 ? "Action" : $"Action<{string.Join(", ", argTypes)}>";
        }
        else
        {
            var returnType = GetFactoryParamType(closureReturn);
            argTypes.Add(returnType);
            return $"Func<{string.Join(", ", argTypes)}>";
        }
    }

    /// <summary>
    /// Gets the idiomatic C# type for a closure argument used in delegate types.
    /// String → "string", BoundType → fully-qualified class name, others → same as factory param.
    /// </summary>
    private static string GetClosureArgCSharpType(BridgeParameter param) => param.Kind switch
    {
        BridgeParameterKind.String => "string",
        BridgeParameterKind.BoundType => param.CSharpTypeName!,
        _ => GetFactoryParamType(param),
    };

    /// <summary>
    /// Gets the C# factory parameter type for a typed closure (e.g., Action&lt;nint&gt;? or Func&lt;nint, bool&gt;?).
    /// </summary>
    private static string GetTypedClosureFactoryType(BridgeParameter param)
    {
        var closureArgs = param.ClosureArguments!;
        var closureReturn = param.ClosureReturn;
        return GetCSharpDelegateType(closureArgs, closureReturn) + "?";
    }

    /// <summary>
    /// Gets the delegate* unmanaged function pointer type for a closure parameter.
    /// VoidClosure: delegate* unmanaged[Cdecl]&lt;IntPtr, void&gt;
    /// TypedClosure: delegate* unmanaged[Cdecl]&lt;argTypes..., IntPtr, returnType&gt;
    /// </summary>
    private static string GetClosureFunctionPointerType(BridgeParameter param)
    {
        if (param.Kind == BridgeParameterKind.VoidClosure)
            return "delegate* unmanaged[Cdecl]<IntPtr, void>";

        var closureArgs = param.ClosureArguments!;
        var closureReturn = param.ClosureReturn;
        var fnPtrTypes = new List<string>();
        foreach (var a in closureArgs)
        {
            if (a.Kind == BridgeParameterKind.String)
            {
                fnPtrTypes.Add("IntPtr"); // ptr
                fnPtrTypes.Add("nint");   // len
            }
            else
            {
                fnPtrTypes.Add(a.CSharpPInvokeType);
            }
        }
        fnPtrTypes.Add("IntPtr"); // userData
        fnPtrTypes.Add(closureReturn?.CSharpPInvokeType ?? "void"); // return type
        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", fnPtrTypes)}>";
    }

    private static string GetInitDescription(ViewBridgeInfo info)
    {
        if (info.Constructors.Count == 0)
            return "init()";

        var ctor = info.Constructors[0];
        var paramDescs = new List<string>();
        for (int i = 1; i < ctor.CSSignature.Count; i++)
        {
            var param = ctor.CSSignature[i];
            paramDescs.Add($"{param.Name}: {param.SwiftTypeSpec}");
        }

        return paramDescs.Count == 0 ? "init()" : $"init({string.Join(", ", paramDescs)})";
    }

    private static string GetInitParamSummary(ViewBridgeInfo info)
    {
        if (info.UnsupportedReason != null)
            return info.UnsupportedReason;

        if (info.Constructors.Count == 0)
            return "no parameters";

        var ctor = info.Constructors[0];
        var paramDescs = new List<string>();
        for (int i = 1; i < ctor.CSSignature.Count; i++)
        {
            var param = ctor.CSSignature[i];
            paramDescs.Add($"{param.Name}: {param.SwiftTypeSpec}");
        }

        return paramDescs.Count == 0 ? "no parameters" : string.Join(", ", paramDescs);
    }

    #endregion
}

/// <summary>
/// Classification of a View's init for bridge generation.
/// </summary>
public enum ViewInitClassification
{
    Simple,
    AsyncDependency,
    Unsupported,
    /// <summary>Bridge hints say skip this view entirely — no bridge output generated.</summary>
    Skipped,
}

/// <summary>
/// Information about a detected SwiftUI View for bridge generation.
/// </summary>
public record ViewBridgeInfo(
    string ViewName,
    string ModuleName,
    ViewInitClassification Classification,
    string? UnsupportedReason,
    List<MethodDecl> Constructors,
    AsyncViewPattern? InferredPattern = null);
