// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;
using Microsoft.Extensions.Logging;

namespace BindingsGeneration;

/// <summary>
/// Detects theme-bridgeable types (classes with singleton + settable Color/Font properties)
/// and emits @_cdecl setter wrappers (Swift) + static setter methods (C#).
/// </summary>
public static class ThemeBridgeEmitter
{
    private const string AutoGeneratedMarker = "// Auto-generated by SwiftBindings";

    /// <summary>
    /// Singleton accessor names recognized as theme singletons.
    /// </summary>
    private static readonly HashSet<string> SingletonPropertyNames = new(StringComparer.Ordinal)
    {
        "shared", "default", "current", "sharedInstance", "instance"
    };

    /// <summary>
    /// Swift keywords that need backtick escaping when used as identifiers.
    /// </summary>
    private static readonly HashSet<string> SwiftKeywords = new(StringComparer.Ordinal)
    {
        "default", "class", "struct", "enum", "protocol", "extension",
        "func", "var", "let", "import", "return", "if", "else", "for",
        "while", "switch", "case", "break", "continue", "in", "where",
        "true", "false", "nil", "self", "super", "init", "deinit",
        "subscript", "operator", "typealias", "associatedtype", "is", "as",
        "try", "catch", "throw", "throws", "rethrows", "do", "repeat",
        "guard", "defer", "static", "public", "private", "internal",
        "fileprivate", "open", "final", "override", "mutating", "inout",
        "lazy", "weak", "unowned", "convenience", "required", "dynamic",
    };

    /// <summary>
    /// A settable property on a theme class that can be bridged.
    /// </summary>
    public record ThemeProperty(string Name, ThemePropertyKind Kind);

    /// <summary>
    /// The kind of theme property (determines ABI shape).
    /// </summary>
    public enum ThemePropertyKind
    {
        Color,
        Font,
    }

    /// <summary>
    /// A detected theme-bridgeable type.
    /// </summary>
    public record ThemeBridgeInfo(
        string ClassName,
        string ModuleName,
        string SingletonName,
        List<ThemeProperty> Properties);

    /// <summary>
    /// Detects theme-bridgeable types from the module's classes.
    /// A class qualifies if it: (1) is concrete, (2) has a static singleton property,
    /// (3) has at least one settable SwiftUI.Color or SwiftUI.Font instance property.
    /// </summary>
    public static List<ThemeBridgeInfo> DetectThemeBridgeableTypes(ModuleDecl moduleDecl)
    {
        var results = new List<ThemeBridgeInfo>();
        foreach (var typeDecl in moduleDecl.Types)
        {
            if (typeDecl is ClassDecl classDecl)
            {
                var info = AnalyzeClassForThemeBridge(classDecl, moduleDecl.Name);
                if (info != null)
                    results.Add(info);
            }
        }
        return results;
    }

    /// <summary>
    /// Analyzes a single class for theme bridge eligibility.
    /// Returns null if the class doesn't qualify.
    /// </summary>
    public static ThemeBridgeInfo? AnalyzeClassForThemeBridge(ClassDecl classDecl, string moduleName)
    {
        // 1. Find singleton property
        var singletonName = FindSingletonProperty(classDecl);
        if (singletonName == null)
            return null;

        // 2. Find settable Color/Font instance properties
        var themeProperties = new List<ThemeProperty>();
        foreach (var property in classDecl.Properties)
        {
            if (property.IsStatic)
                continue;

            // Must have a setter
            if (!property.Accessors.Any(a => a is SetAccessorDecl))
                continue;

            var kind = ClassifyPropertyType(property.SwiftTypeSpec);
            if (kind != null)
                themeProperties.Add(new ThemeProperty(property.Name, kind.Value));
        }

        if (themeProperties.Count == 0)
            return null;

        return new ThemeBridgeInfo(classDecl.Name, moduleName, singletonName, themeProperties);
    }

    /// <summary>
    /// Finds the singleton property name on a class, or null if none found.
    /// </summary>
    internal static string? FindSingletonProperty(ClassDecl classDecl)
    {
        foreach (var property in classDecl.Properties)
        {
            if (!property.IsStatic)
                continue;

            if (!SingletonPropertyNames.Contains(property.Name))
                continue;

            // Type must be Self (the class itself)
            if (property.SwiftTypeSpec is NamedTypeSpec namedType &&
                namedType.Name.EndsWith(classDecl.Name))
            {
                return property.Name;
            }
        }
        return null;
    }

    /// <summary>
    /// Escapes a Swift keyword with backticks if needed (e.g., "default" → "`default`").
    /// Non-keyword identifiers are returned unchanged.
    /// </summary>
    internal static string EscapeSwiftKeyword(string name) =>
        SwiftKeywords.Contains(name) ? $"`{name}`" : name;

    /// <summary>
    /// Returns true if the file at path exists and starts with the auto-generated marker.
    /// Returns false if the file does not exist or is user-maintained.
    /// </summary>
    private static bool IsAutoGeneratedFile(string path)
    {
        if (!File.Exists(path))
            return false;

        try
        {
            using var reader = new StreamReader(path);
            var firstLine = reader.ReadLine();
            return firstLine != null && firstLine.StartsWith(AutoGeneratedMarker, StringComparison.Ordinal);
        }
        catch (IOException)
        {
            return false;
        }
    }

    /// <summary>
    /// Classifies a property type as Color or Font, or null if not bridgeable.
    /// </summary>
    internal static ThemePropertyKind? ClassifyPropertyType(TypeSpec typeSpec)
    {
        if (typeSpec is not NamedTypeSpec namedType)
            return null;

        var fullName = namedType.ToString();
        return fullName switch
        {
            "SwiftUI.Color" or "SwiftUICore.Color" => ThemePropertyKind.Color,
            "SwiftUI.Font" or "SwiftUICore.Font" => ThemePropertyKind.Font,
            _ => null,
        };
    }

    /// <summary>
    /// Emits theme bridge content into the bridge Swift and C# files.
    /// Called from ModuleEmitter after normal emission and view bridge emission.
    /// </summary>
    public static void EmitThemeBridge(
        string outputDirectory,
        string @namespace,
        string moduleName,
        List<ThemeBridgeInfo> themeInfos,
        bool viewBridgeExists,
        ILogger logger)
    {
        if (themeInfos.Count == 0)
            return;

        var hasFonts = themeInfos.Any(t => t.Properties.Any(p => p.Kind == ThemePropertyKind.Font));
        var swiftContent = GenerateSwiftThemeBridge(moduleName, themeInfos, viewBridgeExists, hasFonts);
        var csContent = GenerateCSharpThemeBridge(@namespace, moduleName, themeInfos);

        // Append to existing auto-generated bridge files, or create new standalone files.
        // Never modify user-maintained files (files without the auto-generated marker).
        var swiftPath = Path.Combine(outputDirectory, $"{@namespace}.SwiftUIBridge.swift");
        var csPath = Path.Combine(outputDirectory, $"{@namespace}.SwiftUIBridge.cs");

        if (File.Exists(swiftPath))
        {
            if (IsAutoGeneratedFile(swiftPath))
            {
                File.AppendAllText(swiftPath, swiftContent);
            }
            else
            {
                logger.LogWarning("Bridge file {Path} exists but was not auto-generated; skipping theme bridge append", swiftPath);
            }
        }
        else
        {
            var header = new StringBuilder();
            header.AppendLine("// Auto-generated by SwiftBindings — SwiftUI Bridge");
            header.AppendLine("import UIKit");
            header.AppendLine("import SwiftUI");
            header.AppendLine($"import {moduleName}");
            header.AppendLine();

            // Emit SBW_onMainThread since no view bridge created the file
            header.AppendLine("// --- Shared helpers ---");
            header.AppendLine();
            header.AppendLine("@discardableResult");
            header.AppendLine("func SBW_onMainThread<T>(_ block: () -> T) -> T {");
            header.AppendLine("    if Thread.isMainThread { return block() }");
            header.AppendLine("    return DispatchQueue.main.sync { block() }");
            header.AppendLine("}");
            header.AppendLine();

            File.WriteAllText(swiftPath, header.ToString() + swiftContent);
        }

        if (File.Exists(csPath))
        {
            if (IsAutoGeneratedFile(csPath))
            {
                // Insert theme bridge content before the closing namespace brace
                var existingContent = File.ReadAllText(csPath);
                var lastBrace = existingContent.LastIndexOf('}');
                if (lastBrace >= 0)
                {
                    var newContent = existingContent.Substring(0, lastBrace) + csContent + "\n}\n";
                    File.WriteAllText(csPath, newContent);
                }
                else
                {
                    File.AppendAllText(csPath, csContent);
                }
            }
            else
            {
                logger.LogWarning("Bridge file {Path} exists but was not auto-generated; skipping theme bridge insert", csPath);
            }
        }
        else
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SwiftBindings — SwiftUI Bridge");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine();
            sb.AppendLine($"namespace {@namespace}");
            sb.AppendLine("{");
            sb.Append(csContent);
            sb.AppendLine("}");
            sb.AppendLine();
            File.WriteAllText(csPath, sb.ToString());
        }

        var totalProps = themeInfos.Sum(t => t.Properties.Count);
        logger.LogInformation(
            "Theme bridge: {Count} type(s), {Props} settable properties",
            themeInfos.Count, totalProps);
    }

    #region Swift Generation

    private static string GenerateSwiftThemeBridge(
        string moduleName,
        List<ThemeBridgeInfo> themeInfos,
        bool viewBridgeExists,
        bool hasFonts)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// --- Theme Bridge ---");
        sb.AppendLine();

        // Emit font helpers if any theme has font properties
        if (hasFonts)
        {
            EmitFontHelpers(sb);
        }

        foreach (var info in themeInfos)
        {
            EmitSwiftThemeSetters(sb, moduleName, info);
        }

        return sb.ToString();
    }

    private static void EmitFontHelpers(StringBuilder sb)
    {
        sb.AppendLine("func SBW_fontWeight(_ raw: Int32) -> Font.Weight {");
        sb.AppendLine("    switch raw {");
        sb.AppendLine("    case 0: return .ultraLight");
        sb.AppendLine("    case 1: return .thin");
        sb.AppendLine("    case 2: return .light");
        sb.AppendLine("    case 3: return .regular");
        sb.AppendLine("    case 4: return .medium");
        sb.AppendLine("    case 5: return .semibold");
        sb.AppendLine("    case 6: return .bold");
        sb.AppendLine("    case 7: return .heavy");
        sb.AppendLine("    case 8: return .black");
        sb.AppendLine("    default: return .regular");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func SBW_fontDesign(_ raw: Int32) -> Font.Design {");
        sb.AppendLine("    switch raw {");
        sb.AppendLine("    case 0: return .default");
        sb.AppendLine("    case 1: return .rounded");
        sb.AppendLine("    case 2: return .monospaced");
        sb.AppendLine("    case 3: return .serif");
        sb.AppendLine("    default: return .default");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitSwiftThemeSetters(StringBuilder sb, string moduleName, ThemeBridgeInfo info)
    {
        sb.AppendLine($"// --- {info.ClassName} theme setters ---");
        sb.AppendLine();

        // Escape singleton name if it's a Swift keyword (e.g., `default`)
        var escapedSingleton = EscapeSwiftKeyword(info.SingletonName);

        foreach (var prop in info.Properties)
        {
            var funcName = $"SBW_{info.ClassName}_set_{prop.Name}";

            if (prop.Kind == ThemePropertyKind.Color)
            {
                sb.AppendLine($"@_cdecl(\"{funcName}\")");
                sb.AppendLine($"func {funcName}(");
                sb.AppendLine($"    _ r: Double, _ g: Double, _ b: Double, _ a: Double");
                sb.AppendLine(") {");
                sb.AppendLine("    SBW_onMainThread {");
                sb.AppendLine($"        {info.ClassName}.{escapedSingleton}.{prop.Name} = Color(red: r, green: g, blue: b, opacity: a)");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }
            else // Font
            {
                sb.AppendLine($"@_cdecl(\"{funcName}\")");
                sb.AppendLine($"func {funcName}(");
                sb.AppendLine($"    _ namePtr: UnsafePointer<UInt8>?, _ nameLen: Int,");
                sb.AppendLine($"    _ size: Double, _ weight: Int32, _ design: Int32, _ isSystem: Int32");
                sb.AppendLine(") {");
                sb.AppendLine("    SBW_onMainThread {");
                sb.AppendLine("        let font: Font");
                sb.AppendLine("        if isSystem != 0 {");
                sb.AppendLine("            font = .system(size: CGFloat(size),");
                sb.AppendLine("                           weight: SBW_fontWeight(weight),");
                sb.AppendLine("                           design: SBW_fontDesign(design))");
                sb.AppendLine("        } else if let namePtr = namePtr, nameLen > 0,");
                sb.AppendLine("                  let name = String(bytes: UnsafeBufferPointer(start: namePtr, count: nameLen),");
                sb.AppendLine("                                    encoding: .utf8) {");
                sb.AppendLine($"            font = .custom(name, size: CGFloat(size))");
                sb.AppendLine("        } else {");
                sb.AppendLine("            font = .system(size: CGFloat(size))");
                sb.AppendLine("        }");
                sb.AppendLine($"        {info.ClassName}.{escapedSingleton}.{prop.Name} = font");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }

            sb.AppendLine();
        }
    }

    #endregion

    #region C# Generation

    private static string GenerateCSharpThemeBridge(
        string @namespace,
        string moduleName,
        List<ThemeBridgeInfo> themeInfos)
    {
        var sb = new StringBuilder();
        var bridgeLib = $"{moduleName}SwiftBindings";

        foreach (var info in themeInfos)
        {
            EmitCSharpThemeClass(sb, moduleName, bridgeLib, info);
        }

        return sb.ToString();
    }

    private static void EmitCSharpThemeClass(StringBuilder sb, string moduleName, string bridgeLib, ThemeBridgeInfo info)
    {
        var hasColors = info.Properties.Any(p => p.Kind == ThemePropertyKind.Color);
        var hasFonts = info.Properties.Any(p => p.Kind == ThemePropertyKind.Font);

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Theme bridge setters for SwiftUI.Color and SwiftUI.Font properties.");
        sb.AppendLine($"    /// Set these before creating a view session. Changes take effect on next render.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public partial class {info.ClassName}");
        sb.AppendLine("    {");

        // Emit setter methods
        foreach (var prop in info.Properties)
        {
            var methodName = "Set" + char.ToUpperInvariant(prop.Name[0]) + prop.Name[1..];
            var funcName = $"SBW_{info.ClassName}_set_{prop.Name}";

            if (prop.Kind == ThemePropertyKind.Color)
            {
                sb.AppendLine($"        public static void {methodName}(Swift.SwiftColor value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            ThemeBridgeNativeMethods.{funcName}(");
                sb.AppendLine($"                value.R, value.G, value.B, value.A);");
                sb.AppendLine("        }");
            }
            else // Font
            {
                sb.AppendLine($"        public static unsafe void {methodName}(Swift.SwiftFont value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var nameBytes = value.FontName != null");
                sb.AppendLine($"                ? System.Text.Encoding.UTF8.GetBytes(value.FontName) : null;");
                sb.AppendLine($"            fixed (byte* namePtr = nameBytes)");
                sb.AppendLine("            {");
                sb.AppendLine($"                ThemeBridgeNativeMethods.{funcName}(");
                sb.AppendLine($"                    namePtr, nameBytes?.Length ?? 0,");
                sb.AppendLine($"                    value.Size, (int)value.Weight, (int)value.Design,");
                sb.AppendLine($"                    value.IsSystem ? 1 : 0);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        // Emit NativeMethods
        sb.AppendLine($"        private static partial class ThemeBridgeNativeMethods");
        sb.AppendLine("        {");

        foreach (var prop in info.Properties)
        {
            var funcName = $"SBW_{info.ClassName}_set_{prop.Name}";

            sb.AppendLine($"            [LibraryImport(\"{bridgeLib}\",");
            sb.AppendLine($"                EntryPoint = \"{funcName}\")]");
            sb.AppendLine($"            [UnmanagedCallConv(CallConvs = new[] {{ typeof(CallConvCdecl) }})]");

            if (prop.Kind == ThemePropertyKind.Color)
            {
                sb.AppendLine($"            internal static partial void {funcName}(");
                sb.AppendLine($"                double r, double g, double b, double a);");
            }
            else // Font
            {
                sb.AppendLine($"            internal static unsafe partial void {funcName}(");
                sb.AppendLine($"                byte* namePtr, nint nameLen,");
                sb.AppendLine($"                double size, int weight, int design, int isSystem);");
            }
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    #endregion
}
