// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;

namespace BindingsGeneration;

/// <summary>
/// Generates ARM64 (AAPCS64 + swiftcc) assembly thunks that bridge cdecl → swiftcc.
///
/// Key differences bridged:
///   - x20: self (instance methods) or metatype (constructors/static methods)
///   - x21: swifterror (throwing functions)
///   - Return: Swift uses up to 4 register slots (x0-x3/d0-d3) for structs 17-32 bytes,
///     while cdecl returns them indirectly via x8 pointer
/// </summary>
public sealed class Arm64ThunkTarget : ThunkTargetArch
{
    /// <inheritdoc/>
    public override string ArchTag => "arm64";

    /// <inheritdoc/>
    public override void EmitFileHeader(StringBuilder sb, string moduleName)
    {
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// Native ARM64 thunks for {moduleName}");
        sb.AppendLine("// Auto-generated by SwiftBindings — cdecl → swiftcc bridge");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine(".text");
        sb.AppendLine(".align 4");
        sb.AppendLine();
    }

    /// <inheritdoc/>
    public override void EmitSymbolDecl(StringBuilder sb, string thunkSymbol)
    {
        // Mach-O convention: C symbol "thunk_Module_hash" → Mach-O symbol "_thunk_Module_hash"
        sb.AppendLine($".globl _{thunkSymbol}");
        sb.AppendLine($".p2align 2");
        sb.AppendLine($"_{thunkSymbol}:");
    }

    /// <inheritdoc/>
    public override void EmitTailCall(StringBuilder sb, ThunkDescriptor descriptor)
    {
        sb.AppendLine($"    b       {descriptor.SwiftSymbol}");
    }

    /// <inheritdoc/>
    public override void EmitFullFrame(StringBuilder sb, ThunkDescriptor descriptor)
    {
        bool needsReturnBridge = ThunkAssemblyEmitter.NeedsReturnBridge(descriptor);
        bool needsSelfBridge = descriptor.IsInstanceMethod;
        bool needsMetatype = descriptor.IsConstructor || descriptor.IsStaticMethod;
        bool needsErrorBridge = descriptor.Throws;

        // Calculate the cdecl parameter index where the error out pointer lives.
        // cdecl signature: [self?,] param0, param1, ..., [error_out?]
        // For instance methods: self is x0, params start at x1, error_out is last
        // For static/free: params start at x0, error_out is last
        int errorOutRegIndex = -1;
        if (needsErrorBridge)
        {
            int baseIndex = needsSelfBridge ? 1 : 0;
            errorOutRegIndex = baseIndex + descriptor.ParameterCount;
        }

        // Prologue: save callee-saved registers x20, x19, plus frame pointer and link register.
        // For throwing functions, also save x21 — it's callee-saved in AAPCS64 (x19-x28 range)
        // and the thunk clobbers it for swifterror bridging. The P/Invoke wrapper expects x21
        // preserved across the native call; corrupting it causes SIGSEGV in Mono's GC transition.
        if (needsErrorBridge)
        {
            sb.AppendLine("    stp     x20, x19, [sp, #-48]!");
            sb.AppendLine("    stp     x29, x30, [sp, #16]");
            sb.AppendLine("    add     x29, sp, #16");
            sb.AppendLine("    str     x21, [sp, #32]");
        }
        else
        {
            sb.AppendLine("    stp     x20, x19, [sp, #-32]!");
            sb.AppendLine("    stp     x29, x30, [sp, #16]");
            sb.AppendLine("    add     x29, sp, #16");
        }

        // Save x8 (cdecl return buffer) to x19 if we need to bridge the return
        if (needsReturnBridge)
            sb.AppendLine("    mov     x19, x8");

        // Save error out pointer to x19 (if no return bridge — otherwise we need
        // a different strategy; use stack for error out when both are needed)
        if (needsErrorBridge && !needsReturnBridge)
        {
            sb.AppendLine($"    mov     x19, x{errorOutRegIndex}");
        }
        else if (needsErrorBridge && needsReturnBridge)
        {
            // Both return bridge and error bridge: x19 holds return buffer,
            // save error out pointer on stack
            sb.AppendLine($"    str     x{errorOutRegIndex}, [sp, #-16]!");
        }

        // Handle self parameter (instance methods): self is the last integer register
        // parameter before error_out, at position x{ParameterCount}.
        // CdeclSignatureContract orders: [Arguments] [Metadata] [Self] [ErrorOut]
        // Value parameters (x0..x{ParameterCount-1}) are already in the correct registers
        // for swiftcc — no shift needed. Only self needs to move to x20.
        if (needsSelfBridge)
        {
            sb.AppendLine($"    mov     x20, x{descriptor.ParameterCount}");
        }

        // Handle metatype (constructors/static methods)
        if (needsMetatype)
        {
            EmitMetatypeSetup(sb, descriptor);
        }

        // Clear swifterror register before call
        if (needsErrorBridge)
            sb.AppendLine("    mov     x21, xzr");

        // Call the Swift function
        sb.AppendLine($"    bl      {descriptor.SwiftSymbol}");

        // Store return registers to cdecl return buffer if needed
        if (needsReturnBridge)
            EmitReturnStore(sb, descriptor.ReturnLowering!);

        // Capture swifterror to the error out pointer
        if (needsErrorBridge && !needsReturnBridge)
        {
            sb.AppendLine("    str     x21, [x19]");
        }
        else if (needsErrorBridge && needsReturnBridge)
        {
            // Restore error out pointer from stack and store error
            sb.AppendLine("    ldr     x9, [sp], #16");
            sb.AppendLine("    str     x21, [x9]");
        }

        // Epilogue: restore callee-saved registers
        if (needsErrorBridge)
        {
            sb.AppendLine("    ldr     x21, [sp, #32]");
            sb.AppendLine("    ldp     x29, x30, [sp, #16]");
            sb.AppendLine("    ldp     x20, x19, [sp], #48");
        }
        else
        {
            sb.AppendLine("    ldp     x29, x30, [sp, #16]");
            sb.AppendLine("    ldp     x20, x19, [sp], #32");
        }
        sb.AppendLine("    ret");
    }

    /// <summary>
    /// Emits metatype setup for constructors and static methods.
    /// Calls the metadata accessor function and moves the result to x20.
    /// For constructors: saves/restores parameters around the metadata accessor call.
    /// For static methods: saves/restores parameters around the metadata accessor call.
    /// </summary>
    private static void EmitMetatypeSetup(StringBuilder sb, ThunkDescriptor descriptor)
    {
        if (descriptor.MetadataAccessorSymbol == null)
            return;

        int intParamCount = descriptor.ParameterCount;
        int floatParamCount = descriptor.FloatParameterCount;
        int totalSaveCount = intParamCount + floatParamCount;

        if (totalSaveCount > 0)
        {
            // Save all parameter registers (both integer and float) on the stack
            // before the metadata accessor call clobbers them.
            // The metadata accessor uses x0 for its result and may clobber
            // caller-saved registers (x0-x7, d0-d7).
            int stackSize = ((totalSaveCount * 8) + 15) & ~15;
            sb.AppendLine($"    sub     sp, sp, #{stackSize}");

            int offset = 0;
            for (int i = 0; i < intParamCount; i++)
            {
                sb.AppendLine($"    str     x{i}, [sp, #{offset}]");
                offset += 8;
            }
            for (int i = 0; i < floatParamCount; i++)
            {
                sb.AppendLine($"    str     d{i}, [sp, #{offset}]");
                offset += 8;
            }
        }

        // Call metadata accessor: x0 = request (0 = complete metadata)
        sb.AppendLine("    mov     x0, #0");
        sb.AppendLine($"    bl      {descriptor.MetadataAccessorSymbol}");
        sb.AppendLine("    mov     x20, x0");

        if (totalSaveCount > 0)
        {
            // Restore all parameter registers
            int stackSize = ((totalSaveCount * 8) + 15) & ~15;

            int offset = 0;
            for (int i = 0; i < intParamCount; i++)
            {
                sb.AppendLine($"    ldr     x{i}, [sp, #{offset}]");
                offset += 8;
            }
            for (int i = 0; i < floatParamCount; i++)
            {
                sb.AppendLine($"    ldr     d{i}, [sp, #{offset}]");
                offset += 8;
            }
            sb.AppendLine($"    add     sp, sp, #{stackSize}");
        }
    }

    /// <summary>
    /// Emits store instructions that write swiftcc's register-resident return into the cdecl return
    /// buffer (x19). Swift explodes a 17-32 byte struct field-wise into x0-x3/d0-d3; each field is
    /// stored at its natural-alignment offset using a width-matched instruction so the image matches
    /// the generated C# <c>[StructLayout(Sequential)]</c> struct the managed side reads back.
    ///   - Integer fields: strb/strh/str w/str x for 1/2/4/8 bytes
    ///   - Float fields:   str s/str d for 4/8 bytes (Float/Double)
    /// </summary>
    private static void EmitReturnStore(StringBuilder sb, TypeLoweringResult returnLowering)
    {
        foreach (var (slot, offset) in ThunkAssemblyEmitter.ReturnBufferSlots(returnLowering))
        {
            string instr;
            string reg;
            if (slot.File == RegisterFile.Integer)
            {
                instr = slot.ByteSize switch { 1 => "strb", 2 => "strh", 4 => "str", _ => "str" };
                reg = slot.ByteSize >= 8 ? $"x{slot.Index}" : $"w{slot.Index}";
            }
            else
            {
                instr = "str";
                reg = slot.ByteSize <= 4 ? $"s{slot.Index}" : $"d{slot.Index}";
            }

            string mem = offset == 0 ? "x19" : $"x19, #{offset}";
            sb.AppendLine($"    {instr,-7} {reg}, [{mem}]");
        }
    }
}
