// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;

namespace BindingsGeneration;

/// <summary>
/// Generates x86_64 (System V AMD64 + swiftcc) assembly thunks that bridge cdecl → swiftcc.
/// Emitted in AT&amp;T syntax (clang's default for <c>.s</c> on Darwin x86_64).
///
/// Key differences from ARM64 that this target bridges:
///   - %r13: self (swiftself) for instance methods, or the metatype for constructors/static methods
///   - %r12: swifterror for throwing functions
///   - Indirect return: SysV has no dedicated sret register. A struct returned indirectly is
///     passed as a hidden first integer argument in %rdi, shifting every explicit integer
///     argument down one register, and the callee returns the pointer in %rax. This is the
///     structural reason the x86_64 full-frame body cannot share ARM64's template: ARM64's
///     x8 sits outside the argument sequence, so its arguments never shift.
///   - Direct multi-register return (17-32 byte structs): swiftcc returns field-wise in
///     %rax/%rdx/%rcx/%r8 (integers) and %xmm0-3 (floats), with no SysV eightbyte merging.
///     cdecl returns the same struct indirectly via the %rdi sret pointer, so the thunk
///     captures the registers into that buffer (the "return bridge").
///
/// The integer argument sequence is %rdi, %rsi, %rdx, %rcx, %r8, %r9; floats are %xmm0-7.
/// Because callee-saved %rbx/%r12/%r13 are clobbered here, the full-frame template always
/// preserves them; arguments beyond the six integer registers would spill to the stack, so
/// <see cref="CanEmit"/> declines those shapes and the caller falls back to an @_cdecl wrapper.
/// </summary>
public sealed class SysVThunkTarget : ThunkTargetArch
{
    /// <summary>SysV integer argument registers, in order.</summary>
    private static readonly string[] IntArgRegs = { "rdi", "rsi", "rdx", "rcx", "r8", "r9" };

    /// <summary>swiftcc integer return registers, in order (field-wise, no eightbyte merge).</summary>
    private static readonly string[] IntRetRegs = { "rax", "rdx", "rcx", "r8" };

    /// <inheritdoc/>
    public override string ArchTag => "x86_64";

    /// <summary>
    /// Returns the SysV integer argument register at the given position in the call sequence.
    /// </summary>
    private static string IntArgReg(int index) => IntArgRegs[index];

    /// <summary>
    /// Computes the total number of integer registers the cdecl signature consumes:
    /// the hidden sret pointer (if the C return is &gt;16 bytes), the explicit integer
    /// parameters, self (instance methods), and the error-out pointer (throwing functions).
    /// </summary>
    private static int CdeclIntegerRegisterCount(ThunkDescriptor descriptor)
    {
        int sret = CdeclUsesSret(descriptor) ? 1 : 0;
        int self = descriptor.IsInstanceMethod ? 1 : 0;
        int error = descriptor.Throws ? 1 : 0;
        return sret + descriptor.ParameterCount + self + error;
    }

    /// <summary>
    /// True when the cdecl (C SysV) return is passed indirectly via a hidden %rdi sret pointer.
    /// In C, any struct larger than 16 bytes is returned this way regardless of whether Swift
    /// returns it directly in registers (17-32 bytes) or indirectly (&gt;32 bytes / address-only).
    /// </summary>
    private static bool CdeclUsesSret(ThunkDescriptor descriptor) =>
        descriptor.ReturnLowering is { TotalByteSize: > 16 };

    /// <inheritdoc/>
    public override bool CanEmit(ThunkDescriptor descriptor)
    {
        // Beyond six integer registers, SysV spills to the stack; this target only bridges
        // register-resident signatures. Likewise cap float parameters at the eight %xmm regs.
        // An indirectly-returned (>32 byte / address-only) struct consumes one integer register
        // for the cdecl sret pointer (counted by CdeclIntegerRegisterCount via CdeclUsesSret) and
        // is bridged by moving %rdi→%rax and shifting the explicit arguments down — see
        // EmitTailCall / EmitFullFrame.
        return CdeclIntegerRegisterCount(descriptor) <= IntArgRegs.Length
            && descriptor.FloatParameterCount <= 8;
    }

    /// <inheritdoc/>
    public override void EmitFileHeader(StringBuilder sb, string moduleName)
    {
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// Native x86_64 thunks for {moduleName}");
        sb.AppendLine("// Auto-generated by SwiftBindings — cdecl → swiftcc bridge (System V AMD64)");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine(".text");
        sb.AppendLine();
    }

    /// <inheritdoc/>
    public override void EmitSymbolDecl(StringBuilder sb, string thunkSymbol)
    {
        // Mach-O convention: C symbol "thunk_Module_hash" → Mach-O symbol "_thunk_Module_hash".
        sb.AppendLine($".globl _{thunkSymbol}");
        sb.AppendLine(".p2align 4, 0x90");
        sb.AppendLine($"_{thunkSymbol}:");
    }

    /// <inheritdoc/>
    public override void EmitTailCall(StringBuilder sb, ThunkDescriptor descriptor)
    {
        // A no-payload enum tag return must be zero-extended on x86_64 (the SysV ABI leaves the
        // upper bits of a sub-word return unspecified), so it cannot tail-call away. Set up a
        // minimal aligned frame, call, widen the tag, and return. On entry %rsp is 8 mod 16; the
        // single push realigns it so the call sees a 16-byte-aligned stack. The cdecl and swiftcc
        // argument registers already coincide here (no self/error/metatype/sret), so the arguments
        // pass through untouched.
        if (descriptor.ReturnZeroExtendFromBytes > 0)
        {
            sb.AppendLine("    pushq   %rbp");
            sb.AppendLine("    movq    %rsp, %rbp");
            sb.AppendLine($"    callq   {descriptor.SwiftSymbol}");
            EmitReturnZeroExtension(sb, descriptor);
            sb.AppendLine("    popq    %rbp");
            sb.AppendLine("    retq");
            return;
        }

        // An indirectly-returned (>32 byte / address-only) struct: cdecl passes the result buffer as
        // a hidden first integer argument in %rdi, but swiftcc expects it in %rax (read on entry,
        // preserved through return). Move the buffer into %rax and shift every explicit integer
        // argument down one register to fill the %rdi the sret pointer vacated; float arguments stay
        // in %xmm and never shift. The callee writes into [%rax] and returns it in %rax — exactly where
        // the cdecl caller expects the sret result — so this stays a tail call with no frame. The
        // ascending shift is safe because %rdi is read into %rax before the first store overwrites it.
        // (ClassifyThunk routes here only with no self/error/metatype, and a >16-byte DIRECT return
        // needs a register-capture bridge and goes through the full frame, so an sret here is always
        // the indirect case.)
        if (descriptor.ReturnLowering is { IsIndirect: true })
        {
            sb.AppendLine("    movq    %rdi, %rax");
            for (int i = 0; i < descriptor.ParameterCount; i++)
                sb.AppendLine($"    movq    %{IntArgReg(i + 1)}, %{IntArgReg(i)}");
            sb.AppendLine($"    jmp     {descriptor.SwiftSymbol}");
            return;
        }

        // No bridging needed: the signature has no self, error, metatype, or return buffer, so the
        // cdecl and swiftcc argument/return layouts coincide and we jump straight to the Swift symbol.
        sb.AppendLine($"    jmp     {descriptor.SwiftSymbol}");
    }

    /// <inheritdoc/>
    public override void EmitFullFrame(StringBuilder sb, ThunkDescriptor descriptor)
    {
        bool needsReturnBridge = ThunkAssemblyEmitter.NeedsReturnBridge(descriptor);
        // An indirect (>32 byte / address-only) return: swiftcc reads/returns the buffer in %rax,
        // cdecl passes it in %rdi. Distinct from needsReturnBridge, which captures a 17-32 byte
        // direct register return into the cdecl buffer. Both consume %rdi on the cdecl side
        // (cdeclUsesSret), so both stash %rdi and shift the explicit arguments down.
        bool swiftIndirect = descriptor.ReturnLowering is { IsIndirect: true };
        bool needsSelfBridge = descriptor.IsInstanceMethod;
        bool needsMetatype = descriptor.IsConstructor || descriptor.IsStaticMethod;
        bool needsErrorBridge = descriptor.Throws;
        bool cdeclUsesSret = CdeclUsesSret(descriptor);
        int sretOffset = cdeclUsesSret ? 1 : 0;

        // cdecl integer-register positions, accounting for the hidden sret pointer in %rdi.
        // Layout: [sret?] arg0 .. arg{N-1} [self?] [errorOut?]
        int selfCdeclIndex = descriptor.ParameterCount + sretOffset;
        int errorCdeclIndex = descriptor.ParameterCount
            + (needsSelfBridge ? 1 : 0)
            + sretOffset;

        // Prologue. Always preserve the callee-saved registers this template clobbers:
        // %rbx (stashes the sret buffer), %r12 (swifterror), %r13 (swiftself/metatype).
        // After `push %rbp` the stack is 16-byte aligned; three 8-byte pushes leave it
        // misaligned by 8, so a single 8-byte local slot both realigns it for the call and
        // holds the error-out pointer across the call.
        sb.AppendLine("    pushq   %rbp");
        sb.AppendLine("    movq    %rsp, %rbp");
        sb.AppendLine("    pushq   %rbx");
        sb.AppendLine("    pushq   %r12");
        sb.AppendLine("    pushq   %r13");
        sb.AppendLine("    subq    $8, %rsp");
        const string errorSlot = "-32(%rbp)";

        // Stash the cdecl sret pointer (%rdi) before the argument shift overwrites it. Both the
        // direct-return bridge (capture into the buffer) and the indirect return (pass the buffer to
        // swiftcc in %rax) own this pointer across the call.
        if (cdeclUsesSret)
            sb.AppendLine("    movq    %rdi, %rbx");

        // Stash the error-out pointer before the metatype accessor call can clobber it.
        if (needsErrorBridge)
            sb.AppendLine($"    movq    %{IntArgReg(errorCdeclIndex)}, {errorSlot}");

        // self → %r13 (swiftself).
        if (needsSelfBridge)
            sb.AppendLine($"    movq    %{IntArgReg(selfCdeclIndex)}, %r13");

        // metatype → %r13 (constructors/static methods).
        if (needsMetatype)
            EmitMetatypeSetup(sb, descriptor, sretOffset);

        // Drop the sret pointer out of the argument sequence: shift each explicit integer
        // argument down one register so it lands where swiftcc expects it. Ascending order is
        // safe — each source register is read before the next store would overwrite it. Float
        // arguments stay in %xmm0.. and never shift.
        if (cdeclUsesSret)
        {
            for (int i = 0; i < descriptor.ParameterCount; i++)
                sb.AppendLine($"    movq    %{IntArgReg(i + 1)}, %{IntArgReg(i)}");
        }

        // Clear swifterror before the call.
        if (needsErrorBridge)
            sb.AppendLine("    xorl    %r12d, %r12d");

        // An indirect return: swiftcc reads its result buffer from %rax on entry. Move the stashed
        // cdecl sret pointer into %rax now — after the metatype accessor (which clobbers %rax) and
        // the argument shift have run, and immediately before the call.
        if (swiftIndirect)
            sb.AppendLine("    movq    %rbx, %rax");

        sb.AppendLine($"    callq   {descriptor.SwiftSymbol}");

        // Zero-extend a narrow no-payload-enum tag return. Mutually exclusive with the return
        // bridge (a bridged struct is >16 bytes; an enum tag is 1-2), so it never races the
        // %rbx → %rax restore below.
        if (descriptor.ReturnZeroExtendFromBytes > 0)
            EmitReturnZeroExtension(sb, descriptor);

        // Capture the register-resident return into the cdecl sret buffer.
        if (needsReturnBridge)
            EmitReturnStore(sb, descriptor.ReturnLowering!);

        // Write swifterror back through the saved error-out pointer.
        if (needsErrorBridge)
        {
            sb.AppendLine($"    movq    {errorSlot}, %r10");
            sb.AppendLine("    movq    %r12, (%r10)");
        }

        // SysV returns the sret pointer in %rax. The return-bridge path owns the buffer it captured
        // into, and the indirect path passed it to swiftcc; restore it from the %rbx stash either way
        // (swiftcc preserves %rbx, so this is correct even when swiftcc already left the buffer in %rax).
        if (cdeclUsesSret)
            sb.AppendLine("    movq    %rbx, %rax");

        // Epilogue.
        sb.AppendLine("    addq    $8, %rsp");
        sb.AppendLine("    popq    %r13");
        sb.AppendLine("    popq    %r12");
        sb.AppendLine("    popq    %rbx");
        sb.AppendLine("    popq    %rbp");
        sb.AppendLine("    retq");
    }

    /// <summary>
    /// Emits metatype setup for constructors and static methods: calls the metadata accessor
    /// (request in %rdi, result in %rax) and moves the metatype into %r13. The accessor is an
    /// ordinary call and clobbers the caller-saved argument registers, so the explicit integer
    /// and float arguments are spilled across it and restored afterwards.
    /// </summary>
    /// <param name="sb">Assembly buffer.</param>
    /// <param name="descriptor">Thunk descriptor.</param>
    /// <param name="sretOffset">1 if the cdecl integer arguments start after a hidden sret pointer, else 0.</param>
    private static void EmitMetatypeSetup(StringBuilder sb, ThunkDescriptor descriptor, int sretOffset)
    {
        if (descriptor.MetadataAccessorSymbol == null)
            return;

        int intParamCount = descriptor.ParameterCount;
        int floatParamCount = descriptor.FloatParameterCount;
        int totalSaveCount = intParamCount + floatParamCount;

        if (totalSaveCount > 0)
        {
            // Round the spill area up to a 16-byte multiple so the call stays aligned.
            int stackSize = ((totalSaveCount * 8) + 15) & ~15;
            sb.AppendLine($"    subq    ${stackSize}, %rsp");

            int offset = 0;
            for (int i = 0; i < intParamCount; i++)
            {
                sb.AppendLine($"    movq    %{IntArgReg(sretOffset + i)}, {SpillMem(offset)}");
                offset += 8;
            }
            for (int i = 0; i < floatParamCount; i++)
            {
                sb.AppendLine($"    movsd   %xmm{i}, {SpillMem(offset)}");
                offset += 8;
            }
        }

        // Request complete metadata (request = 0).
        sb.AppendLine("    xorl    %edi, %edi");
        sb.AppendLine($"    callq   {descriptor.MetadataAccessorSymbol}");
        sb.AppendLine("    movq    %rax, %r13");

        if (totalSaveCount > 0)
        {
            int stackSize = ((totalSaveCount * 8) + 15) & ~15;

            int offset = 0;
            for (int i = 0; i < intParamCount; i++)
            {
                sb.AppendLine($"    movq    {SpillMem(offset)}, %{IntArgReg(sretOffset + i)}");
                offset += 8;
            }
            for (int i = 0; i < floatParamCount; i++)
            {
                sb.AppendLine($"    movsd   {SpillMem(offset)}, %xmm{i}");
                offset += 8;
            }
            sb.AppendLine($"    addq    ${stackSize}, %rsp");
        }
    }

    /// <summary>
    /// Emits store instructions that write swiftcc's register-resident return into the cdecl sret
    /// buffer held in %rbx. swiftcc explodes a 17-32 byte struct field-wise into %rax/%rdx/%rcx/%r8
    /// (integers) and %xmm0-3 (floats); each field is stored at its natural-alignment offset with a
    /// width-matched instruction (movb/movw/movl/movq, movss/movsd) using the correctly-sized
    /// sub-register, so the buffer image matches the generated C# <c>[StructLayout(Sequential)]</c>
    /// struct the managed side reads back.
    /// </summary>
    private static void EmitReturnStore(StringBuilder sb, TypeLoweringResult returnLowering)
    {
        foreach (var (slot, offset) in ThunkAssemblyEmitter.ReturnBufferSlots(returnLowering))
        {
            if (slot.File == RegisterFile.Integer)
            {
                string instr = slot.ByteSize switch { 1 => "movb", 2 => "movw", 4 => "movl", _ => "movq" };
                sb.AppendLine($"    {instr,-7} %{IntRetSubReg(slot.Index, slot.ByteSize)}, {BufferMem(offset)}");
            }
            else
            {
                string instr = slot.ByteSize <= 4 ? "movss" : "movsd";
                sb.AppendLine($"    {instr,-7} %xmm{slot.Index}, {BufferMem(offset)}");
            }
        }
    }

    /// <summary>
    /// Zero-extends a narrow no-payload-enum tag return (1 or 2 bytes) into %eax. Writing the 32-bit
    /// %eax also clears the upper 32 bits of %rax, so the managed side reads a clean value whether the
    /// enum's underlying integer is 32- or 64-bit. Enum tags are non-negative, so zero-extension is
    /// value-preserving. See <see cref="ThunkDescriptor.ReturnZeroExtendFromBytes"/>.
    /// </summary>
    private static void EmitReturnZeroExtension(StringBuilder sb, ThunkDescriptor descriptor)
    {
        switch (descriptor.ReturnZeroExtendFromBytes)
        {
            case 1:
                sb.AppendLine("    movzbl  %al, %eax");
                break;
            case 2:
                sb.AppendLine("    movzwl  %ax, %eax");
                break;
        }
    }

    /// <summary>Sub-registers of the four swiftcc integer return registers, indexed [retReg][byte/word/dword/qword].</summary>
    private static readonly string[][] IntRetSubRegs =
    {
        new[] { "al",  "ax",  "eax", "rax" },
        new[] { "dl",  "dx",  "edx", "rdx" },
        new[] { "cl",  "cx",  "ecx", "rcx" },
        new[] { "r8b", "r8w", "r8d", "r8"  },
    };

    /// <summary>Returns the return register at <paramref name="index"/> sized to <paramref name="byteSize"/> bytes.</summary>
    private static string IntRetSubReg(int index, int byteSize)
    {
        int column = byteSize switch { 1 => 0, 2 => 1, 4 => 2, _ => 3 };
        return IntRetSubRegs[index][column];
    }

    /// <summary>Formats a stack-spill memory operand relative to %rsp.</summary>
    private static string SpillMem(int offset) => offset == 0 ? "(%rsp)" : $"{offset}(%rsp)";

    /// <summary>Formats a return-buffer memory operand relative to the sret pointer in %rbx.</summary>
    private static string BufferMem(int offset) => offset == 0 ? "(%rbx)" : $"{offset}(%rbx)";
}
