// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;

namespace BindingsGeneration;

/// <summary>
/// Describes a native ARM64 thunk to be generated.
/// </summary>
/// <param name="ThunkSymbol">The exported symbol name for the thunk (e.g., "_thunk_Module_methodName_a1b2c3d4").</param>
/// <param name="SwiftSymbol">The target Swift symbol to call (with underscore prefix, e.g., "_$s6Module6methodyyF").</param>
/// <param name="ReturnLowering">How the return type maps to ARM64 registers. Null for void returns.</param>
/// <param name="SelfLowering">How the self parameter maps to registers. Null for free functions and constructors.</param>
/// <param name="ParameterCount">Number of cdecl integer register parameters (excluding self, error out pointer).</param>
/// <param name="FloatParameterCount">Number of cdecl float register parameters (d0-d7).</param>
/// <param name="IsInstanceMethod">True if this is an instance method (self in x20).</param>
/// <param name="IsStaticMethod">True if this is a static method (metatype in x20).</param>
/// <param name="IsConstructor">True if this is a constructor (metatype in x20, allocating init).</param>
/// <param name="Throws">True if the function can throw (swifterror in x21).</param>
/// <param name="MetadataAccessorSymbol">The metadata accessor symbol for constructors/static methods (with underscore prefix).</param>
public record ThunkDescriptor(
    string ThunkSymbol,
    string SwiftSymbol,
    TypeLoweringResult? ReturnLowering,
    TypeLoweringResult? SelfLowering,
    int ParameterCount,
    int FloatParameterCount,
    bool IsInstanceMethod,
    bool IsStaticMethod,
    bool IsConstructor,
    bool Throws,
    string? MetadataAccessorSymbol);

/// <summary>
/// Generates ARM64 assembly thunk functions that bridge cdecl → swiftcc calling conventions.
///
/// These thunks allow C# P/Invoke (which uses cdecl) to call Swift functions using their
/// native calling convention without @_cdecl wrappers or CallConvSwift runtime support.
///
/// Key differences bridged:
///   - x20: self (instance methods) or metatype (constructors/static methods)
///   - x21: swifterror (throwing functions)
///   - Return: Swift uses up to 4 register slots (x0-x3/d0-d3) for structs 17-32 bytes,
///     while cdecl returns them indirectly via x8 pointer
///
/// Reference: .claude/worktrees/native-thunk-experiments/experiments/thunks/thunks.s
/// </summary>
public static class ThunkAssemblyEmitter
{
    /// <summary>
    /// Emits the assembly file header with section and alignment directives.
    /// </summary>
    /// <param name="moduleName">The Swift module name for the comment header.</param>
    /// <returns>Assembly header text.</returns>
    public static string EmitFileHeader(string moduleName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// Native ARM64 thunks for {moduleName}");
        sb.AppendLine("// Auto-generated by SwiftBindings — cdecl → swiftcc bridge");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine(".text");
        sb.AppendLine(".align 4");
        sb.AppendLine();
        return sb.ToString();
    }

    /// <summary>
    /// Emits the assembly file footer (currently empty, reserved for future use).
    /// </summary>
    /// <returns>Assembly footer text.</returns>
    public static string EmitFileFooter()
    {
        return string.Empty;
    }

    /// <summary>
    /// Emits a single ARM64 thunk function from a ThunkDescriptor.
    /// Composes the appropriate template based on descriptor flags.
    /// </summary>
    /// <param name="descriptor">The thunk descriptor with all metadata needed for code generation.</param>
    /// <returns>The complete assembly text for this thunk function.</returns>
    public static string EmitThunk(ThunkDescriptor descriptor)
    {
        var sb = new StringBuilder();

        // Classify the thunk to select the optimal template
        var classification = ClassifyThunk(descriptor);

        sb.AppendLine($".globl {descriptor.ThunkSymbol}");
        sb.AppendLine($".p2align 2");
        sb.AppendLine($"{descriptor.ThunkSymbol}:");

        switch (classification)
        {
            case ThunkKind.TailCall:
                EmitTailCall(sb, descriptor);
                break;
            case ThunkKind.FullFrame:
                EmitFullFrame(sb, descriptor);
                break;
        }

        sb.AppendLine();
        return sb.ToString();
    }

    /// <summary>
    /// Classifies a thunk to determine which template to use.
    /// </summary>
    private enum ThunkKind
    {
        /// <summary>Tail call (b instruction) — zero overhead, no frame needed.</summary>
        TailCall,
        /// <summary>Full frame with callee-saved registers (x19, x20).</summary>
        FullFrame,
    }

    /// <summary>
    /// Determines which template to use based on the descriptor.
    /// </summary>
    private static ThunkKind ClassifyThunk(ThunkDescriptor descriptor)
    {
        bool needsReturnBridge = NeedsReturnBridge(descriptor);
        bool needsSelfBridge = descriptor.IsInstanceMethod;
        bool needsMetatype = descriptor.IsConstructor || descriptor.IsStaticMethod;
        bool needsErrorBridge = descriptor.Throws;

        // Tail call: no bridging needed at all — parameters and return are identical
        // in both cdecl and swiftcc, so just branch directly
        if (!needsReturnBridge && !needsSelfBridge && !needsMetatype && !needsErrorBridge)
            return ThunkKind.TailCall;

        // Full frame: needs x19 (return buffer / error out ptr) and/or x20 (self / metatype)
        return ThunkKind.FullFrame;
    }

    /// <summary>
    /// Determines whether the return value needs bridging (Swift returns in registers,
    /// cdecl returns indirectly via x8).
    /// </summary>
    private static bool NeedsReturnBridge(ThunkDescriptor descriptor)
    {
        if (descriptor.ReturnLowering == null)
            return false;

        // If indirect, both conventions use x8 — no bridge needed
        if (descriptor.ReturnLowering.IsIndirect)
            return false;

        // If total byte size > 16, cdecl uses x8 but Swift uses registers — bridge needed
        if (descriptor.ReturnLowering.TotalByteSize > 16)
            return true;

        // ≤ 16 bytes: both conventions return in x0+x1 / d0+d1 — no bridge needed
        // UNLESS there are mixed int/float registers that need different store patterns
        // For ≤ 16 bytes, cdecl and swiftcc agree on register usage, so no bridge
        return false;
    }

    /// <summary>
    /// Emits a tail call thunk — the simplest case, zero overhead.
    /// Used when cdecl and swiftcc parameter/return layouts are identical.
    /// </summary>
    private static void EmitTailCall(StringBuilder sb, ThunkDescriptor descriptor)
    {
        sb.AppendLine($"    b       {descriptor.SwiftSymbol}");
    }

    /// <summary>
    /// Emits a full-frame thunk that saves/restores callee-saved registers (x19, x20).
    /// This is the general-purpose template that handles all bridging cases:
    /// self-in-x20, metatype-in-x20, swifterror-in-x21, and struct return bridging.
    /// </summary>
    private static void EmitFullFrame(StringBuilder sb, ThunkDescriptor descriptor)
    {
        bool needsReturnBridge = NeedsReturnBridge(descriptor);
        bool needsSelfBridge = descriptor.IsInstanceMethod;
        bool needsMetatype = descriptor.IsConstructor || descriptor.IsStaticMethod;
        bool needsErrorBridge = descriptor.Throws;

        // Calculate the cdecl parameter index where the error out pointer lives.
        // cdecl signature: [self?,] param0, param1, ..., [error_out?]
        // For instance methods: self is x0, params start at x1, error_out is last
        // For static/free: params start at x0, error_out is last
        int errorOutRegIndex = -1;
        if (needsErrorBridge)
        {
            int baseIndex = needsSelfBridge ? 1 : 0;
            errorOutRegIndex = baseIndex + descriptor.ParameterCount;
        }

        // Prologue: save callee-saved registers x20, x19, plus frame pointer and link register.
        // Note: x21 (swifterror) is caller-saved in AAPCS64 — the thunk's caller does not
        // expect it preserved, so we don't save/restore it. We only use it for the Swift call.
        sb.AppendLine("    stp     x20, x19, [sp, #-32]!");
        sb.AppendLine("    stp     x29, x30, [sp, #16]");
        sb.AppendLine("    add     x29, sp, #16");

        // Save x8 (cdecl return buffer) to x19 if we need to bridge the return
        if (needsReturnBridge)
            sb.AppendLine("    mov     x19, x8");

        // Save error out pointer to x19 (if no return bridge — otherwise we need
        // a different strategy; use stack for error out when both are needed)
        if (needsErrorBridge && !needsReturnBridge)
        {
            sb.AppendLine($"    mov     x19, x{errorOutRegIndex}");
        }
        else if (needsErrorBridge && needsReturnBridge)
        {
            // Both return bridge and error bridge: x19 holds return buffer,
            // save error out pointer on stack
            sb.AppendLine($"    str     x{errorOutRegIndex}, [sp, #-16]!");
        }

        // Handle self parameter (instance methods): move x0 → x20, shift params down
        if (needsSelfBridge)
        {
            sb.AppendLine("    mov     x20, x0");
            EmitParameterShift(sb, descriptor.ParameterCount);
        }

        // Handle metatype (constructors/static methods)
        if (needsMetatype)
        {
            EmitMetatypeSetup(sb, descriptor);
        }

        // Clear swifterror register before call
        if (needsErrorBridge)
            sb.AppendLine("    mov     x21, xzr");

        // Call the Swift function
        sb.AppendLine($"    bl      {descriptor.SwiftSymbol}");

        // Store return registers to cdecl return buffer if needed
        if (needsReturnBridge)
            EmitReturnStore(sb, descriptor.ReturnLowering!);

        // Capture swifterror to the error out pointer
        if (needsErrorBridge && !needsReturnBridge)
        {
            sb.AppendLine("    str     x21, [x19]");
        }
        else if (needsErrorBridge && needsReturnBridge)
        {
            // Restore error out pointer from stack and store error
            sb.AppendLine("    ldr     x9, [sp], #16");
            sb.AppendLine("    str     x21, [x9]");
        }

        // Epilogue: restore callee-saved registers
        sb.AppendLine("    ldp     x29, x30, [sp, #16]");
        sb.AppendLine("    ldp     x20, x19, [sp], #32");
        sb.AppendLine("    ret");
    }

    /// <summary>
    /// Emits parameter shift instructions for instance methods.
    /// When self moves from x0 → x20, the remaining parameters need to shift down:
    /// x1 → x0, x2 → x1, etc.
    /// </summary>
    private static void EmitParameterShift(StringBuilder sb, int parameterCount)
    {
        for (int i = 0; i < parameterCount; i++)
        {
            sb.AppendLine($"    mov     x{i}, x{i + 1}");
        }
    }

    /// <summary>
    /// Emits metatype setup for constructors and static methods.
    /// Calls the metadata accessor function and moves the result to x20.
    /// For constructors: saves/restores parameters around the metadata accessor call.
    /// For static methods: saves/restores parameters around the metadata accessor call.
    /// </summary>
    private static void EmitMetatypeSetup(StringBuilder sb, ThunkDescriptor descriptor)
    {
        if (descriptor.MetadataAccessorSymbol == null)
            return;

        int intParamCount = descriptor.ParameterCount;
        int floatParamCount = descriptor.FloatParameterCount;
        int totalSaveCount = intParamCount + floatParamCount;

        if (totalSaveCount > 0)
        {
            // Save all parameter registers (both integer and float) on the stack
            // before the metadata accessor call clobbers them.
            // The metadata accessor uses x0 for its result and may clobber
            // caller-saved registers (x0-x7, d0-d7).
            int stackSize = ((totalSaveCount * 8) + 15) & ~15;
            sb.AppendLine($"    sub     sp, sp, #{stackSize}");

            int offset = 0;
            for (int i = 0; i < intParamCount; i++)
            {
                sb.AppendLine($"    str     x{i}, [sp, #{offset}]");
                offset += 8;
            }
            for (int i = 0; i < floatParamCount; i++)
            {
                sb.AppendLine($"    str     d{i}, [sp, #{offset}]");
                offset += 8;
            }
        }

        // Call metadata accessor: x0 = request (0 = complete metadata)
        sb.AppendLine("    mov     x0, #0");
        sb.AppendLine($"    bl      {descriptor.MetadataAccessorSymbol}");
        sb.AppendLine("    mov     x20, x0");

        if (totalSaveCount > 0)
        {
            // Restore all parameter registers
            int stackSize = ((totalSaveCount * 8) + 15) & ~15;

            int offset = 0;
            for (int i = 0; i < intParamCount; i++)
            {
                sb.AppendLine($"    ldr     x{i}, [sp, #{offset}]");
                offset += 8;
            }
            for (int i = 0; i < floatParamCount; i++)
            {
                sb.AppendLine($"    ldr     d{i}, [sp, #{offset}]");
                offset += 8;
            }
            sb.AppendLine($"    add     sp, sp, #{stackSize}");
        }
    }

    /// <summary>
    /// Emits store instructions to write Swift return registers to the cdecl return buffer (x19).
    /// The store pattern is generated from the TypeLoweringResult slots, computing byte offsets
    /// from field sizes and emitting the appropriate str xN/dN instructions.
    ///
    /// Each slot occupies 8 bytes in the return buffer regardless of the field's logical size
    /// (e.g., Bool = 1 byte). This matches Swift's ABI where each struct field in register
    /// return occupies a full 64-bit register, and the cdecl return buffer is laid out with
    /// 8-byte alignment per register slot. The `str xN/dN` instructions write full 64-bit
    /// values, with the meaningful data in the low bits and zeros in the high bits.
    /// </summary>
    private static void EmitReturnStore(StringBuilder sb, TypeLoweringResult returnLowering)
    {
        int offset = 0;

        foreach (var slot in returnLowering.Slots)
        {
            string reg = slot.File == RegisterFile.Integer
                ? $"x{slot.Index}"
                : $"d{slot.Index}";

            sb.AppendLine($"    str     {reg}, [{(offset == 0 ? "x19" : $"x19, #{offset}")}]");

            // Each register slot occupies 8 bytes in the return buffer.
            offset += 8;
        }
    }

    /// <summary>
    /// Generates a unique thunk symbol name from a module name and method mangled name.
    /// Uses a hash of the mangled name for uniqueness while keeping the symbol readable.
    /// </summary>
    /// <param name="moduleName">The Swift module name.</param>
    /// <param name="mangledName">The Swift mangled name of the method.</param>
    /// <returns>The thunk symbol with leading underscore (e.g., "_thunk_Module_a1b2c3d4").</returns>
    public static string GenerateThunkSymbol(string moduleName, string mangledName)
    {
        // Use a stable hash of the full mangled name for uniqueness
        var hash = ComputeStableHash(mangledName);
        var sanitizedModule = SanitizeForSymbol(moduleName);
        return $"_thunk_{sanitizedModule}_{hash:x8}";
    }

    /// <summary>
    /// Computes a stable 32-bit hash for symbol generation.
    /// Uses FNV-1a for good distribution and determinism.
    /// </summary>
    private static uint ComputeStableHash(string input)
    {
        const uint fnvPrime = 0x01000193;
        const uint fnvOffset = 0x811c9dc5;

        uint hash = fnvOffset;
        foreach (char c in input)
        {
            hash ^= c;
            hash *= fnvPrime;
        }
        return hash;
    }

    /// <summary>
    /// Sanitizes a module name for use in assembly symbols (alphanumeric + underscore only).
    /// </summary>
    private static string SanitizeForSymbol(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }
}
