// Auto-generated by SwiftBindings — SwiftUI Bridge
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace Swift.Lottie
{
    internal static class LottieButtonBridgeNativeMethods
    {
        private const string BridgeLib = "LottieBridge";

        [DllImport(BridgeLib, EntryPoint = "SBW_Lottie_LottieButton_Create")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static extern IntPtr Create(IntPtr animation, IntPtr actionCallback, IntPtr actionUserData);

        [DllImport(BridgeLib, EntryPoint = "SBW_Lottie_LottieButton_GetViewController")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static extern IntPtr GetViewController(IntPtr handle);

        [DllImport(BridgeLib, EntryPoint = "SBW_Lottie_LottieButton_Free")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static extern void Free(IntPtr handle);
    }

    public sealed class LottieButtonSession : IDisposable
    {
        private IntPtr _handle;
        private bool _disposed;
        private GCHandle[] _closureHandles = Array.Empty<GCHandle>();

        internal LottieButtonSession(IntPtr handle) => _handle = handle;

        public IntPtr Handle => !_disposed
            ? _handle
            : throw new ObjectDisposedException(nameof(LottieButtonSession));

        public IntPtr GetViewController() =>
            LottieButtonBridgeNativeMethods.GetViewController(Handle);

        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static void ActionTrampoline(IntPtr userData)
        {
            if (userData != IntPtr.Zero)
            {
                var h = GCHandle.FromIntPtr(userData);
                if (h.Target is Action action)
                    action();
            }
        }

        public static unsafe LottieButtonSession Create(Swift.Lottie.LottieAnimation? animation, Action? action = null)
        {
            var closureHandles = new System.Collections.Generic.List<GCHandle>();
            try
            {
                IntPtr actionCallback = IntPtr.Zero;
                IntPtr actionUserData = IntPtr.Zero;
                if (action != null)
                {
                    var h = GCHandle.Alloc(action);
                    closureHandles.Add(h);
                    actionUserData = GCHandle.ToIntPtr(h);
                    delegate* unmanaged[Cdecl]<IntPtr, void> fn = &ActionTrampoline;
                    actionCallback = (IntPtr)fn;
                }

                var handle = LottieButtonBridgeNativeMethods.Create(animation?.Payload.DangerousGetHandle() ?? IntPtr.Zero, actionCallback, actionUserData);
                if (handle == IntPtr.Zero)
                    throw new InvalidOperationException("Failed to create LottieButton session.");
                var session = new LottieButtonSession(handle);
                session._closureHandles = closureHandles.ToArray();
                closureHandles.Clear();
                return session;
            }
            finally
            {
                foreach (var h in closureHandles)
                    if (h.IsAllocated) h.Free();
            }
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                _disposed = true;
                LottieButtonBridgeNativeMethods.Free(_handle);
                foreach (var h in _closureHandles)
                    if (h.IsAllocated) h.Free();
                _closureHandles = Array.Empty<GCHandle>();
                _handle = IntPtr.Zero;
            }
        }
    }

    internal static class LottieSwitchBridgeNativeMethods
    {
        private const string BridgeLib = "LottieBridge";

        [DllImport(BridgeLib, EntryPoint = "SBW_Lottie_LottieSwitch_Create")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static extern IntPtr Create(IntPtr animation);

        [DllImport(BridgeLib, EntryPoint = "SBW_Lottie_LottieSwitch_GetViewController")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static extern IntPtr GetViewController(IntPtr handle);

        [DllImport(BridgeLib, EntryPoint = "SBW_Lottie_LottieSwitch_Free")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static extern void Free(IntPtr handle);
    }

    public sealed class LottieSwitchSession : IDisposable
    {
        private IntPtr _handle;
        private bool _disposed;

        internal LottieSwitchSession(IntPtr handle) => _handle = handle;

        public IntPtr Handle => !_disposed
            ? _handle
            : throw new ObjectDisposedException(nameof(LottieSwitchSession));

        public IntPtr GetViewController() =>
            LottieSwitchBridgeNativeMethods.GetViewController(Handle);

        public static LottieSwitchSession Create(Swift.Lottie.LottieAnimation? animation)
        {
            var handle = LottieSwitchBridgeNativeMethods.Create(animation?.Payload.DangerousGetHandle() ?? IntPtr.Zero);
            if (handle == IntPtr.Zero)
                throw new InvalidOperationException("Failed to create LottieSwitch session.");
            return new LottieSwitchSession(handle);
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                _disposed = true;
                LottieSwitchBridgeNativeMethods.Free(_handle);
                _handle = IntPtr.Zero;
            }
        }
    }

    // BRIDGE TEMPLATE: LottieView (Unsupported: Generic type parameter)
    // See: src/docs/swiftui-bridge-design.md

}

