// Auto-generated by SwiftBindings — SwiftUI Bridge
import UIKit
import SwiftUI
import Lottie

// --- Shared helpers ---

@discardableResult
func SBW_onMainThread<T>(_ block: () -> T) -> T {
    if Thread.isMainThread { return block() }
    return DispatchQueue.main.sync { block() }
}

// --- LottieButton ---

final class SBW_Lottie_LottieButton_Session {
    let hostingController: UIHostingController<LottieButton>
    let actionCallback: ((@convention(c) (UnsafeMutableRawPointer?) -> Void))?
    let actionUserData: UnsafeMutableRawPointer?

    init(animationPtr: UnsafeMutableRawPointer?,
         actionCallback: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?,
         actionUserData: UnsafeMutableRawPointer?) {
        self.actionCallback = actionCallback
        self.actionUserData = actionUserData
        let cb_action = actionCallback; let ud_action = actionUserData
        let animationVal: LottieAnimation? = animationPtr.map { Unmanaged<LottieAnimation>.fromOpaque($0).takeUnretainedValue() }
        let view = LottieButton(animation: animationVal, action: {
            DispatchQueue.main.async { cb_action?(ud_action) }
        })
        self.hostingController = UIHostingController(rootView: view)
    }
}

var SBW_Lottie_LottieButton_liveHandles = Set<UnsafeMutableRawPointer>()

@_cdecl("SBW_Lottie_LottieButton_Create")
public func SBW_Lottie_LottieButton_Create(_ animationPtr: UnsafeMutableRawPointer?,
    _ actionCallback: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?,
    _ actionUserData: UnsafeMutableRawPointer?
) -> UnsafeMutableRawPointer? {
    return SBW_onMainThread {
        let session = SBW_Lottie_LottieButton_Session(
            animationPtr: animationPtr,
            actionCallback: actionCallback,
            actionUserData: actionUserData)
        let handle = Unmanaged.passRetained(session).toOpaque()
        SBW_Lottie_LottieButton_liveHandles.insert(handle)
        return handle
    }
}

@_cdecl("SBW_Lottie_LottieButton_GetViewController")
public func SBW_Lottie_LottieButton_GetViewController(
    _ handle: UnsafeMutableRawPointer?
) -> UnsafeMutableRawPointer? {
    return SBW_onMainThread {
        guard let handle = handle,
              SBW_Lottie_LottieButton_liveHandles.contains(handle) else { return nil }
        let session = Unmanaged<SBW_Lottie_LottieButton_Session>
            .fromOpaque(handle).takeUnretainedValue()
        return Unmanaged.passUnretained(session.hostingController).toOpaque()
    }
}

@_cdecl("SBW_Lottie_LottieButton_Free")
public func SBW_Lottie_LottieButton_Free(_ handle: UnsafeMutableRawPointer?) {
    SBW_onMainThread {
        guard let handle = handle,
              SBW_Lottie_LottieButton_liveHandles.remove(handle) != nil else { return }
        Unmanaged<SBW_Lottie_LottieButton_Session>.fromOpaque(handle).release()
    }
}

// --- LottieSwitch ---

final class SBW_Lottie_LottieSwitch_Session {
    let hostingController: UIHostingController<LottieSwitch>

    init(animationPtr: UnsafeMutableRawPointer?) {
        let animationVal: LottieAnimation? = animationPtr.map { Unmanaged<LottieAnimation>.fromOpaque($0).takeUnretainedValue() }
        let view = LottieSwitch(animation: animationVal)
        self.hostingController = UIHostingController(rootView: view)
    }
}

var SBW_Lottie_LottieSwitch_liveHandles = Set<UnsafeMutableRawPointer>()

@_cdecl("SBW_Lottie_LottieSwitch_Create")
public func SBW_Lottie_LottieSwitch_Create(_ animationPtr: UnsafeMutableRawPointer?
) -> UnsafeMutableRawPointer? {
    return SBW_onMainThread {
        let session = SBW_Lottie_LottieSwitch_Session(
            animationPtr: animationPtr)
        let handle = Unmanaged.passRetained(session).toOpaque()
        SBW_Lottie_LottieSwitch_liveHandles.insert(handle)
        return handle
    }
}

@_cdecl("SBW_Lottie_LottieSwitch_GetViewController")
public func SBW_Lottie_LottieSwitch_GetViewController(
    _ handle: UnsafeMutableRawPointer?
) -> UnsafeMutableRawPointer? {
    return SBW_onMainThread {
        guard let handle = handle,
              SBW_Lottie_LottieSwitch_liveHandles.contains(handle) else { return nil }
        let session = Unmanaged<SBW_Lottie_LottieSwitch_Session>
            .fromOpaque(handle).takeUnretainedValue()
        return Unmanaged.passUnretained(session.hostingController).toOpaque()
    }
}

@_cdecl("SBW_Lottie_LottieSwitch_Free")
public func SBW_Lottie_LottieSwitch_Free(_ handle: UnsafeMutableRawPointer?) {
    SBW_onMainThread {
        guard let handle = handle,
              SBW_Lottie_LottieSwitch_liveHandles.remove(handle) != nil else { return }
        Unmanaged<SBW_Lottie_LottieSwitch_Session>.fromOpaque(handle).release()
    }
}

// ========================================
// BRIDGE TEMPLATE: LottieView
// ========================================
// Init: init(animation: Swift.Optional<Lottie.LottieAnimation>)
// Classification: Unsupported
// Unsupported reason: Generic type parameter
// Status: Template — complete the TODO sections
//
// @_cdecl("SBW_Lottie_LottieView_Create")
// @_cdecl("SBW_Lottie_LottieView_GetViewController")
// @_cdecl("SBW_Lottie_LottieView_Free")
//
// See: src/docs/swiftui-bridge-design.md

