<Project>
  <PropertyGroup>
    <Copyright>Copyright (c) Microsoft Corporation. Copyright (c) 2026 Justin Wojciechowski.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <LangVersion>Latest</LangVersion>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <IsPackable>false</IsPackable>
    <TestCaptureOutput>false</TestCaptureOutput>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4" PrivateAssets="all" />
  </ItemGroup>
</Project>
