// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;
using Microsoft.Extensions.Logging;

namespace BindingsGeneration.ObjC;

public static class StructsAndEnumsEmitter
{
    static readonly HashSet<string> FieldSupportedTypes = ["NSString", "nint", "nuint", "nfloat", "int", "float", "double"];

    // Structs already defined by .NET MAUI's framework bindings — skip re-emission.
    static readonly HashSet<string> SystemStructs =
    [
        "CLLocationCoordinate2D", "MKCoordinateSpan", "MKCoordinateRegion",
        "MKMapPoint", "MKMapSize", "MKMapRect",
        "CMTime", "CMTimeRange", "CMTimeMapping",
        "CGAffineTransform", "CGPoint", "CGSize", "CGRect", "CGVector",
        "UIEdgeInsets", "NSDirectionalEdgeInsets",
        "NSRange", "UIOffset", "CATransform3D",
        "SCNVector3", "SCNVector4", "SCNMatrix4",
        "MKTileOverlayPath",
    ];

    public static string? Emit(ObjCModule module, string outputDir, string resolvedNamespace, ILogger logger)
    {
        var blockTypedefs = module.Typedefs.Where(t => t.UnderlyingType.IsBlock).ToList();
        if (module.Enums.Count == 0 && module.Structs.Count == 0 && !module.Constants.Any(c => c.IsExtern) && module.Functions.Count == 0 && blockTypedefs.Count == 0)
        {
            logger.LogDebug("No enums, structs, constants, functions, or block typedefs to emit for module {ModuleName}", module.ModuleName);
            return null;
        }

        var typedefMap = ObjCTypeMapper.BuildResolvedTypedefMap(module);

        // Build set of module-local type names (classes + protocol interfaces)
        // to detect accessibility issues with delegates and functions
        var moduleLocalTypes = new HashSet<string>();
        foreach (var cls in module.Classes)
            moduleLocalTypes.Add(cls.Name);
        foreach (var proto in module.Protocols)
        {
            moduleLocalTypes.Add(proto.Name);
            moduleLocalTypes.Add($"I{proto.Name}");
        }

        // Build set of block typedef names used as parameters in protocol methods.
        // MAUI bgen auto-generates delegate types for these — emitting our own causes CS0101.
        // However, if the same typedef is also used by a C function, we must keep emitting it
        // because function signatures reference the named delegate type.
        var blockTypedefNames = new HashSet<string>(blockTypedefs.Select(t => t.Name));
        var protocolUsedBlocks = new HashSet<string>();
        foreach (var proto in module.Protocols)
            foreach (var method in proto.Methods)
                foreach (var param in method.Parameters)
                    if (blockTypedefNames.Contains(param.Type.Name))
                        protocolUsedBlocks.Add(param.Type.Name);

        // Resolve a type name through typedef chains to find the underlying block typedef.
        // e.g., AliasBlock → OriginalBlock (via typedefMap) when OriginalBlock is a block typedef.
        string? ResolveToBlockTypedef(string name)
        {
            if (blockTypedefNames.Contains(name))
                return name;
            if (typedefMap.TryGetValue(name, out var resolved) && blockTypedefNames.Contains(resolved.Name))
                return resolved.Name;
            return null;
        }

        var functionUsedBlocks = new HashSet<string>();
        foreach (var func in module.Functions)
        {
            var resolved = ResolveToBlockTypedef(func.ReturnType.Name);
            if (resolved != null) functionUsedBlocks.Add(resolved);
            foreach (var param in func.Parameters)
            {
                resolved = ResolveToBlockTypedef(param.Type.Name);
                if (resolved != null) functionUsedBlocks.Add(resolved);
            }
        }

        var bgenAutoGeneratedDelegates = new HashSet<string>(protocolUsedBlocks.Except(functionUsedBlocks));

        var sb = new StringBuilder();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using CoreAnimation;");
        sb.AppendLine("using CoreFoundation;");
        sb.AppendLine("using CoreGraphics;");
        sb.AppendLine("using CoreLocation;");
        sb.AppendLine("using CoreMedia;");
        sb.AppendLine("using Foundation;");
        sb.AppendLine("using ObjCRuntime;");
        sb.AppendLine("using UIKit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {resolvedNamespace}");
        sb.AppendLine("{");

        foreach (var enumDecl in module.Enums)
            EmitEnum(sb, enumDecl);

        foreach (var structDecl in module.Structs.Where(s => !SystemStructs.Contains(s.Name)))
            EmitStruct(sb, structDecl, typedefMap);

        foreach (var blockTypedef in blockTypedefs)
            EmitBlockDelegate(sb, blockTypedef, typedefMap, moduleLocalTypes, bgenAutoGeneratedDelegates);

        if (module.Constants.Any(c => c.IsExtern) || module.Functions.Count > 0)
            EmitConstantsClass(sb, module, typedefMap, moduleLocalTypes);

        sb.AppendLine("}");

        Directory.CreateDirectory(outputDir);
        var filePath = Path.Combine(outputDir, "StructsAndEnums.cs");
        File.WriteAllText(filePath, sb.ToString());

        logger.LogInformation("Wrote {FilePath}", filePath);
        return filePath;
    }

    static void EmitEnum(StringBuilder sb, ObjCEnumDecl enumDecl)
    {
        sb.AppendLine("    [Native]");
        if (enumDecl.IsOptions)
            sb.AppendLine("    [Flags]");

        var baseType = enumDecl.IsOptions ? "ulong" : "long";
        sb.AppendLine($"    public enum {enumDecl.Name} : {baseType}");
        sb.AppendLine("    {");

        var stripPrefix = ShouldStripPrefix(enumDecl);

        foreach (var c in enumDecl.Cases)
        {
            var caseName = stripPrefix ? c.Name[enumDecl.Name.Length..] : c.Name;
            // Prefix with _ if stripping left a digit-leading identifier (invalid C#)
            if (caseName.Length > 0 && char.IsDigit(caseName[0]))
                caseName = "_" + caseName;
            var valueStr = c.Value.HasValue ? $" = {c.Value.Value}" : "";
            sb.AppendLine($"        {caseName}{valueStr},");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    static bool ShouldStripPrefix(ObjCEnumDecl enumDecl)
    {
        if (enumDecl.Cases.Count == 0)
            return false;
        return enumDecl.Cases.All(c => c.Name.StartsWith(enumDecl.Name, StringComparison.Ordinal));
    }

    static void EmitBlockDelegate(StringBuilder sb, ObjCTypedefDecl typedef, Dictionary<string, ObjCTypeRef> typedefMap, HashSet<string> moduleLocalTypes, HashSet<string> bgenAutoGeneratedDelegates)
    {
        // Skip delegates that MAUI bgen auto-generates from protocol method block parameters.
        // With proper typedef chain resolution, these params emit as Action<>/Func<> instead
        // of the named delegate, so this is a safety net for edge cases.
        if (bgenAutoGeneratedDelegates.Contains(typedef.Name))
            return;

        var block = typedef.UnderlyingType;
        var returnType = block.BlockReturnType != null
            ? ObjCTypeMapper.MapType(block.BlockReturnType, typedefMap: typedefMap)
            : "void";

        var paramParts = new List<string>();
        var allMappedTypes = new List<string> { returnType };
        for (var i = 0; i < block.BlockParams.Count; i++)
        {
            var mappedType = ObjCTypeMapper.MapType(block.BlockParams[i], typedefMap: typedefMap);
            paramParts.Add($"{mappedType} arg{i}");
            allMappedTypes.Add(mappedType);
        }

        // Skip delegates that reference module-local types (defined in ApiDefinition.cs)
        // to avoid CS0059 accessibility errors — these are internal partial interfaces
        if (allMappedTypes.Any(t => moduleLocalTypes.Contains(t)))
            return;

        var parameters = string.Join(", ", paramParts);
        sb.AppendLine($"    public delegate {returnType} {typedef.Name}({parameters});");
        sb.AppendLine();
    }

    static void EmitStruct(StringBuilder sb, ObjCStructDecl structDecl, Dictionary<string, ObjCTypeRef> typedefMap)
    {
        sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"    public struct {structDecl.Name}");
        sb.AppendLine("    {");

        foreach (var field in structDecl.Fields)
        {
            var mappedType = ObjCTypeMapper.MapType(field.Type, typedefMap: typedefMap);
            var pascalName = ToPascalCase(field.Name);

            // Handle C fixed-size array fields (parsed from clang's "uint8_t [4]" qualType)
            if (field.Type.FixedArraySize is > 0)
            {
                var elementType = ObjCTypeMapper.MapType(new ObjCTypeRef { Name = field.Type.Name, IsPointer = field.Type.IsPointer }, typedefMap: typedefMap);
                sb.AppendLine($"        [MarshalAs(UnmanagedType.ByValArray, SizeConst = {field.Type.FixedArraySize})]");
                sb.AppendLine($"        public {elementType}[] {pascalName};");
            }
            else
            {
                sb.AppendLine($"        public {mappedType} {pascalName};");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    static void EmitConstantsClass(StringBuilder sb, ObjCModule module, Dictionary<string, ObjCTypeRef> typedefMap, HashSet<string> moduleLocalTypes)
    {
        sb.AppendLine($"    public static class {module.ModuleName}Constants");
        sb.AppendLine("    {");

        foreach (var constant in module.Constants.Where(c => c.IsExtern))
            EmitConstant(sb, constant, typedefMap);

        foreach (var function in module.Functions)
            EmitFunction(sb, function, typedefMap, moduleLocalTypes);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    static void EmitConstant(StringBuilder sb, ObjCConstantDecl constant, Dictionary<string, ObjCTypeRef> typedefMap)
    {
        var pascalName = ToPascalCase(constant.Name);

        // NSString* constants use NSString as the [Field] property type (MAUI convention),
        // not the mapped "string" type that ObjCTypeMapper returns.
        var isNSString = constant.Type is { Name: "NSString", IsPointer: true };
        var fieldType = isNSString ? "NSString" : ObjCTypeMapper.MapType(constant.Type, typedefMap: typedefMap);

        if (FieldSupportedTypes.Contains(fieldType))
        {
            sb.AppendLine($"        [Field(\"{constant.Name}\", \"__Internal\")]");
            sb.AppendLine($"        public static {fieldType} {pascalName} {{ get; }}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine($"        // TODO: {constant.Name} ({fieldType}) — [Field] not supported for this type");
            sb.AppendLine();
        }
    }

    static void EmitFunction(StringBuilder sb, ObjCFunctionDecl function, Dictionary<string, ObjCTypeRef> typedefMap, HashSet<string> moduleLocalTypes)
    {
        var returnType = ObjCTypeMapper.MapType(function.ReturnType, typedefMap: typedefMap);
        var paramTypes = function.Parameters.Select(p => ObjCTypeMapper.MapType(p.Type, typedefMap: typedefMap)).ToList();

        // Skip functions that reference module-local types (defined in ApiDefinition.cs)
        // to avoid CS0050 accessibility errors
        if (moduleLocalTypes.Contains(returnType) || paramTypes.Any(t => moduleLocalTypes.Contains(t)))
            return;

        var parameters = string.Join(", ", function.Parameters.Select((p, i) =>
            $"{paramTypes[i]} {p.Name}"));

        sb.AppendLine($"        [DllImport(\"__Internal\")]");
        sb.AppendLine($"        public static extern {returnType} {function.Name}({parameters});");
        sb.AppendLine();
    }

    static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToUpperInvariant(name[0]) + name[1..];
    }
}
