// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Swift.Runtime;

/// <summary>
/// Represents a type that can be marshaled into Swift
/// </summary>
public interface ISwiftObject : IDisposable
{
    /// <summary>
    /// Returns the TypeMetadata for this object
    /// </summary>
    /// <returns>A type metadata object for the type.</returns>
    public static abstract TypeMetadata GetTypeMetadata();

    /// <summary>
    /// Creates a new Swift object from a given payload
    /// </summary>
    public static abstract ISwiftObject NewFromPayload(IntPtr payload);

    /// <summary>
    /// Marshals this object to a Swift destination
    /// </summary>
    public int MarshalToSwift(ref Span<byte> swiftDestSpan);

    /// <summary>
    /// Gets the protocol conformance descriptor for the given type
    /// </summary>
    public static abstract ProtocolConformanceDescriptor GetProtocolConformanceDescriptor<TProtocol>() where TProtocol : class;

    /// <summary>
    /// Gets the raw Swift handle for interop marshalling.
    /// Types backed by a SafeHandle or existential container override this.
    /// Value-type structs (frozen) do not have meaningful handles and retain the default throw.
    /// </summary>
    IntPtr SwiftHandle => throw new NotSupportedException(
        $"SwiftHandle is not available for {GetType().Name}. Only heap-backed Swift types support handle extraction.");

    /// <summary>
    /// Suppresses the finalizer of this object's backing payload, if it owns one.
    /// Called by <see cref="InteropServices.SwiftMarshal.MarshalBorrowedFromSwift{T}"/> when a
    /// borrowed (+0) native reference is wrapped: the wrapper must not release a handle it does
    /// not own, so its payload <see cref="System.Runtime.InteropServices.SafeHandle"/> finalizer
    /// (which would call <c>ReleaseHandle</c> → <c>Arc.Release</c> / VWT destroy) must be suppressed.
    /// This is the non-reflective replacement for the former per-call
    /// <c>GetType().GetProperty("Payload")</c> + boxed <c>GetValue</c> lookup.
    /// The default is a no-op for types with no separately-finalizable payload — value-type
    /// (frozen) structs, existential-container-backed proxies, and SafeHandle-subclass wrappers
    /// whose own finalizer is already suppressed by the caller's <c>GC.SuppressFinalize(this)</c>.
    /// Heap-backed wrappers that hold a payload SafeHandle in a separate field override this to
    /// call <c>GC.SuppressFinalize</c> on that field.
    /// </summary>
    void SuppressPayloadFinalizer() { }
}

/// <summary>
/// Helper class for Swift invoking ISwiftObject static methods.
/// On NativeAOT (IsDynamicCodeSupported=false), uses direct static virtual dispatch.
/// On Mono JIT (IsDynamicCodeSupported=true), uses reflection to avoid
/// Mono JIT assertion failure (jit-info.c:918, mini-generic-sharing.c:2759).
/// Results are cached so reflection cost is one-time per type.
/// </summary>
public struct SwiftObjectHelper<T> where T : ISwiftObject
{
    /// <summary>
    /// Returns the TypeMetadata for T
    /// </summary>
    /// <returns>the TypeMetadata for T</returns>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetTypeMetadata is always present on ISwiftObject implementations generated by the binding generator")]
    [UnconditionalSuppressMessage("Trimming", "IL2067",
        Justification = "typeof(T) satisfies DynamicallyAccessedMembers at runtime; types preserved via TrimmerRoots.xml")]
    public static TypeMetadata GetTypeMetadata()
    {
        return TypeMetadata.Cache.GetOrAdd(typeof(T), type =>
        {
            // On NativeAOT, use direct static virtual dispatch.
            // On Mono (JIT or AOT/simulator), use reflection to avoid JIT assertion
            // (jit-info.c:918, mini-generic-sharing.c:2759).
            // The direct dispatch is in a separate method so Mono never compiles it.
            TypeMetadata metadata;
            if (SwiftRuntimeInfo.IsNativeAotRuntime)
                metadata = DirectDispatchGetTypeMetadata();
            else
                metadata = SwiftObjectReflectionHelper.InvokeGetTypeMetadata(type);

            if (!metadata.IsValid)
            {
                throw new InvalidOperationException($"Failed to retrieve type metadata for {type}");
            }

            return metadata;
        });
    }

    /// <summary>
    /// Direct static virtual dispatch — NativeAOT only.
    /// Separate method so Mono JIT never compiles this (avoids jit-info.c:918 assertion).
    /// </summary>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static TypeMetadata DirectDispatchGetTypeMetadata()
    {
        // Register NewFromPayload factory so unconstrained callers
        // (MarshalFromSwift<T>) can create instances without reflection.
        Swift.Runtime.InteropServices.NewFromPayloadDispatcher.Register(
            typeof(T), handle => (object)T.NewFromPayload(handle));
        return T.GetTypeMetadata();
    }

    /// <summary>
    /// Creates a new Swift object from a given payload
    /// </summary>
    /// <param name="payload"></param>
    /// <returns>a new ISwiftObject</returns>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "NewFromPayload is always present on ISwiftObject implementations generated by the binding generator")]
    [UnconditionalSuppressMessage("Trimming", "IL2087",
        Justification = "typeof(T) satisfies DynamicallyAccessedMembers at runtime; types preserved via TrimmerRoots.xml")]
    public static ISwiftObject NewFromPayload(IntPtr payload)
    {
        // On NativeAOT, use direct static virtual dispatch.
        if (SwiftRuntimeInfo.IsNativeAotRuntime)
            return DirectDispatchNewFromPayload(payload);

        // Mono / CoreCLR: consult the factory cache first (Finding 32). Generated module
        // initializers register a concrete-typed factory for every emitted type on all
        // runtimes, so this is a cache lookup + delegate invoke in the common case rather
        // than per-call reflection. We do not register here on Mono — the registration
        // lambda contains the static-abstract T.NewFromPayload that would assert on Mono.
        var cached = Swift.Runtime.InteropServices.NewFromPayloadDispatcher.TryCreate(typeof(T), payload);
        if (cached != null)
            return (ISwiftObject)cached;
        return SwiftObjectReflectionHelper.InvokeNewFromPayload(typeof(T), payload);
    }

    /// <summary>
    /// Direct static virtual dispatch — NativeAOT only.
    /// Separate method so Mono JIT never compiles this (avoids jit-info.c:918 assertion).
    /// </summary>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ISwiftObject DirectDispatchNewFromPayload(IntPtr payload)
    {
        Swift.Runtime.InteropServices.NewFromPayloadDispatcher.Register(
            typeof(T), handle => (object)T.NewFromPayload(handle));
        return T.NewFromPayload(payload);
    }
}

/// <summary>
/// Helper class for invoking ISwiftObject static abstract methods via reflection.
/// This avoids static virtual dispatch in generic contexts which triggers Mono JIT
/// assertion failures (jit-info.c:918, mini-generic-sharing.c:2759).
/// </summary>
internal static class SwiftObjectReflectionHelper
{
    /// <summary>
    /// Invokes GetTypeMetadata() on the concrete type via reflection.
    /// Searches for the explicit interface implementation (ISwiftObject.GetTypeMetadata).
    /// </summary>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetTypeMetadata is always present on ISwiftObject implementations; types preserved via TrimmerRoots.xml")]
    internal static TypeMetadata InvokeGetTypeMetadata([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type type)
    {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (method.ReturnType == typeof(TypeMetadata) &&
                method.GetParameters().Length == 0 &&
                method.Name.Contains("GetTypeMetadata"))
            {
                return (TypeMetadata)method.Invoke(null, null)!;
            }
        }
        return TypeMetadata.Zero;
    }

    /// <summary>
    /// Invokes NewFromPayload(IntPtr) on the concrete type via reflection.
    /// </summary>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "NewFromPayload is always present on ISwiftObject implementations; types preserved via TrimmerRoots.xml")]
    [UnconditionalSuppressMessage("Trimming", "IL2065",
        Justification = "Constructor lookup is a NativeAOT fallback for explicit interface implementations not found via GetMethods")]
    internal static ISwiftObject InvokeNewFromPayload([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods | DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type type, IntPtr payload)
    {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (method.ReturnType == typeof(ISwiftObject) &&
                method.Name.Contains("NewFromPayload") &&
                method.GetParameters().Length == 1 &&
                method.GetParameters()[0].ParameterType == typeof(IntPtr))
            {
                return (ISwiftObject)method.Invoke(null, new object[] { payload })!;
            }
        }

        // Fallback: NativeAOT may not enumerate explicit interface implementations via GetMethods.
        // All ISwiftObject types have a constructor(IntPtr) that NewFromPayload delegates to.
        var ctor = type.GetConstructor(
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            null, new[] { typeof(IntPtr) }, null);
        if (ctor != null)
            return (ISwiftObject)ctor.Invoke(new object[] { payload });

        throw new InvalidOperationException($"Failed to find NewFromPayload on {type}");
    }

    /// <summary>
    /// Invokes GetProtocolConformanceDescriptor&lt;TProtocol&gt;() on the concrete type via reflection.
    /// </summary>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetProtocolConformanceDescriptor is always present on ISwiftObject implementations; types preserved via TrimmerRoots.xml")]
    [UnconditionalSuppressMessage("Trimming", "IL2060",
        Justification = "MakeGenericMethod on GetProtocolConformanceDescriptor which is always present on ISwiftObject implementations")]
    [UnconditionalSuppressMessage("AOT", "IL3050",
        Justification = "MakeGenericMethod is used on methods that exist in all generated bindings")]
    internal static ProtocolConformanceDescriptor InvokeGetProtocolConformanceDescriptor([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type type, Type protocolType)
    {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (method.ReturnType == typeof(ProtocolConformanceDescriptor) &&
                method.Name.Contains("GetProtocolConformanceDescriptor") &&
                method.IsGenericMethodDefinition &&
                method.GetGenericArguments().Length == 1)
            {
                var closedMethod = method.MakeGenericMethod(protocolType);
                return (ProtocolConformanceDescriptor)closedMethod.Invoke(null, null)!;
            }
        }
        throw new InvalidOperationException(
            $"Failed to find GetProtocolConformanceDescriptor for {type} with protocol {protocolType}");
    }
}

public struct ProtocolConformanceDescriptorHelper<TType, TProtocol>
    where TType : ISwiftObject
    where TProtocol : class
{
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetProtocolConformanceDescriptor is always present on ISwiftObject implementations")]
    [UnconditionalSuppressMessage("Trimming", "IL2087",
        Justification = "typeof(TType) satisfies DynamicallyAccessedMembers at runtime; types preserved via TrimmerRoots.xml")]
    public static ProtocolConformanceDescriptor GetProtocolConformanceDescriptor()
    {
        // On NativeAOT, use direct static virtual dispatch.
        // On Mono (JIT or AOT/simulator), use reflection to avoid JIT assertion
        // (jit-info.c:918, mini-generic-sharing.c:2759).
        // The direct dispatch is in a separate method so Mono never compiles it.
        if (SwiftRuntimeInfo.IsNativeAotRuntime)
            return DirectDispatch();
        return SwiftObjectReflectionHelper.InvokeGetProtocolConformanceDescriptor(typeof(TType), typeof(TProtocol));
    }

    /// <summary>
    /// Direct static virtual dispatch — NativeAOT only.
    /// Separate method so Mono JIT never compiles this (avoids jit-info.c:918 assertion).
    /// </summary>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ProtocolConformanceDescriptor DirectDispatch()
    {
        // Register conformance factory so unconstrained callers
        // (ProtocolConformanceDescriptor.TryGet) can resolve without reflection.
        Swift.Runtime.InteropServices.ConformanceDispatcher.Register(
            typeof(TType), typeof(TProtocol),
            () => TType.GetProtocolConformanceDescriptor<TProtocol>());
        return TType.GetProtocolConformanceDescriptor<TProtocol>();
    }
}
