// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Swift.Runtime;

/// <summary>
/// Represents a type that can be marshaled into Swift
/// </summary>
public interface ISwiftObject : IDisposable
{
    /// <summary>
    /// Returns the TypeMetadata for this object
    /// </summary>
    /// <returns>A type metadata object for the type.</returns>
    public static abstract TypeMetadata GetTypeMetadata();

    /// <summary>
    /// Creates a new Swift object from a given payload
    /// </summary>
    public static abstract ISwiftObject NewFromPayload(IntPtr payload);

    /// <summary>
    /// Marshals this object to a Swift destination
    /// </summary>
    public int MarshalToSwift(ref Span<byte> swiftDestSpan);

    /// <summary>
    /// Gets the protocol conformance descriptor for the given type
    /// </summary>
    public static abstract ProtocolConformanceDescriptor GetProtocolConformanceDescriptor<TProtocol>() where TProtocol : class;

    /// <summary>
    /// Gets the raw Swift handle for interop marshalling.
    /// Types backed by a SafeHandle or existential container override this.
    /// Value-type structs (frozen) do not have meaningful handles and retain the default throw.
    /// </summary>
    IntPtr SwiftHandle => throw new NotSupportedException(
        $"SwiftHandle is not available for {GetType().Name}. Only heap-backed Swift types support handle extraction.");
}

/// <summary>
/// Helper class for Swift invoking ISwiftObject static methods.
/// Uses reflection instead of static virtual dispatch (T.GetTypeMetadata()) to avoid
/// Mono JIT assertion failure (jit-info.c:918, mini-generic-sharing.c:2759).
/// Results are cached so reflection cost is one-time per type.
/// </summary>
public struct SwiftObjectHelper<T> where T : ISwiftObject
{
    /// <summary>
    /// Returns the TypeMetadata for T
    /// </summary>
    /// <returns>the TypeMetadata for T</returns>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetTypeMetadata is always present on ISwiftObject implementations generated by the binding generator")]
    public static TypeMetadata GetTypeMetadata()
    {
        return TypeMetadata.Cache.GetOrAdd(typeof(T), type =>
        {
            // Avoid T.GetTypeMetadata() static virtual dispatch — it triggers
            // Mono JIT assertion failure (jit-info.c:918, condition `!ji->async`
            // and mini-generic-sharing.c:2759). Use reflection to invoke the
            // concrete type's GetTypeMetadata implementation instead.
            TypeMetadata metadata = SwiftObjectReflectionHelper.InvokeGetTypeMetadata(type);
            if (!metadata.IsValid)
            {
                throw new InvalidOperationException($"Failed to retrieve type metadata for {type}");
            }

            return metadata;
        });
    }

    /// <summary>
    /// Creates a new Swift object from a given payload
    /// </summary>
    /// <param name="payload"></param>
    /// <returns>a new ISwiftObject</returns>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "NewFromPayload is always present on ISwiftObject implementations generated by the binding generator")]
    public static ISwiftObject NewFromPayload(IntPtr payload)
    {
        // Avoid T.NewFromPayload() static virtual dispatch for Mono JIT safety.
        return SwiftObjectReflectionHelper.InvokeNewFromPayload(typeof(T), payload);
    }
}

/// <summary>
/// Helper class for invoking ISwiftObject static abstract methods via reflection.
/// This avoids static virtual dispatch in generic contexts which triggers Mono JIT
/// assertion failures (jit-info.c:918, mini-generic-sharing.c:2759).
/// </summary>
internal static class SwiftObjectReflectionHelper
{
    /// <summary>
    /// Invokes GetTypeMetadata() on the concrete type via reflection.
    /// Searches for the explicit interface implementation (ISwiftObject.GetTypeMetadata).
    /// </summary>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetTypeMetadata is always present on ISwiftObject implementations generated by the binding generator")]
    internal static TypeMetadata InvokeGetTypeMetadata(Type type)
    {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (method.ReturnType == typeof(TypeMetadata) &&
                method.GetParameters().Length == 0 &&
                method.Name.Contains("GetTypeMetadata"))
            {
                return (TypeMetadata)method.Invoke(null, null)!;
            }
        }
        return TypeMetadata.Zero;
    }

    /// <summary>
    /// Invokes NewFromPayload(IntPtr) on the concrete type via reflection.
    /// </summary>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "NewFromPayload is always present on ISwiftObject implementations generated by the binding generator")]
    internal static ISwiftObject InvokeNewFromPayload(Type type, IntPtr payload)
    {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (method.ReturnType == typeof(ISwiftObject) &&
                method.Name.Contains("NewFromPayload") &&
                method.GetParameters().Length == 1 &&
                method.GetParameters()[0].ParameterType == typeof(IntPtr))
            {
                return (ISwiftObject)method.Invoke(null, new object[] { payload })!;
            }
        }
        throw new InvalidOperationException($"Failed to find NewFromPayload on {type}");
    }

    /// <summary>
    /// Invokes GetProtocolConformanceDescriptor&lt;TProtocol&gt;() on the concrete type via reflection.
    /// </summary>
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetProtocolConformanceDescriptor is always present on ISwiftObject implementations")]
    [UnconditionalSuppressMessage("Trimming", "IL2060",
        Justification = "MakeGenericMethod on GetProtocolConformanceDescriptor which is always present on ISwiftObject implementations")]
    [UnconditionalSuppressMessage("AOT", "IL3050",
        Justification = "MakeGenericMethod is used on methods that exist in all generated bindings")]
    internal static ProtocolConformanceDescriptor InvokeGetProtocolConformanceDescriptor(Type type, Type protocolType)
    {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (method.ReturnType == typeof(ProtocolConformanceDescriptor) &&
                method.Name.Contains("GetProtocolConformanceDescriptor") &&
                method.IsGenericMethodDefinition &&
                method.GetGenericArguments().Length == 1)
            {
                var closedMethod = method.MakeGenericMethod(protocolType);
                return (ProtocolConformanceDescriptor)closedMethod.Invoke(null, null)!;
            }
        }
        throw new InvalidOperationException(
            $"Failed to find GetProtocolConformanceDescriptor for {type} with protocol {protocolType}");
    }
}

public struct ProtocolConformanceDescriptorHelper<TType, TProtocol>
    where TType : ISwiftObject
    where TProtocol : class
{
    [UnconditionalSuppressMessage("Trimming", "IL2070",
        Justification = "GetProtocolConformanceDescriptor is always present on ISwiftObject implementations")]
    public static ProtocolConformanceDescriptor GetProtocolConformanceDescriptor()
    {
        // On NativeAOT (IsDynamicCodeSupported=false), use direct static virtual dispatch.
        // On Mono JIT (IsDynamicCodeSupported=true), use reflection to avoid JIT assertion
        // (jit-info.c:918, mini-generic-sharing.c:2759).
        // The direct dispatch is in a separate method so Mono JIT never compiles it.
        if (!RuntimeFeature.IsDynamicCodeSupported)
            return DirectDispatch();
        return SwiftObjectReflectionHelper.InvokeGetProtocolConformanceDescriptor(typeof(TType), typeof(TProtocol));
    }

    /// <summary>
    /// Direct static virtual dispatch — NativeAOT only.
    /// Separate method so Mono JIT never compiles this (avoids jit-info.c:918 assertion).
    /// </summary>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ProtocolConformanceDescriptor DirectDispatch()
    {
        return TType.GetProtocolConformanceDescriptor<TProtocol>();
    }
}
