// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

namespace Swift.Runtime
{
    /// <summary>
    /// Finalizer-thread-safe cleanup helper for a Swift binding type's
    /// <see cref="SwiftSafeHandle{T}"/> payload.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The current generator does <b>not</b> emit a per-wrapper <c>~T()</c> finalizer:
    /// struct/enum wrappers rely on the <see cref="SwiftSafeHandle{T}"/> payload's own
    /// <see cref="System.Runtime.ConstrainedExecution.CriticalFinalizerObject"/> finalizer
    /// for release (identical to the class-wrapper model, where
    /// <see cref="SwiftClassHandle{T}"/>'s built-in finalizer calls Arc.Release). A second
    /// wrapper finalizer would only re-do that release and make every instance a second
    /// finalizable object. This helper is therefore <b>retained for compatibility</b> with
    /// bindings generated by earlier SDK versions that still emit
    /// <c>~T() { SwiftDispose.FinalizerCleanup(_payload); }</c>; removing it would break
    /// those already-shipped sources when only the runtime package is upgraded.
    /// </para>
    /// <para>
    /// It calls <c>Close()</c> (not <c>Dispose()</c>) on the SafeHandle so
    /// <c>_explicitDispose</c> stays false: ReleaseHandle then uses the Cdecl trampoline
    /// (<c>SBW_VWTDestroy</c>) for VWT Destroy — safe on the GC finalizer thread on both
    /// Mono and NativeAOT — and preserves the process-exit guard that skips VWT Destroy
    /// when the Swift runtime may already be torn down.
    /// </para>
    /// </remarks>
    public static class SwiftDispose
    {
        /// <summary>
        /// Releases a <see cref="SwiftSafeHandle{T}"/> payload from a finalizer thread.
        /// Triggers VWT Destroy via the Cdecl trampoline — safe on both Mono and NativeAOT.
        /// Retained for bindings generated by earlier SDK versions (see type remarks); the
        /// current generator relies on the payload SafeHandle's own critical finalizer.
        /// </summary>
        public static void FinalizerCleanup<T>(SwiftSafeHandle<T>? payload) where T : ISwiftObject
        {
            if (payload != null && !payload.IsInvalid && !payload.IsClosed)
                payload.Close();
        }
    }
}
