// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.Linq;

namespace BindingsGeneration;

/// <summary>
/// Pre-emission pass for the two case-only collision shapes in
/// <see cref="NameCollisionPolicy"/>: a type whose emitted name differs only by case from a
/// sibling Swift container that emits as a C# NAMESPACE, and two sibling members whose Swift
/// names differ only by case and therefore collapse onto one C# identifier.
///
/// <para>Swift identifiers are case-sensitive and its libraries use that freely (<c>url</c>
/// alongside <c>URL</c>); the generated C# surface has to stay unambiguous without dropping the
/// second declaration on the floor. This pass runs immediately after the nested-type rename
/// pre-pass so it reads type leaves that are already final, and before any emission so every
/// name-prediction site sees the same decision the emitter will.</para>
///
/// <para><b>Scope boundary, deliberate.</b> The member arm fires only when the two Swift names
/// project onto the SAME C# identifier — the shape that is a hard CS0102 and currently costs the
/// later declaration its binding. Two members whose projections merely differ by case
/// (<c>DocumentURL</c> vs <c>DocumentUrl</c>) are left alone: C# keeps them distinct and legal,
/// so renaming one would be churn on an API that already works. The type arm is wider — it fires
/// on any case-insensitive match — because a namespace and a type that read as the same
/// identifier are ambiguous to a reader and to case-folding tooling regardless of exact spelling,
/// and the file splitter is already having to disambiguate their output files.</para>
///
/// <para><b>Conformance is decided once, on the requirement.</b> The member arm's winner is the
/// first declaration, and a conforming type may declare the same two requirements in the opposite
/// order — so a protocol and its conformer choosing independently produce an interface
/// <c>Url</c> bound to Swift <c>url</c> and an implementation <c>Url</c> bound to Swift
/// <c>URL</c>. C# binds the implicit implementation by NAME, so that compiles and silently reads
/// the wrong storage through the interface. Protocols are therefore resolved first and conformers
/// ADOPT the requirement's name — from this run for a same-module protocol, and from the
/// persisted rename ledger (<c>&lt;renamedMembers&gt;</c>) for a protocol whose module was
/// generated by an earlier process.</para>
/// </summary>
public static class CaseOnlyCollisionPass
{
    /// <summary>
    /// Runs both arms over a module. Must be called AFTER
    /// <see cref="NameProvider.PrecomputeNestedTypeRenames"/> — the type arm compares emitted type
    /// leaves, and a nested type renamed to <c>*Info</c>/<c>*Kind</c> by that pass may be exactly
    /// what does (or no longer does) collide here. Running this first would also let the earlier
    /// pass's own taken-name set pick a leaf this pass had already claimed.
    /// </summary>
    public static void Precompute(ModuleDecl moduleDecl, ITypeDatabase typeDatabase)
    {
        ApplyNamespaceFacadeCaseRenames(moduleDecl, typeDatabase);

        // Protocols are decided FIRST, and conforming types then ADOPT the requirement's name.
        // Declaration order picks the winner within one type, and a conformer is free to declare
        // the same two requirements in the opposite order — so letting each side choose
        // independently gives an interface `Url` bound to Swift `url` and an implementation `Url`
        // bound to Swift `URL`. C# matches the implicit implementation by NAME, so that compiles
        // and silently reads the wrong storage through the interface.
        var protocolRenames = new Dictionary<SwiftTypeName, IReadOnlyDictionary<string, string>>();

        // A dependency supplied as a raw ABI/xcframework rather than a published module database
        // has no persisted ledger to read: its decisions were made by this same process, on the
        // dep's own ModuleDecl, moments ago. Seed them from the live decls so the ledger and the
        // re-parse branch reach the same answer.
        foreach (var dependencyModule in typeDatabase.GetDependencyModuleDecls())
        {
            foreach (var dependencyProtocol in dependencyModule.Protocols)
            {
                var dependencyRenames = CollectCaseRenames(dependencyProtocol);
                if (dependencyRenames.Count > 0)
                    protocolRenames[dependencyProtocol.SwiftTypeName] = dependencyRenames;
            }
        }

        foreach (var protocolDecl in moduleDecl.Protocols)
        {
            ApplyMemberCaseRenamesRecursive(protocolDecl, typeDatabase, protocolRenames);
            var requirementNames = CollectCaseRenames(protocolDecl);
            if (requirementNames.Count > 0)
                protocolRenames[protocolDecl.SwiftTypeName] = requirementNames;
        }

        foreach (var typeDecl in moduleDecl.Types)
            ApplyMemberCaseRenamesRecursive(typeDecl, typeDatabase, protocolRenames);
    }

    /// <summary>
    /// Type arm — a top-level type whose emitted leaf matches a sibling namespace facade's leaf
    /// case-insensitively is renamed with the same kind-aware suffix the nested-type scheme uses.
    /// The FACADE keeps its name: it is a namespace segment for every type declared inside it and
    /// is spelled that way in every cross-module reference, so renaming it would cascade over the
    /// whole subtree to fix a collision that only involves one sibling.
    /// </summary>
    private static void ApplyNamespaceFacadeCaseRenames(ModuleDecl moduleDecl, ITypeDatabase typeDatabase)
    {
        // Facades are top-level by construction (NamespaceFacadeDetector rejects nested ones), so
        // the collision is between module-scope siblings and this arm never needs to recurse.
        var facadeLeaves = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var candidates = new List<TypeDecl>();
        foreach (var typeDecl in moduleDecl.Types)
        {
            if (NamespaceFacadeDetector.IsNamespaceFacade(typeDecl))
                facadeLeaves.Add(GetEmittedLeaf(typeDecl, typeDatabase));
            else
                candidates.Add(typeDecl);
        }

        if (facadeLeaves.Count == 0 || candidates.Count == 0)
            return;

        // Case-insensitive so the replacement leaf cannot itself land on a sibling that differs
        // only by case — resolving one case collision by creating another would be no fix at all.
        var takenNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var typeDecl in moduleDecl.Types)
            takenNames.Add(GetEmittedLeaf(typeDecl, typeDatabase));

        foreach (var typeDecl in candidates)
        {
            var leaf = GetEmittedLeaf(typeDecl, typeDatabase);
            if (!facadeLeaves.Contains(leaf))
                continue;
            if (!typeDatabase.TryGetTypeRecord(typeDecl.SwiftTypeName, out var record))
                continue;

            var ownChildNames = new HashSet<string>(
                typeDecl.Types.Select(t => NameProvider.ToPascalCaseForTypeName(t.Name)),
                StringComparer.OrdinalIgnoreCase);
            var newLeaf = NameCollisionPolicy.ResolveTypeSideName(
                leaf,
                NameCollisionPolicy.TypeSuffixFor(typeDecl),
                n => takenNames.Contains(n) || ownChildNames.Contains(n));

            var oldCSharpName = record.CSharpTypeName.Name;
            var @namespace = record.CSharpTypeName.Namespace;
            var lastDot = oldCSharpName.LastIndexOf('.');
            var newCSharpName = lastDot >= 0
                ? oldCSharpName.Substring(0, lastDot + 1) + newLeaf
                : newLeaf;

            typeDatabase.ApplyEmissionResult(typeDecl.SwiftTypeName, new TypeEmissionResult
            {
                CSharpTypeName = CSharpTypeName.FromNamespaceAndName(@namespace, newCSharpName),
            });
            takenNames.Add(newLeaf);

            // A renamed parent is a prefix of every descendant's registered C# name, so the whole
            // subtree moves with it.
            NameProvider.CascadeTypeRename(typeDecl, oldCSharpName, newCSharpName, @namespace, typeDatabase);
        }
    }

    private static string GetEmittedLeaf(TypeDecl typeDecl, ITypeDatabase typeDatabase)
    {
        if (!typeDatabase.TryGetTypeRecord(typeDecl.SwiftTypeName, out var record))
            return NameProvider.ToPascalCaseForTypeName(typeDecl.Name);

        var name = record.CSharpTypeName.Name;
        var lastDot = name.LastIndexOf('.');
        return lastDot >= 0 ? name.Substring(lastDot + 1) : name;
    }

    private static void ApplyMemberCaseRenamesRecursive(
        TypeDecl typeDecl,
        ITypeDatabase typeDatabase,
        IReadOnlyDictionary<SwiftTypeName, IReadOnlyDictionary<string, string>> protocolRenames)
    {
        ApplyMemberCaseRenames(typeDecl, typeDatabase, ResolveAdoptedRenames(typeDecl, typeDatabase, protocolRenames));
        foreach (var nestedType in typeDecl.Types)
            ApplyMemberCaseRenamesRecursive(nestedType, typeDatabase, protocolRenames);
    }

    /// <summary>
    /// Member arm — sibling properties whose distinct Swift names project onto one C# identifier.
    /// The declaration-order first keeps the natural name (it is the one already bound today, and
    /// moving it would silently change an existing public member's type or staticness); every
    /// later distinct Swift name takes the next free numeric suffix.
    /// </summary>
    /// <param name="adopted">
    /// Requirement names this type inherits from a protocol it conforms to, keyed by Swift name.
    /// Applied unconditionally and before the local rule — including when this type declares only
    /// one side of the protocol's colliding pair and therefore has no local collision at all,
    /// which is exactly the case where choosing locally would implement the wrong interface member.
    /// </param>
    private static void ApplyMemberCaseRenames(
        TypeDecl typeDecl,
        ITypeDatabase typeDatabase,
        IReadOnlyDictionary<string, string> adopted)
    {
        var stamps = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var property in typeDecl.Properties)
        {
            if (adopted.TryGetValue(property.Name, out var adoptedName))
                stamps[property.Name] = adoptedName;
        }

        ResolveLocalCollisions(typeDecl, typeDatabase, stamps);

        // Stamp EVERY declaration carrying a renamed Swift name, including a static/instance pair
        // that shares it, so the handlers' duplicate check still compares like with like.
        foreach (var property in typeDecl.Properties)
        {
            if (!stamps.TryGetValue(property.Name, out var chosen))
                continue;
            // A protocol is both a ProtocolDecl and a TypeDecl, so it sits in the module's
            // protocol list AND its type list and this walk reaches it twice. Stamping the same
            // name twice is a no-op, but PUBLISHING it twice would book one decision as two and
            // make the ledger's count a fact about the traversal instead of about the surface.
            if (string.Equals(property.CaseDisambiguatedName, chosen, StringComparison.Ordinal))
                continue;
            property.MarkCaseDisambiguated(chosen);

            // Publish the decision to the binding report. This arm assigns numeric suffixes on
            // purpose — two Swift spellings differing only by case carry no labels or parameter
            // types to derive a semantic token from — so the record has to reach the report as its
            // OWN channel: the overload lane's records are read under a contract that forbids a
            // numeric assignment outright, and a rename that never lands anywhere is a public name
            // no artifact accounts for.
            ReportCollector.RecordCaseOnlyRenamed(
                typeDecl.Name,
                property.Name,
                NameProvider.GetPropertyBaseName(property.Name),
                chosen,
                nameof(NameCollisionScheme.CaseOnlyMemberCollision));
        }
    }

    /// <summary>
    /// The local rule: among sibling properties projecting onto one identifier, the first that is
    /// not already fixed by an adopted requirement name keeps the natural projection and the rest
    /// escalate numerically. Adds its decisions to <paramref name="stamps"/>.
    ///
    /// <para>An adopted name is immovable — it is the interface member the conformer has to
    /// implement — so a property whose OWN natural projection is that name has to move instead,
    /// even when nothing else collides with it.</para>
    /// </summary>
    private static void ResolveLocalCollisions(
        TypeDecl typeDecl,
        ITypeDatabase typeDatabase,
        Dictionary<string, string> stamps)
    {
        if (typeDecl.Properties.Count < 2)
            return;

        // A property that cannot be emitted at all should not push a sibling off its natural name.
        // Deliberately a SUBSET of MemberEmissionValidator.CanEmitProperty: the access-level and
        // type-support gates are the ones that reject a whole declaration outright, and they are
        // decidable here. The remaining gates need emission-time state this pre-pass runs before,
        // so erring toward "counts as a sibling" keeps a name reserved that nothing emits — the
        // harmless direction.
        //
        // `IsModuleInternal` is deliberately NOT consulted on a protocol: the ABI JSON carries no
        // access-control attribute on a requirement, so the parser's `@inlinable`-without-access-
        // control heuristic marks nearly every one of them internal (in this repo's own fixture
        // library, 120 of 126 protocols have every requirement flagged). The interface emitter
        // never reads the flag — a requirement is emitted onto the interface either way — so
        // honouring it here would switch the member arm off for protocols entirely.
        //
        // A supported AsyncStream property is the one exception to the type gate: its element type
        // lives in `_Concurrency`, so `HasUnsupportedPropertyType` rejects it, yet the property
        // handler emits it anyway as `IAsyncEnumerable<T>` down a dedicated path. Two of those
        // differing only by case collide on the C# surface exactly like any other pair, so they
        // belong in the sibling set — the same carve-out the nested-type collision detector makes.
        var honorsModuleInternal = typeDecl is not ProtocolDecl;
        var asyncStreamHandler = new AsyncStreamHandler(typeDatabase);
        var emittableProperties = typeDecl.Properties
            .Where(p => (!honorsModuleInternal || !p.IsModuleInternal)
                     && !p.IsSpiProtected
                     && (!MemberEmissionValidator.HasUnsupportedPropertyType(p, typeDatabase)
                         || (asyncStreamHandler.IsAsyncStream(p.SwiftTypeSpec)
                             && asyncStreamHandler.IsSupportedAsyncStream(p.SwiftTypeSpec))))
            .ToList();
        if (emittableProperties.Count < 2)
            return;

        // Group by projected C# name, keeping the DISTINCT Swift spellings in declaration order.
        // Two declarations sharing one Swift name (Swift permits a static and an instance property
        // with the same identifier) collapse to a single entry here on purpose: that is not a
        // case-only collision, and the handlers' existing duplicate-signature rule still applies.
        var groups = new List<(string Projected, List<string> SwiftNames)>();
        var groupIndex = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var property in emittableProperties)
        {
            var projected = NameProvider.GetPropertyBaseName(property.Name);
            if (!groupIndex.TryGetValue(projected, out var index))
            {
                groupIndex[projected] = index = groups.Count;
                groups.Add((projected, new List<string>()));
            }
            if (!groups[index].SwiftNames.Contains(property.Name, StringComparer.Ordinal))
                groups[index].SwiftNames.Add(property.Name);
        }

        // Names an adopted requirement has claimed. These cannot move — they name an interface
        // member — so a group landing on one has to relocate even if it is a group of one.
        var immovableNames = new HashSet<string>(stamps.Values, StringComparer.Ordinal);

        if (!groups.Any(g => g.SwiftNames.Count > 1) &&
            !groups.Any(g => immovableNames.Contains(g.Projected)))
            return;

        // Seed the taken set with every name already spoken for inside this type, so a chosen
        // `Url2` cannot land on a real `url2` property, a nested type, an enum case, or a name
        // an adopted requirement has already claimed.
        var takenNames = new HashSet<string>(groupIndex.Keys, StringComparer.Ordinal);
        foreach (var nestedType in typeDecl.Types)
            takenNames.Add(NameProvider.ToPascalCaseForTypeName(nestedType.Name));
        if (typeDecl is EnumDecl enumDecl)
        {
            foreach (var enumCase in enumDecl.Cases)
                takenNames.Add(NameProvider.ToPascalCase(enumCase.Name));
        }
        foreach (var adoptedName in immovableNames)
            takenNames.Add(adoptedName);

        foreach (var (projected, swiftNames) in groups)
        {
            // The first name not already fixed by an adopted requirement keeps `projected`
            // untouched — no stamp needed for the winner — unless an adopted name already IS
            // `projected`, in which case every name in the group has to escalate.
            var naturalAvailable = !immovableNames.Contains(projected);
            foreach (var swiftName in swiftNames)
            {
                if (stamps.ContainsKey(swiftName))
                    continue;
                if (naturalAvailable)
                {
                    naturalAvailable = false;
                    continue;
                }
                var chosen = NameCollisionPolicy.ResolveCaseOnlyMemberName(projected, takenNames.Contains);
                takenNames.Add(chosen);
                stamps[swiftName] = chosen;
            }
        }
    }

    /// <summary>
    /// The case-only names this type chose for its own properties, keyed by Swift name. This is
    /// the requirement-side view a conforming type adopts.
    /// </summary>
    private static IReadOnlyDictionary<string, string> CollectCaseRenames(TypeDecl typeDecl)
    {
        Dictionary<string, string>? renames = null;
        foreach (var property in typeDecl.Properties)
        {
            if (property.CaseDisambiguatedName is not { } chosen)
                continue;
            renames ??= new Dictionary<string, string>(StringComparer.Ordinal);
            renames[property.Name] = chosen;
        }
        return renames ?? EmptyRenames;
    }

    /// <summary>
    /// The requirement names <paramref name="typeDecl"/> inherits from the protocols it conforms
    /// to, read from whichever of three sources holds the protocol's decisions. A same-module
    /// protocol is read from this run's map, filled in protocols-first order. A protocol from a
    /// dependency supplied as raw ABI is ALSO in that map — <see cref="Precompute"/> seeds it from
    /// the dependency's live decls, because this same process made those decisions moments ago and
    /// nothing persisted them. Only a dependency consumed as a published module database falls
    /// through to its persisted rename ledger, the sole surviving record of a decision made by an
    /// earlier generator run.
    /// </summary>
    private static IReadOnlyDictionary<string, string> ResolveAdoptedRenames(
        TypeDecl typeDecl,
        ITypeDatabase typeDatabase,
        IReadOnlyDictionary<SwiftTypeName, IReadOnlyDictionary<string, string>> protocolRenames)
    {
        var conformances = typeDecl switch
        {
            ClassDecl classDecl => classDecl.Conformances,
            StructDecl structDecl => structDecl.Conformances,
            EnumDecl enumDecl => enumDecl.Conformances,
            _ => null,
        };
        if (conformances is null || conformances.Count == 0)
            return EmptyRenames;

        Dictionary<string, string>? adopted = null;
        foreach (var conformance in conformances)
        {
            var fromProtocol = LookupProtocolRenames(conformance.Protocol, typeDatabase, protocolRenames);
            if (fromProtocol is null)
                continue;
            foreach (var (swiftName, csharpName) in fromProtocol)
            {
                adopted ??= new Dictionary<string, string>(StringComparer.Ordinal);
                // First conformance wins. Two protocols that give one requirement different names
                // are in conflict whatever this type does; keeping the first at least leaves that
                // interface's members bound to the storage it named.
                if (!adopted.ContainsKey(swiftName))
                    adopted[swiftName] = csharpName;
            }
        }
        return adopted ?? EmptyRenames;
    }

    private static IReadOnlyDictionary<string, string>? LookupProtocolRenames(
        SwiftTypeName protocolName,
        ITypeDatabase typeDatabase,
        IReadOnlyDictionary<SwiftTypeName, IReadOnlyDictionary<string, string>> protocolRenames)
    {
        if (protocolRenames.TryGetValue(protocolName, out var sameModule))
            return sameModule;

        if (!typeDatabase.TryGetTypeRecord(protocolName, out var record) ||
            record.RenamedMembers is not { Count: > 0 } ledger)
            return null;

        Dictionary<string, string>? fromLedger = null;
        foreach (var entry in ledger)
        {
            if (entry.Kind != RenamedMemberKind.Property ||
                entry.Scheme != nameof(NameCollisionScheme.CaseOnlyMemberCollision))
                continue;
            fromLedger ??= new Dictionary<string, string>(StringComparer.Ordinal);
            fromLedger[entry.SwiftName] = entry.CSharpName;
        }
        return fromLedger;
    }

    private static readonly IReadOnlyDictionary<string, string> EmptyRenames =
        new Dictionary<string, string>(StringComparer.Ordinal);
}
