// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Text;
using System.Xml;
using Microsoft.Extensions.Logging;

namespace BindingsGeneration
{
    /// <summary>
    /// Emits an ILLink trimmer descriptor (<c>ILLink.Descriptors.xml</c>) listing every
    /// open-generic ISwiftObject type definition emitted for a module so ILC (NativeAOT)
    /// preserves its reflection metadata across trimming.
    ///
    /// The eager-cctor pattern emitted by the type handlers
    /// (see <c>TypeHandlerHelpers.WriteStaticConstructor</c> etc.) gives ILC a *call edge*
    /// for the closed instantiations it can statically see, but it does NOT preserve the
    /// reflection metadata or factory-method bookkeeping needed by other closed
    /// instantiations resolved at runtime through <c>SwiftObjectHelper&lt;T&gt;</c> and
    /// <c>SwiftObjectReflectionHelper</c>. Mirroring the runtime's own descriptor for
    /// <c>Swift.SwiftArray`1</c> (see <c>src/Swift.Runtime/src/ILLink.Descriptors.xml</c>),
    /// we list every emitted open generic with <c>preserve="all"</c>. Codex r1 HIGH for
    /// RC-AOT flagged this descriptor as load-bearing alongside the cctor.
    ///
    /// The consumer csproj must root this file via <c>TrimmerRootDescriptor</c>; the
    /// embedded-resource entry is for downstream consumers that pick up the binding
    /// nupkg, since ILC does not auto-discover descriptors embedded in referenced
    /// assemblies. <see cref="BindingProjectEmitter"/> emits both items together.
    /// </summary>
    public static class TrimmerDescriptorEmitter
    {
        public const string FileName = "ILLink.Descriptors.xml";

        /// <summary>
        /// Writes <c>ILLink.Descriptors.xml</c> into <paramref name="outputDirectory"/>
        /// rooting every open-generic ISwiftObject in <paramref name="context"/> under the
        /// assembly produced for <paramref name="assemblyName"/>. Returns true when the
        /// file was written; returns false (and writes nothing) when no open-generic
        /// types were emitted, so the csproj can stay free of dead descriptor wiring.
        /// </summary>
        public static bool Emit(
            ModuleEmissionContext context,
            string outputDirectory,
            string assemblyName,
            ILogger logger)
        {
            if (context == null) throw new ArgumentNullException(nameof(context));
            if (string.IsNullOrEmpty(outputDirectory)) throw new ArgumentNullException(nameof(outputDirectory));
            if (string.IsNullOrEmpty(assemblyName)) throw new ArgumentNullException(nameof(assemblyName));

            var openGenerics = context.EmittedOpenGenericISwiftObjectTypes;
            if (openGenerics.Count == 0)
                return false;

            var resolvedNamespace = context.ResolvedNamespace;
            if (string.IsNullOrEmpty(resolvedNamespace))
                throw new InvalidOperationException(
                    "ModuleEmissionContext.ResolvedNamespace must be set before emitting the ILLink descriptor.");

            var path = Path.Combine(outputDirectory, FileName);

            var settings = new XmlWriterSettings
            {
                Indent = true,
                IndentChars = "  ",
                NewLineChars = "\n",
                OmitXmlDeclaration = true,
                Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            };

            var sb = new StringBuilder();
            using (var writer = XmlWriter.Create(sb, settings))
            {
                writer.WriteComment(
                    " Auto-generated by TrimmerDescriptorEmitter. Roots every open-generic " +
                    "ISwiftObject type definition for ILC so the eager-cctor metadata path " +
                    "in each generated wrapper survives trimming on NativeAOT. ");
                writer.WriteStartElement("linker");
                writer.WriteStartElement("assembly");
                writer.WriteAttributeString("fullname", assemblyName);

                foreach (var entry in openGenerics)
                {
                    // ModuleEmissionContext keys nested open generics in C# source syntax
                    // (e.g. "Outer.Inner"); ILLink reads `fullname` as a CLR metadata type
                    // identifier which uses '/' between a nesting outer and its nested
                    // type. Namespaces still use '.', so only the entry-key segment is
                    // converted. Top-level entries (no nesting) are unaffected.
                    var metadataKey = entry.Key.Replace('.', '/');
                    var typeFullName = $"{resolvedNamespace}.{metadataKey}`{entry.Value}";
                    writer.WriteStartElement("type");
                    writer.WriteAttributeString("fullname", typeFullName);
                    writer.WriteAttributeString("preserve", "all");
                    writer.WriteEndElement();
                }

                writer.WriteEndElement(); // assembly
                writer.WriteEndElement(); // linker
            }

            File.WriteAllText(path, sb.ToString() + "\n");
            logger.LogInformation(
                "Wrote ILLink trimmer descriptor with {Count} open-generic ISwiftObject root(s) to {Path}",
                openGenerics.Count, path);
            return true;
        }
    }
}
