// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

#nullable enable

using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace BindingsGeneration.Tests;

/// <summary>
/// The <c>{namespace}.api-surface.md</c> member table exists so a consumer-facing README can derive
/// its member list from what the generator actually emitted — the API manifest — rather than a
/// hand-authored list transcribed from Swift source that drifts. These tests assert the doc is a
/// faithful, lossless view of the manifest: every manifest signature appears in the table exactly
/// once, grouped under its containing type, and nothing else does.
/// </summary>
public class ApiSurfaceDocEmitterTests
{
    /// <summary>
    /// Parses the rendered Markdown back into the set of full member signatures it lists, so a test
    /// can compare the doc against the manifest keys it was rendered from. Reconstructs each key as
    /// <c>{heading}.{member}</c> (or just <c>{member}</c> under the free-functions heading).
    /// </summary>
    private static HashSet<string> ParseListedSignatures(string markdown)
    {
        var result = new HashSet<string>();
        string? heading = null;
        foreach (var raw in markdown.Split('\n'))
        {
            var line = raw.TrimEnd('\r');
            if (line.StartsWith("## "))
            {
                heading = line.Substring(3).Trim();
                continue;
            }
            if (line.StartsWith("- `") && line.EndsWith("`"))
            {
                var member = line.Substring(3, line.Length - 4);
                Assert.NotNull(heading);
                result.Add(heading == ApiSurfaceDocEmitter.FreeFunctionsHeading
                    ? member
                    : $"{heading}.{member}");
            }
        }
        return result;
    }

    [Fact]
    public void SurfaceDoc_MemberTable_MatchesManifestExactly()
    {
        // Drive the real manifest accumulator the doc derives from, then assert the doc lists
        // exactly the manifest's signatures — no drift in either direction.
        var ctx = new ModuleEmissionContext();
        ctx.RecordApiManifestEntry("PaymentSheet.Configuration.SetMerchant(string)", "sym_a");
        ctx.RecordApiManifestEntry("PaymentSheet.Configuration.SetAmount(int)", "sym_b");
        ctx.RecordApiManifestEntry("PaymentSheet.Present(nint)", "sym_c");
        ctx.RecordApiManifestEntry("ConfigureGlobalDefaults()", "sym_d");
        ctx.RecordApiManifestEntry("MakeClient(string,int)", "sym_e");

        var manifestKeys = ctx.ApiManifestEntries.Keys.ToHashSet();
        var markdown = ApiSurfaceDocEmitter.Render("Stripe", ctx.ApiManifestEntries.Keys);
        var listed = ParseListedSignatures(markdown);

        Assert.Equal(manifestKeys, listed);
    }

    [Fact]
    public void SurfaceDoc_GroupsMembersUnderContainingType()
    {
        var markdown = ApiSurfaceDocEmitter.Render("Stripe", new[]
        {
            "PaymentSheet.Configuration.SetMerchant(string)",
            "PaymentSheet.Configuration.SetAmount(int)",
            "TopLevelHelper(int)",
        });

        // The nested-type members are grouped under their dotted containing-type heading, and the
        // member bullet carries only the member signature (the parent path lives in the heading).
        Assert.Contains("## PaymentSheet.Configuration\n", markdown);
        Assert.Contains("- `SetMerchant(string)`", markdown);
        Assert.DoesNotContain("- `PaymentSheet.Configuration.SetMerchant(string)`", markdown);
        // Free functions land under the sentinel heading.
        Assert.Contains($"## {ApiSurfaceDocEmitter.FreeFunctionsHeading}\n", markdown);
        Assert.Contains("- `TopLevelHelper(int)`", markdown);
    }

    [Fact]
    public void SurfaceDoc_StatesItIsAutoGeneratedAndNotHandEdited()
    {
        // The header must warn against hand-editing (otherwise a maintainer edits it and reintroduces
        // the very drift the doc exists to prevent) and must state its scope, including how to read a
        // bullet that carries no parameter list.
        var markdown = ApiSurfaceDocEmitter.Render("Stripe", new[] { "Foo()" });

        Assert.Contains("AUTO-GENERATED", markdown);
        Assert.Contains("do not hand-edit", markdown);
        Assert.Contains("properties and subscripts", markdown);
        Assert.Contains("without a parameter list is a property", markdown);
    }

    [Fact]
    public void SurfaceDoc_ListsPropertiesAndSubscripts()
    {
        // A property key carries no parameter list and a subscript key is an indexer; neither may be
        // rendered as a zero-argument method, which is what appending a bare "()" would produce.
        var markdown = ApiSurfaceDocEmitter.Render("Stripe", new[]
        {
            "PaymentSheet.Amount",
            "PaymentSheet.this[int]",
            "PaymentSheet.Present(nint)",
        });

        Assert.Contains("- `Amount`\n", markdown);
        Assert.Contains("- `this[int]`\n", markdown);
        Assert.DoesNotContain("- `Amount()`", markdown);
        Assert.DoesNotContain("- `this[int]()`", markdown);
        // All three group under the containing type, not the free-function sentinel.
        Assert.DoesNotContain(ApiSurfaceDocEmitter.FreeFunctionsHeading, markdown);
    }

    [Fact]
    public void SurfaceDoc_SubscriptWithDottedIndexType_KeepsWholeIndexList()
    {
        // The member↔parent split must happen before the index list, or a namespace-qualified index
        // type's dot is mistaken for the parent separator and the heading swallows the member.
        var markdown = ApiSurfaceDocEmitter.Render("M", new[]
        {
            "Widget.this[global::System.IntPtr]",
        });

        Assert.Contains("## Widget\n", markdown);
        Assert.Contains("- `this[global::System.IntPtr]`\n", markdown);
    }

    [Fact]
    public void Emit_ZeroMembers_DeletesStaleSurfaceDoc()
    {
        // A prior build wrote a surface doc; this build records zero members. The stale doc must be
        // removed, not left behind — a doc that outlives the members it listed is the drift the
        // artifact exists to prevent.
        var dir = Path.Combine(Path.GetTempPath(), "api-surface-stale-" + System.Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var stalePath = Path.Combine(dir, "Stripe.api-surface.md");
            File.WriteAllText(stalePath, "# Stripe — public API surface\n\n## Old\n- `Gone()`\n");

            var emptyCtx = new ModuleEmissionContext();
            var result = ApiSurfaceDocEmitter.Emit("Stripe", "Stripe", emptyCtx, dir, new NullLogger<ApiSurfaceDocEmitterTests>());

            Assert.Null(result);
            Assert.False(File.Exists(stalePath));
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void Emit_WithMembers_WritesSurfaceDoc()
    {
        var dir = Path.Combine(Path.GetTempPath(), "api-surface-write-" + System.Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var ctx = new ModuleEmissionContext();
            ctx.RecordApiManifestEntry("PaymentSheet.Present(nint)", "sym_a");

            var result = ApiSurfaceDocEmitter.Emit("Stripe", "Stripe", ctx, dir, new NullLogger<ApiSurfaceDocEmitterTests>());

            var expectedPath = Path.Combine(dir, "Stripe.api-surface.md");
            Assert.Equal(expectedPath, result);
            Assert.True(File.Exists(expectedPath));
            Assert.Contains("- `Present(nint)`", File.ReadAllText(expectedPath));
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void SurfaceDoc_ParamTypeWithParentheses_SplitsOnFirstParen()
    {
        // A projected parameter type can itself contain a '(' (e.g. a function-pointer type). The
        // name↔params split keys off the FIRST '(', so the containing type and member name survive.
        var markdown = ApiSurfaceDocEmitter.Render("M", new[]
        {
            "Widget.Configure(delegate*<int,void>)",
        });

        Assert.Contains("## Widget\n", markdown);
        Assert.Contains("- `Configure(delegate*<int,void>)`", markdown);
    }
}
