// Copyright (c) Microsoft Corporation.
// Copyright (c) 2026 Justin Wojciechowski.
// Licensed under the MIT License.

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace Swift.Runtime.InteropServices;

#nullable enable

/// <summary>
/// Represents a class for marshaling data to and from Swift
/// </summary>
public static class SwiftMarshal
{
    /// <summary>
    /// Marshals a value to a Swift destination
    /// </summary>
    /// <typeparam name="T">The type of the value being marshaled</typeparam>
    /// <param name="value">The value to marshal</param>
    /// <param name="swiftDestSpan">the destination for marshaling</param>
    /// <returns>the number of bytes written to the destination</returns>
    public static int MarshalToSwift<T>(T value, ref Span<byte> swiftDestSpan)
    {
        if (value is ISwiftObject swiftValue)
        {
            return swiftValue.MarshalToSwift(ref swiftDestSpan);
        }

        var type = typeof(T);
        if ((type.IsPrimitive || typeof(nint).IsAssignableFrom(type) || typeof(nuint).IsAssignableFrom(type)) && !typeof(char).IsAssignableFrom(type))
        {
            unsafe
            {
                int size = Unsafe.SizeOf<T>();
                if (size > swiftDestSpan.Length)
                {
                    throw new ArgumentException($"Span size does not match type size, Expected: {size}, Actual: {swiftDestSpan.Length}");
                }
                fixed (void* swiftDest = swiftDestSpan)
                {
                    MarshalPrimitiveToSwift(value, swiftDest);
                    return size;
                }
            }
        }

        // Handle tuple types (ValueTuple<T1, T2, ...>)
        // Note: Tuple marshalling uses reflection internally, but this is intentional
        // for the generic runtime path. Generated bindings use inline code instead.
#pragma warning disable IL3050, IL2026, IL2087, IL2091 // Suppressing trimming/AOT warnings for tuple marshalling
        if (TypeMetadata.IsValueTupleType(type))
        {
            return MarshalTupleToSwift(value, type, ref swiftDestSpan);
        }
#pragma warning restore IL3050, IL2026, IL2087, IL2091

        // Handle delegate types (closures)
        if (typeof(Delegate).IsAssignableFrom(type))
        {
            unsafe
            {
                if (value is Delegate delegateValue)
                {
                    // For now, only support @convention(c) closures which are just function pointers
                    // Escaping closures require a thunk which is generated by the emitter
                    var closureData = SwiftClosureMarshaller.CreateConventionCClosure(delegateValue);

                    // Write the closure data (function pointer + context) to the destination
                    int closureSize = sizeof(SwiftClosureData);
                    if (closureSize > swiftDestSpan.Length)
                    {
                        throw new ArgumentException($"Span size does not match closure size, Expected: {closureSize}, Actual: {swiftDestSpan.Length}");
                    }
                    fixed (void* swiftDest = swiftDestSpan)
                    {
                        *(SwiftClosureData*)swiftDest = closureData;
                        return closureSize;
                    }
                }
            }
        }

        // Handle existential containers (Swift protocol types like 'any Protocol')
        if (typeof(IExistentialContainer).IsAssignableFrom(type))
        {
            if (value is IExistentialContainer container)
            {
                int containerSize = container.SizeOf;
                if (containerSize > swiftDestSpan.Length)
                {
                    throw new ArgumentException($"Span size does not match container size, Expected: {containerSize}, Actual: {swiftDestSpan.Length}");
                }
                unsafe
                {
                    fixed (void* swiftDest = swiftDestSpan)
                    {
                        container.CopyTo((IntPtr)swiftDest);
                        return containerSize;
                    }
                }
            }
        }

        throw new NotSupportedException($"Cannot marshal type {type} to Swift");
    }

    /// <summary>
    /// Marshals a primitive value to a Swift destination
    /// </summary>
    /// <typeparam name="T">the type of the primitive</typeparam>
    /// <param name="value">The value to marshal</param>
    /// <param name="swiftDest">where in memory to marshal it</param>
    /// <returns>the resulting pointer for passing to a Swift method.</returns>
    /// <exception cref="NotSupportedException"></exception>
    static unsafe void MarshalPrimitiveToSwift<T>(T value, void* swiftDest)
    {
        if (value is bool boolValue)
        {
            *((byte*)swiftDest) = (byte)(boolValue ? 1 : 0);
        }
        else if (value is byte byteValue)
        {
            *((byte*)swiftDest) = byteValue;
        }
        else if (value is sbyte sbyteValue)
        {
            *((sbyte*)swiftDest) = sbyteValue;
        }
        else if (value is short shortValue)
        {
            *((short*)swiftDest) = shortValue;
        }
        else if (value is ushort ushortValue)
        {
            *((ushort*)swiftDest) = ushortValue;
        }
        else if (value is int intValue)
        {
            *((int*)swiftDest) = intValue;
        }
        else if (value is uint uintValue)
        {
            *((uint*)swiftDest) = uintValue;
        }
        else if (value is long longValue)
        {
            *((long*)swiftDest) = longValue;
        }
        else if (value is ulong ulongValue)
        {
            *((ulong*)swiftDest) = ulongValue;
        }
        else if (value is float floatValue)
        {
            *((float*)swiftDest) = floatValue;
        }
        else if (value is double doubleValue)
        {
            *((double*)swiftDest) = doubleValue;
        }
        else if (value is nint nintValue)
        {
            *((nint*)swiftDest) = nintValue;
        }
        else if (value is nuint nuintValue)
        {
            *((nuint*)swiftDest) = nuintValue;
        }
        else
        {
            throw new NotSupportedException($"Cannot marshal type {typeof(T)} to Swift");
        }
    }

    /// <summary>
    /// Marshals a value from a Swift source.
    /// </summary>
    /// <typeparam name="T">The type of the expected value</typeparam>
    /// <param name="swiftSource">Memory to read from</param>
    /// <returns>The C# type created by marshaling</returns>
    /// <exception cref="NotSupportedException"></exception>
    public static T MarshalFromSwift<T>(IntPtr swiftSource)
    {
        if (typeof(ISwiftObject).IsAssignableFrom(typeof(T)))
        {
            var helper = typeof(SwiftObjectHelper<>).MakeGenericType(typeof(T));
            return (T)helper.GetMethod("NewFromPayload")!.Invoke(null, new object[] { swiftSource })!;
        }
        var type = typeof(T);
        if (type.IsPrimitive)
        {
            unsafe
            {
                return MarshalPrimitiveFromSwift<T>(swiftSource);
            }
        }

        // Handle tuple types (ValueTuple<T1, T2, ...>)
        // Note: Tuple marshalling uses reflection internally, but this is intentional
        // for the generic runtime path. Generated bindings use inline code instead.
#pragma warning disable IL3050, IL2026, IL2091 // Suppressing trimming/AOT warnings for tuple marshalling
        if (TypeMetadata.IsValueTupleType(type))
        {
            return MarshalTupleFromSwift<T>(swiftSource);
        }
#pragma warning restore IL3050, IL2026, IL2091

        // Handle delegate types (closures) - Phase 3 support
        if (typeof(Delegate).IsAssignableFrom(typeof(T)))
        {
            // Read the Swift closure data (function pointer + context)
            unsafe
            {
                var closureData = *(SwiftClosureData*)swiftSource;

                // Receiving Swift closures as C# delegates requires generated invoker code
                // because we need to know the exact signature to call the Swift function
                // with the proper calling convention (context in register).
                // The generated bindings should create SwiftEscapingClosure<TDelegate> wrappers
                // with proper invoker delegates.
                throw new NotSupportedException(
                    $"Receiving Swift closures as C# delegates requires generated invoker code. " +
                    $"The closure data is at address 0x{swiftSource:X}, " +
                    $"function pointer: 0x{closureData.FunctionPointer:X}, " +
                    $"context: 0x{closureData.Context:X}. Type: {typeof(T)}");
            }
        }

        // Existential containers cannot be directly marshalled from Swift to C# as a generic delegate
        // because the concrete type is not known at compile time. The generated bindings should
        // handle existential types with explicit container types.

#if IOS || TVOS || MACCATALYST || MACOS
        // Defense-in-depth: if T is an NSObject subclass (ObjC-bridged type like UIImage, NSImage),
        // read the object pointer from the Swift memory and wrap with GetNSObject<T>.
        // The generated bindings should emit GetNSObject directly, but this catches edge cases
        // where the TypeDatabase didn't recognize the type as ObjC-bridged.
        if (typeof(Foundation.NSObject).IsAssignableFrom(type))
        {
            var objPtr = Marshal.ReadIntPtr(swiftSource);
            return (T)(object)ObjCRuntime.Runtime.GetNSObject(objPtr)!;
        }
#endif

        throw new NotSupportedException($"Cannot marshal type {type} from Swift");
    }

    /// <summary>
    /// Marshals a primitive value from a Swift source
    /// </summary>
    /// <typeparam name="T">The type of the value to marshal</typeparam>
    /// <param name="swiftSource">Memory to read from</param>
    /// <returns>The marshaled type</returns>
    /// <exception cref="NotSupportedException"></exception>
    public static unsafe T MarshalPrimitiveFromSwift<T>(IntPtr swiftSource)
    {
        if (typeof(T) == typeof(bool))
        {
            return (T)(object)(((*(byte*)swiftSource) & 1) != 0);
        }
        else if (typeof(T) == typeof(byte))
        {
            return (T)(object)(*(byte*)swiftSource);
        }
        else if (typeof(T) == typeof(sbyte))
        {
            return (T)(object)(*(sbyte*)swiftSource);
        }
        else if (typeof(T) == typeof(short))
        {
            return (T)(object)(*(short*)swiftSource);
        }
        else if (typeof(T) == typeof(ushort))
        {
            return (T)(object)(*(ushort*)swiftSource);
        }
        else if (typeof(T) == typeof(int))
        {
            return (T)(object)(*(int*)swiftSource);
        }
        else if (typeof(T) == typeof(uint))
        {
            return (T)(object)(*(uint*)swiftSource);
        }
        else if (typeof(T) == typeof(long))
        {
            return (T)(object)(*(long*)swiftSource);
        }
        else if (typeof(T) == typeof(ulong))
        {
            return (T)(object)(*(ulong*)swiftSource);
        }
        else if (typeof(T) == typeof(float))
        {
            return (T)(object)(*(float*)swiftSource);
        }
        else if (typeof(T) == typeof(double))
        {
            return (T)(object)(*(double*)swiftSource);
        }
        else if (typeof(T) == typeof(nint))
        {
            return (T)(object)(*(nint*)swiftSource);
        }
        else if (typeof(T) == typeof(nuint))
        {
            return (T)(object)(*(nuint*)swiftSource);
        }
        else
        {
            throw new NotSupportedException($"Cannot marshal type {typeof(T)} from Swift");
        }
    }

    /// <summary>
    /// Marshals a C# ValueTuple to Swift memory.
    /// Uses direct unsafe memory access for primitive types to avoid reflection overhead.
    /// </summary>
    /// <typeparam name="T">The ValueTuple type.</typeparam>
    /// <param name="value">The tuple value.</param>
    /// <param name="tupleType">The tuple type.</param>
    /// <param name="swiftDestSpan">The destination span.</param>
    /// <returns>The number of bytes written.</returns>
    [RequiresDynamicCode("Tuple marshalling uses reflection for non-primitive element types")]
    [RequiresUnreferencedCode("Tuple marshalling requires access to ValueTuple fields")]
    private static unsafe int MarshalTupleToSwift<T>(T value, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] Type tupleType, ref Span<byte> swiftDestSpan)
    {
        var elementTypes = TypeMetadata.GetTupleElementTypes(tupleType);
        var elementCount = elementTypes.Length;

        // Get tuple metadata to determine layout
        if (!TypeMetadata.TryGetTypeMetadata<T>(out var tupleMetadata))
            throw new NotSupportedException($"Cannot get tuple metadata for {tupleType.Name}");

        var tupleSize = (int)tupleMetadata.Value.Size;
        if (tupleSize > swiftDestSpan.Length)
            throw new ArgumentException($"Span size does not match tuple size, Expected: {tupleSize}, Actual: {swiftDestSpan.Length}");

        // Get field values using ValueTuple's Item1, Item2, etc. fields
        var fields = GetTupleFields(tupleType);

        fixed (byte* destPtr = swiftDestSpan)
        {
            // Calculate offsets and marshal each element
            int currentOffset = 0;
            for (int i = 0; i < elementCount; i++)
            {
                var elementType = elementTypes[i];
                var elementValue = fields[i].GetValue(value);

                // Get element metadata to determine alignment
                var elementMetadata = GetTypeMetadataForType(elementType);
                var elementAlignment = elementMetadata.Alignment;
                var elementSize = (int)elementMetadata.Size;

                // Align the offset
                currentOffset = AlignOffset(currentOffset, elementAlignment);

                // Marshal the element directly using unsafe pointers
                MarshalElementToSwiftUnsafe(elementValue, elementType, destPtr + currentOffset);

                currentOffset += elementSize;
            }
        }

        return tupleSize;
    }

    /// <summary>
    /// Marshals a Swift tuple to a C# ValueTuple.
    /// Uses direct unsafe memory access for primitive types to avoid reflection overhead.
    /// </summary>
    /// <typeparam name="T">The ValueTuple type.</typeparam>
    /// <param name="swiftSource">The Swift memory source.</param>
    /// <returns>The marshalled ValueTuple.</returns>
    [RequiresDynamicCode("Tuple marshalling uses reflection for non-primitive element types")]
    [RequiresUnreferencedCode("Tuple marshalling requires access to ValueTuple constructors")]
    private static unsafe T MarshalTupleFromSwift<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicFields)] T>(IntPtr swiftSource)
    {
        var tupleType = typeof(T);
        var elementTypes = TypeMetadata.GetTupleElementTypes(tupleType);
        var elementCount = elementTypes.Length;

        // Get element values
        var elementValues = new object?[elementCount];
        int currentOffset = 0;

        for (int i = 0; i < elementCount; i++)
        {
            var elementType = elementTypes[i];

            // Get element metadata to determine alignment and size
            var elementMetadata = GetTypeMetadataForType(elementType);
            var elementAlignment = elementMetadata.Alignment;
            var elementSize = (int)elementMetadata.Size;

            // Align the offset
            currentOffset = AlignOffset(currentOffset, elementAlignment);

            // Marshal the element from Swift
            var elementPtr = IntPtr.Add(swiftSource, currentOffset);
            elementValues[i] = MarshalElementFromSwiftUnsafe(elementPtr, elementType);

            currentOffset += elementSize;
        }

        // Create the ValueTuple using the constructor
        return CreateValueTuple<T>(tupleType, elementValues);
    }

    /// <summary>
    /// Gets the fields of a ValueTuple in order (Item1, Item2, etc.).
    /// </summary>
    [RequiresUnreferencedCode("ValueTuple field access")]
    private static FieldInfo[] GetTupleFields([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] Type tupleType)
    {
        var elementCount = tupleType.GetGenericArguments().Length;
        var fields = new FieldInfo[elementCount];

        for (int i = 0; i < elementCount; i++)
        {
            var fieldName = $"Item{i + 1}";
            fields[i] = tupleType.GetField(fieldName)
                ?? throw new InvalidOperationException($"Could not find field {fieldName} on {tupleType.Name}");
        }

        return fields;
    }

    /// <summary>
    /// Gets TypeMetadata for a runtime Type.
    /// </summary>
    [RequiresDynamicCode("Type metadata lookup uses reflection")]
    private static TypeMetadata GetTypeMetadataForType(Type type)
    {
        // Use reflection to call the generic TryGetTypeMetadata<T>
        var tryGetMethod = typeof(TypeMetadata).GetMethod(nameof(TypeMetadata.TryGetTypeMetadata), BindingFlags.Public | BindingFlags.Static)!;
        var genericMethod = tryGetMethod.MakeGenericMethod(type);

        var args = new object?[] { null };
        var success = (bool)genericMethod.Invoke(null, args)!;

        if (!success)
            throw new NotSupportedException($"Cannot get type metadata for {type.Name}");

        return ((TypeMetadata?)args[0])!.Value;
    }

    /// <summary>
    /// Aligns an offset to the given alignment.
    /// </summary>
    private static int AlignOffset(int offset, int alignment)
    {
        var remainder = offset % alignment;
        return remainder == 0 ? offset : offset + (alignment - remainder);
    }

    /// <summary>
    /// Marshals a single element value to Swift memory using direct pointer access.
    /// </summary>
    [RequiresDynamicCode("Non-primitive element marshalling uses reflection")]
    private static unsafe void MarshalElementToSwiftUnsafe(object? value, Type elementType, byte* dest)
    {
        if (value == null)
            throw new ArgumentNullException(nameof(value), "Tuple element cannot be null");

        // Handle primitives directly without reflection
        if (elementType == typeof(bool))
        {
            *dest = (byte)((bool)value ? 1 : 0);
        }
        else if (elementType == typeof(byte))
        {
            *dest = (byte)value;
        }
        else if (elementType == typeof(sbyte))
        {
            *(sbyte*)dest = (sbyte)value;
        }
        else if (elementType == typeof(short))
        {
            *(short*)dest = (short)value;
        }
        else if (elementType == typeof(ushort))
        {
            *(ushort*)dest = (ushort)value;
        }
        else if (elementType == typeof(int))
        {
            *(int*)dest = (int)value;
        }
        else if (elementType == typeof(uint))
        {
            *(uint*)dest = (uint)value;
        }
        else if (elementType == typeof(long))
        {
            *(long*)dest = (long)value;
        }
        else if (elementType == typeof(ulong))
        {
            *(ulong*)dest = (ulong)value;
        }
        else if (elementType == typeof(float))
        {
            *(float*)dest = (float)value;
        }
        else if (elementType == typeof(double))
        {
            *(double*)dest = (double)value;
        }
        else if (elementType == typeof(nint))
        {
            *(nint*)dest = (nint)value;
        }
        else if (elementType == typeof(nuint))
        {
            *(nuint*)dest = (nuint)value;
        }
        else if (typeof(ISwiftObject).IsAssignableFrom(elementType))
        {
            // For ISwiftObject types, use MarshalToSwift through the interface
            var swiftObject = (ISwiftObject)value;
            var metadata = GetTypeMetadataForType(elementType);
            var span = new Span<byte>(dest, (int)metadata.Size);
            swiftObject.MarshalToSwift(ref span);
        }
        else
        {
            throw new NotSupportedException($"Cannot marshal tuple element type {elementType.Name} to Swift");
        }
    }

    /// <summary>
    /// Marshals a single element from Swift memory using direct pointer access.
    /// </summary>
    [RequiresDynamicCode("Non-primitive element marshalling uses reflection")]
    private static unsafe object? MarshalElementFromSwiftUnsafe(IntPtr source, Type elementType)
    {
        // Handle primitives directly without reflection
        if (elementType == typeof(bool))
        {
            return ((*(byte*)source) & 1) != 0;
        }
        else if (elementType == typeof(byte))
        {
            return *(byte*)source;
        }
        else if (elementType == typeof(sbyte))
        {
            return *(sbyte*)source;
        }
        else if (elementType == typeof(short))
        {
            return *(short*)source;
        }
        else if (elementType == typeof(ushort))
        {
            return *(ushort*)source;
        }
        else if (elementType == typeof(int))
        {
            return *(int*)source;
        }
        else if (elementType == typeof(uint))
        {
            return *(uint*)source;
        }
        else if (elementType == typeof(long))
        {
            return *(long*)source;
        }
        else if (elementType == typeof(ulong))
        {
            return *(ulong*)source;
        }
        else if (elementType == typeof(float))
        {
            return *(float*)source;
        }
        else if (elementType == typeof(double))
        {
            return *(double*)source;
        }
        else if (elementType == typeof(nint))
        {
            return *(nint*)source;
        }
        else if (elementType == typeof(nuint))
        {
            return *(nuint*)source;
        }
        else if (typeof(ISwiftObject).IsAssignableFrom(elementType))
        {
            // For ISwiftObject types, use NewFromPayload through reflection
            var helperType = typeof(SwiftObjectHelper<>).MakeGenericType(elementType);
            return helperType.GetMethod("NewFromPayload")!.Invoke(null, new object[] { source });
        }
        else
        {
            throw new NotSupportedException($"Cannot marshal tuple element type {elementType.Name} from Swift");
        }
    }

    /// <summary>
    /// Creates a ValueTuple from an array of element values.
    /// </summary>
    [RequiresUnreferencedCode("ValueTuple constructor access")]
    private static T CreateValueTuple<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>(Type tupleType, object?[] values)
    {
        // Use the ValueTuple constructor directly
        var constructor = tupleType.GetConstructor(tupleType.GetGenericArguments())
            ?? throw new InvalidOperationException($"Could not find constructor for {tupleType.Name}");

        return (T)constructor.Invoke(values);
    }
}
