#!/bin/bash
# Build the Swift wrapper library

set -e

cd "$(dirname "$0")/output-ios"

# Check if Swift.Lottie.swift exists (generated by binding tool)
if [ ! -f "Swift.Lottie.swift" ]; then
    echo "Swift.Lottie.swift not found - run regenerate-bindings.sh first"
    exit 1
fi

# Check if SwiftBindings.swift exists
if [ ! -f "SwiftBindings.swift" ]; then
    echo "SwiftBindings.swift not found - run regenerate-bindings.sh first"
    exit 1
fi

xcrun swiftc -emit-library -target arm64-apple-ios15.0-simulator \
  -sdk $(xcrun --sdk iphonesimulator --show-sdk-path) \
  -F ../Lottie.xcframework/ios-arm64_x86_64-simulator/ \
  -module-name SwiftBindings \
  -Xlinker -install_name -Xlinker @rpath/SwiftBindings.framework/SwiftBindings \
  -o SwiftBindings.framework/SwiftBindings \
  Swift.Lottie.swift SwiftBindings.swift

# Also update the xcframework copy (test app uses this)
cp SwiftBindings.framework/SwiftBindings SwiftBindings.xcframework/ios-arm64-simulator/SwiftBindings.framework/SwiftBindings

echo "Swift wrapper built successfully"
